### PR TITLE
feat: pass sellAmount to TwapSuggestionBanner on TWAP page link

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Make the TWAP banner suggestion on SWAP orders to include the sell amount in the link

image

https://github.com/cowprotocol/cowswap/assets/43217/ad33428b-90c7-440e-a270-46eef2e50799

# To Test

1. On SWAP fill in the sell order with significant slippage as to see the TWAP banner
2. Click on the TWAP link
* The sell amount should be kept when moving to the new tab

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , great job!
However, I noticed that the link does not fills in an amount in the TWAP sell field when I open the app for the 1st time, and click on the link for the 1st time. 

Also, I noticed one more edge case issue: 
1. Banner is displayed based on the fast quotes (see #2971 issue)
2. when I press on the link on the banner, I'm navigated to the TWAP page, but there is no amount/selected token in the field
3. when I return back, I see no 'suggest TWAP' banner :)

**Review by shoom3301 — APPROVED** [review]

**Comment by alfetopito** [comment]
> @alfetopito please, change the target branch to 1.44

It depends on https://github.com/cowprotocol/cowswap/pull/2967
That PR is already pointing to 1.44

**Comment by alfetopito** [comment]
> > Hey @alfetopito , great job! However, I noticed that the link does not fills in an amount in the TWAP sell field when I open the app for the 1st time, and click on the link for the 1st time.
> > Also, I noticed one more edge case issue:
> > ```
> > 1. Banner is displayed based on the fast quotes (see [[1.44]Don't show 'Suggest TWAP' banner until a price is finally loaded #2971](https://github.com/cowprotocol/cowswap/issues/2971) issue)
> > ```
> 
> Replied [in the previous PR](https://github.com/cowprotocol/cowswap/pull/2967#issuecomment-1660279138)
> 
> > ```
> > 2. when I press on the link on the banner, I'm navigated to the TWAP page, but there is no amount/selected token in the field
> > ```
> 
> No? Hmm, it worked while testing. I'll check if I forgot to push something...
> 
> > ```
> > 3. when I return back, I see no 'suggest TWAP' banner :)
> > ```
> 
> That depends on the banner display logic, should behave the same as the release PR since this one doesn't change it

Update: it does work to fill in the form when following the link **for the first time only**.
If you had already filled in the TWAP form, it doesn't.
Will work on a fix

**Comment by elena-zh** [comment]
Hey @shoom3301 , the issue is still here: 
1. I open the app for the 1st time
2. I specify a Swap amount that should show me the banner
3. When I press on the banner, the amount does not appear in the Advanced sell field. 
4. It starts to work on the 2nd press

**Review by elena-zh — APPROVED** [review]

**Pull request merged**
