### PR TITLE
Remove COW from locked GNO from subsidy calculation

### LINKED ISSUE #497: Hide subsidy for GNO lock
We want to remove COW vested from locked GNO from the subsidy calculation until the BE implements this functionality.

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #497

Removes COW from locked GNO from vested calculation and also from header balance button

## To test
- we want to make sure that the COW vested from locked GNO is not included in the subsidy percentage and balance button

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Nice you parametriced. It would be enough with commenting out.

When we start using the locked gno for subsidy, I would revert this PR, because I don't think we will need the parametrisation in the future.

**Comment by elena-zh** [comment]
@nenadV91 , then, I think, we should remove this amount from the (v)COW button's balance
image

WDYT?

**Comment by nenadV91** [comment]
@anxolin I've changed it to comments to remove locked balance from both header button and subsidy as @elena-zh suggested.

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Comment by elena-zh** [comment]
Btw, I have reopened #409 issue in order not to forget to add it when BE functionality is ready.

**Pull request merged**
