### PR TITLE
Progress of execution UI

### LINKED ISSUE #321: Progress of execution UI
**Description**

UI implementation of the progress bar component discussed in https://github.com/gnosis/cowswap/issues/1946
Documentation:  https://docs.google.com/document/d/1rJPCmztsbpIi-jklCFAQIrrPusIBYmrJvswB26I8AWA/edit#heading=h.gjdgxs
Design: https://www.figma.com/file/bcoZf5RIgVKDItdOaTZq18/GP-Swap?node-id=4167%3A93
Group 183
Group 185
Group 181
Group 189
Group 193
Group 192

> Original issue https://github.com/gnosis/cowswap/issues/2545 by @ramirotw

### PR DESCRIPTION
**Pull request by alongoni**
# Summary
🚧 WIP 🚧 Only UI component. The logic and calcs will be implemented in a separated PR-
Fixes #321 (from https://github.com/gnosis/cowswap/issues/2545)
image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alongoni , great changes! Some nitpicks from my side: 
1. I'd remove colon before 'Cancel order' button
remove colon
2. Besides, I'd keep this button in 1 line in the sentence
upper
3. I do not know whether it is possible to implement in this PR, but I'd remove this sentence at all when connected to SC wallets (Gnosis safe, Argent, Pillar), as we can't cancel orders when connected to them. 
remove when connected to Safe
4. Seems like COW icon does not fully covers the bar
overlap
5. I'd increase the margin between gnosis safe block and the bar in order to correspond to the rest margins in the modal
increase margin to correspond
6. I have some doubts relates to the 'tick' icon when 'Looking for a cow'. In my understanding, the tick means something like a 'finished' action. But we are 'looking', so the process is in not finished. 
Could we replace it with a 'clock icon and make it in 'green' instead f the 'tick' icon? WDYT?
clock
Thanks!

**Comment by ramirotw** [comment]
> 3\. I do not know whether it is possible to implement in this PR, but I'd remove this sentence at all when connected to SC wallets (Gnosis safe, Argent, Pillar), as we can't cancel orders when connected to them.

@elena-zh this is going to be tackled in the integration PR, this is just the UI

**Comment by elena-zh** [comment]
Hey @alongoni ! Great changes!

Sorry if I did not explained correctly, but under the p.6 I meant this change: 
clock

**Review by elena-zh — APPROVED** [review]
Changes LGTM now!

**Review by ramirotw — APPROVED** [review]
💅

**Pull request merged**
