### PR TITLE
feat(yield): define token category by default for selection

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Implementation of the logic described in [Figma](https://www.figma.com/design/iIblVIbidg7oG3SdgNCsde/Vampire-Attack-2024-Sept?node-id=0-1&node-type=canvas&t=4bDFGhz5CMEYtznt-0).

The main logic of this PR is defined in `getDefaultTokenListCategories()`:

1. When select Sell token and there is any LP-token with balance, then select "Pool tokens" tab by default
2. When select Sell token and there is NO LP-tokens with balance, then select "All" tab by default
3. When select Buy token and Sell token is CoWAMM token, then select "Pool tokens" tab by default
4. When select Buy token and Sell token is LP token but not CoWAMM, then select "CoW AMM only" tab by default
5. When select Buy token and Sell token is ERC-20 token, then hide "All" tab and select "CoW AMM only" tab by default

# To Test

See above

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , the build failed. Could you please check it?

**Comment by shoom3301** [comment]
@elena-zh done

**Comment by elena-zh** [comment]
Hey @shoom3301 , 

1. `When select Sell token and there is NO LP-tokens with balance, then select "All" tab by default`
 is not working as there is no All tab on the form
image

2. I don't have liquidity tokens on sepolia, but I have then on other chains for this address. The list is opened on CoW AMM tab (empty). I think, it should be opened on All tab
all is missing

3. Pool tokens tab duplicates tokens:
duplicating


4. Trade mode selector on a reduced screen. To reproduce, please open it from the swap widget
trade mode

5. When Buy token is CoWAMM token, all is displayed in the token list instead of "Pool tokens" tab by default
image
image

6. When Buy token is any LP token, all is displayed in the token list instead of "CoW AMM" tab by default

**Comment by shoom3301** [comment]
@elena-zh thank you!

1. I couldn't reproduce that. Could you record a video please? Or let's make a call
2. It's a bit problematic to handle this case for Sepolia. Let's skip it for now, I would eventually even hide Yield widget for Sepolia
3. Fixed
4. https://github.com/cowprotocol/cowswap/pull/5023
5. Fixed
6. It should work like that. We should not motivate people move liquidity from COW AMM

**Comment by elena-zh** [comment]
Hey @shoom3301 , 

still I have some issues with: 
1. `When select Sell token and there is any LP-token with balance, then select "Pool tokens" tab by default` is not working for me: instead of pool tokens it opens 'CoW AMM' tab
2. `When select Sell token and there is NO LP-tokens with balance, then select "All" tab by default` here is the video: https://www.loom.com/share/5b3c820c61c94277a5f7c6f8f3d26bb2
In the video, there is ERC20 token is picked in the sell field, But when I change it to any pool token, it opens CoW AMM tab (case 4 from your description)
3. 

> > When Buy token is any LP token, all is displayed in the token list instead of "CoW AMM" tab by default
> It should work like that. We should not motivate people move liquidity from COW AMM

Then why if I select CoW AMM in the sell field, it opens Pool tokens by default it the Buy token? I mean, it should work the same in both directions

Yes, lets discuss this in a call.

**Review by elena-zh — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
