### PR TITLE
Twap/save amount banner styling

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Styling savings banner

Screenshot 2023-07-26 at 12 50 19

Screenshot 2023-07-26 at 13 14 42

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]
Awesome!

**Comment by elena-zh** [comment]
Hey @fairlighteth , in the dark mode the banner looks a bit too toxic green to me
image
Maybe we should enhance a bit text's color there?

Thanks

**Comment by fairlighteth** [comment]
@elena-zh I'd propose to leave as is and would suggest to have a separate PR to address these colors ( a bit more involved ..)

**Review by elena-zh — APPROVED** [review]
Hey @fairlighteth , created #2940 task for this. 
Thanks!

**Pull request merged**
