### PR TITLE
Setup for amplitude tracking

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Implements a new type of analytics https://analytics.amplitude.com/
Some of the events in this PR are
- Different page views
- Open currency select modal
- Pick a currency
- Import a new token

# Testing
- Go to the https://analytics.amplitude.com/cowswap-test/activity
- Open the Demo and create few events mentioned above or just change few pages
- In a few moments there should be data related to those event in the Amplitude console
Screenshot from 2022-09-20 16-36-36
- You can click on user id and see a View with events in chronological order of that user with more details
Screenshot from 2022-09-20 16-37-39

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Code-wise looks ok, but how can we test this?

I logged onto Amplitude dashboard but I don't see anything there.
Is it possible to verify the events in the console somehow?

**Comment by nenadV91** [comment]
One simple way is to go to https://analytics.amplitude.com/cowswap-test/activity

**Comment by elena-zh** [comment]
I've been able to see all events from the description
image
However: 
1. navigation to a page was logged only once (I Opened Account page, the event was logged. Then I moved to Swap page. And when I returned back to the account page, the event was not logged)
2. It would be nice to add details what page is in the 'Page Viewed' event
3. The same for tokens (token selected/token imported) events.
Thanks!

**Comment by nenadV91** [comment]
@elena-zh 
1. Should be fixed now, there was an issue with older version of Amplitude package so after version update seems the issue is fixed
2. and 3. There is already more data for the events but its visible if you click on some user id and then below in the Event Stream panel you click on some event, and then you will see for example
Page view 
Screenshot from 2022-09-20 16-39-25
Token select
Screenshot from 2022-09-20 16-47-15

**Comment by nenadV91** [comment]
> Is it possible to verify the events in the console somehow?

You can also just filter Network tab with `amplitude` or `httpapi`

**Comment by elena-zh** [comment]
Hey @nenadV91 , cool, thanks!

**Review by elena-zh — APPROVED** [review]

**Comment by nenadV91** [comment]
Merging this since Elena approved and we can do a code review post merge

**Pull request merged**
