### PR TITLE
chore(advanced-orders): read sell amount from url for TWAP

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

While SWAP and LIMIT orders can take `sellAmount` (and `buyAmount`) from the url params, ADVANCED did not.

This PR is a very quick and dirty solution to make it available

Next step is to refactor all 3 into a single location as it's pretty much copy and paste.
For now I'm implementing it this way to not delay it any further.

# To Test

1. Load the app on advanced orders with the url param `sellAmount=2` or whatever amount (example: https://swap-dev-git-sell-amount-url-for-twap-cowswap.vercel.app/#/1/advanced-orders/WETH?sellAmount=4)
* The amount set in the url should be set onto the sell amount
* The parameter should be removed from the URL

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , the param is not set when open the app using a direct link for the 1st time. The [link ]( https://swap-dev-git-sell-amount-url-for-twap-cowswap.vercel.app/#/1/advanced-orders/WETH?sellAmount=4)navigates me to the Swap page
image

When I paste the link for the 2nd time, it will work. 

Also I wonder how it can work with Safe app: 
image

Thanks

**Comment by alfetopito** [comment]
> Hey @alfetopito , the param is not set when open the app using a direct link for the 1st time. The [link ](https://swap-dev-git-sell-amount-url-for-twap-cowswap.vercel.app/#/1/advanced-orders/WETH?sellAmount=4)navigates me to the Swap page image
> 
> When I paste the link for the 2nd time, it will work.

Yeah, I noticed that too, and we should fix it.
Still, for the internal link (warning banner) it should work, so that has less priority IMO
 
> Also I wonder how it can work with Safe app: image

The Safe doesn't allow url parms for apps AFAICT, so it won't work

**Review by shoom3301 — APPROVED** [review]
Haven't tested, but code looks good

**Review by elena-zh — APPROVED** [review]
Hey @shoom3301 , case 1 from this [comment ](https://github.com/cowprotocol/cowswap/pull/2967#issuecomment-1659923037) is still reproducible to me here

**Comment by shoom3301** [comment]
@elena-zh the branch was not up to date, fixed that, now the case 1 is fixed

**Review by elena-zh — APPROVED** [review]
Changes LGTM now!

**Pull request merged**
