### PR TITLE
Disable anniversary release

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Disable anniversary release

  # To Test

1. Open the page
* Should not contain the anniversary banner
2. Place an order
* Should have the regular cow sound

### CODE REVIEW

**Review by W3stside — APPROVED** [review]
Couldnt we just flag disable it? Be8st year we'll do this again likely

**Comment by alfetopito** [comment]
> Couldnt we just flag disable it? Be8st year we'll do this again likely

Who knows what the UI will look like in 1 year. I wouldn't count it being very compatible then

**Comment by alfetopito** [comment]
Merging to start preparing the version.

Likely not going out today given the time and devops availability.

Still, would like to get it ready for as soon as we can

**Comment by alfetopito** [comment]
Merging to start preparing the version.

Likely not going out today given the time and devops availability.

Still, would like to get it ready for as soon as we can

**Pull request merged**
