### PR TITLE
fix(twap): always display price diff warning

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

image

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @shoom3301 , I still can reproduce the #2971 issue in the PR. See the video: https://www.loom.com/share/67589532a61c4bf48fdd1e3f278a6471

Then, I don't see the banner how much I will save when I'm on the read only mode 
image

**Comment by shoom3301** [comment]
So, I made a wrong assumption.
Actually, the price impact calculation process always use `OPTIMAL` price quality.
The reason why the price impact value is "jumping" is an implementation of `useHigherUSDValue`.
Sometimes coingecko API might fail and we go through another process and get another value.
I don't think we can fix it fast without significant refactoring.

**Comment by shoom3301** [comment]
@elena-zh the banner displays well for me.
The displaying conditions are matching the spec:
https://www.notion.so/cownation/FE-TWAP-Orders-c9f6bd5c23bd4c749147611dcb63daac?pvs=4#b719e9b8c73644f8919418125cb5c18e

**Review by elena-zh — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
THANKS!!!

**Pull request merged**
