### PR TITLE
[EthFlow]#1294 wire is refunded

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Wiring up refund state when order expires

# To Test

To test this, you must make one order expire, which the only way I found is to move the price of the pair against you.

1. Pick ETH as sell
2. Make sure deadline and slippage are set to the minimum possible (10min and 2% respectively) to make your life easier
3. Pick as buy a token that you have enough funds to move the liquidity a few %
4. Fill in a significant ETH value, for example 7 ETH (I only tested on Goerli!)
5. Open another browser window (or another browser/device) and select the same pair
6. Set the sell amount to an amount similar but not identical - like 7.001 - to avoid the identical order issues
7. Place the order on both windows in close sucession
* One order should match and move the price enough so the other order becomes out of market
8. Wait until the pending order expires
* A few seconds after expiring (between 15 to 30) the order status will change from `refunding... etc` to `Refunded` like in this image
Screenshot 2022-12-16 at 18 45 14

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Nice job, looks great. I guess it's a good call to add the updater since its quicker and lower risk for now

...but you explain Sasha when he is back, he won't like it :P 

Anyways, we need to clean up all the other updaters, this is just one more.

**Comment by alfetopito** [comment]
> Hey @alfetopito , great job! Just 1 question: why we hide links to a blockexplorer in this case? image
> 
> And I have not tested the feature in Mainnet/GC as I don't have so many funds to reproduce price OOM issue there.

The first tx will only be available in the original browser.
I assume the screenshot if taken from another device?
I can also happen to not show if not started on the current tab. Refreshing will fix this, as there's no active sync between multiple windows but it's stored on localStorage.

As for the second case, it's not available from the API yet.
Will be added when backend is ready

**Comment by elena-zh** [comment]
> I assume the screenshot if taken from another device?
No. The link was displayed when the order was in 'Initiating refund' state, and disappeared when the order was in 'Refunded' state. Will retest it in the HotFix branch once again

**Comment by elena-zh** [comment]
Hey @alfetopito , just forgot to mention another case: Cancel order button is still enabled when an order is cancelled on Explorer, but not in CoW Swap yet. And it calls onchain transaction. 

already expired

Can we hide this button somehow?

I'm bothering about it due to for regular orders we will receive 'Order expired' be error when we sign cancel request in this case. But for the ETH order the transaction will run, and a user will loose ETH for paying gas.

**Comment by alfetopito** [comment]
> Hey @alfetopito , just forgot to mention another case: Cancel order button is still enabled when an order is cancelled on Explorer, but not in CoW Swap yet. And it calls onchain transaction.
> 
> already expired
> 
> Can we hide this button somehow?
> 
> I'm bothering about it due to for regular orders we will receive 'Order expired' be error when we sign cancel request in this case. But for the ETH order the transaction will run, and a user will loose ETH for paying gas.

What do you mean by cancelled on Explorer?
Was it cancelled on another device/tab?

**Comment by elena-zh** [comment]
Hey @alfetopito , 

> What do you mean by cancelled on Explorer?
> Was it cancelled on another device/tab?

I'm sorry, I mixed up words. I meant 'expired on Explorer. I have updated the comment

**Comment by alfetopito** [comment]
Hmm, could it be an issue related to having the page opened in multiple tabs?
Otherwise it should update every 2sec and the API data and use the same cancellation logic as the Explorer

**Comment by elena-zh** [comment]
> Hmm, could it be an issue related to having the page opened in multiple tabs? Otherwise it should update every 2sec and the API data and use the same cancellation logic as the Explorer

No, it can't be. 
The issue is in a delay that we use before showing 'Expired' status (we wait up to 1 minute before updating it).

**Comment by alfetopito** [comment]
> > Hmm, could it be an issue related to having the page opened in multiple tabs? Otherwise it should update every 2sec and the API data and use the same cancellation logic as the Explorer
> 
> No, it can't be. The issue is in a delay that we use before showing 'Expired' status (we wait up to 1 minute before updating it).

Hmmm I see then.
I thought the way I handled ethflow orders would skip this delay but then I did it wrong.
Can you create an issue for this please?

**Comment by elena-zh** [comment]
Hey @alfetopito , 
> Hmmm I see then. I thought the way I handled ethflow orders would skip this delay but then I did it wrong. Can you create an issue for this please?

Reported in https://github.com/cowprotocol/cowswap/issues/1788  now. 

Thanks!

**Pull request merged**
