### PR TITLE
Fix for wrap mode

### LINKED ISSUE #1851: Word wrap mode is broken on content pages
Related to #1829
Related to FAQ/Terms/Policies pages on Development env-t

Open any content page and reduce a screen width
Check the text:

**AR**: see the image:

**ER**:

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1851

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @nenadV91 , changes LGTM!
However, the issue with links is back in this PR: 
image

**Comment by elena-zh** [comment]
> Hey @nenadV91 , changes LGTM! However, the issue with links is back in this PR: image

However, nevermind: this is reported in #1825 (case 8)

**Comment by anxolin** [comment]
Should it be like fairlight is saying? @nenadV91 

I would think so https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by elena-zh** [comment]
Hey @nenadV91 , @anxolin , I opened a separate task for links wrapping #1888

**Pull request merged**
