### PR TITLE
fix: rename Gnosis Safe -> Safe

### LINKED ISSUE #2286: Update Safe wallet name and links
1. Open the CoW Swap app inside the Safe app
2. Check the wallet name and links

**AR**: there is 'Gnosis' in the name of the wallet

safe1

**ER**:  it should be “Connected with Safe” and farther down, “View Safe.”

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2286

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
However, there is still 'Gnosis' in the wallet name when open the app inside the safe app: 
image

**Comment by shoom3301** [comment]
@elena-zh  thanks! Fixed

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by anxolin — COMMENTED** [review]
👍

**Pull request merged**
