### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by shoom3301**
:robot: I have created a release *beep* *boop*
---

<details><summary>cowswap: 1.70.0</summary>

### Features

* notifications feed ([#4409](https://github.com/cowprotocol/cowswap/issues/4409)) ([d6f2987](https://github.com/cowprotocol/cowswap/commit/d6f2987b57e3b5bd90d029aca0215134ec1a050b))
* **usd-estimation:** add defillama price source ([#4341](https://github.com/cowprotocol/cowswap/issues/4341)) ([96a0343](https://github.com/cowprotocol/cowswap/commit/96a03437710b807c966debdaa8ce5219ddaff7a4))
* **wallets:** support eip6963 multi-injected providers ([#4416](https://github.com/cowprotocol/cowswap/issues/4416)) ([85a78bb](https://github.com/cowprotocol/cowswap/commit/85a78bbfe9b0a8fe5428b25aba0b38944b10987d))

### Bug Fixes

* **notifications:** don't fail when CMS API is down ([#4464](https://github.com/cowprotocol/cowswap/issues/4464)) ([6ba4e76](https://github.com/cowprotocol/cowswap/commit/6ba4e76d89304cea1941ba77dd9d976911338288))
* **twap:** lower minimum sell amount ([#4428](https://github.com/cowprotocol/cowswap/issues/4428)) ([fb9e91b](https://github.com/cowprotocol/cowswap/commit/fb9e91ba5e46a2df3bef15842a5da9a1cfa6d534))
* **widget-cfg:** don't request network switching with standalone mode ([#4463](https://github.com/cowprotocol/cowswap/issues/4463)) ([41ef4cc](https://github.com/cowprotocol/cowswap/commit/41ef4cc83358c17742fb3e5472e1aa8dc19d475d))
</details>

<details><summary>explorer: 2.29.6</summary>

### Bug Fixes

* **explorer:** reduce retries for tx orders requests ([#4438](https://github.com/cowprotocol/cowswap/issues/4438)) ([2ee1a8d](https://github.com/cowprotocol/cowswap/commit/2ee1a8dfa79aed6d68a89feae7a3c757addcbdf0))
</details>

<details><summary>cow-fi: 1.0.0</summary>

### Features

* add SEO image and fallback to cover image ([#4427](https://github.com/cowprotocol/cowswap/issues/4427)) ([7a83add](https://github.com/cowprotocol/cowswap/commit/7a83add4d3d59548d36b552e5bf95d5ad90d7296))
* **cms:** add blog page with an article ([#4421](https://github.com/cowprotocol/cowswap/issues/4421)) ([5cfde16](https://github.com/cowprotocol/cowswap/commit/5cfde16ca25b442cb88abbd957339a9c4a56643a))
* **cms:** markup Category page and display all articles ([#4334](https://github.com/cowprotocol/cowswap/issues/4334)) ([57a9657](https://github.com/cowprotocol/cowswap/commit/57a965717ec5f5d7058b3ff23963256206744a22))
* **cow-fi:** migrate cow-fi to monorepo ([#4332](https://github.com/cowprotocol/cowswap/issues/4332)) ([5cb9821](https://github.com/cowprotocol/cowswap/commit/5cb9821147b2ba1c471287582f54637d79de995b))
* **learn:** add feature flag for learn ([#4436](https://github.com/cowprotocol/cowswap/issues/4436)) ([1ecbc4f](https://github.com/cowprotocol/cowswap/commit/1ecbc4f96266f85a077c8b8d8b56dec4b82c8311))

### Bug Fixes

* **cow-fi:** fix buttons style ([#4361](https://github.com/cowprotocol/cowswap/issues/4361)) ([6283bdd](https://github.com/cowprotocol/cowswap/commit/6283bddab696da777b679624a0d19a85c16d245c))
* **cow-fi:** hide link to Learn page ([#4356](https://github.com/cowprotocol/cowswap/issues/4356)) ([a261d38](https://github.com/cowprotocol/cowswap/commit/a261d3813227441bf295800af639a58e31e64f11))
</details>

<details><summary>widget-configurator: 1.2.1</summary>

### Bug Fixes

* **widget-cfg:** don't request network switching with standalone mode ([#4463](https://github.com/cowprotocol/cowswap/issues/4463)) ([41ef4cc](https://github.com/cowprotocol/cowswap/commit/41ef4cc83358c17742fb3e5472e1aa8dc19d475d))
</details>

<details><summary>analytics: 1.2.0</summary>

### Features

* **wallets:** support eip6963 multi-injected providers ([#4416](https://github.com/cowprotocol/cowswap/issues/4416)) ([85a78bb](https://github.com/cowprotocol/cowswap/commit/85a78bbfe9b0a8fe5428b25aba0b38944b10987d))
</details>

<details><summary>assets: 1.2.0</summary>

### Features

* notifications feed ([#4409](https://github.com/cowprotocol/cowswap/issues/4409)) ([d6f2987](https://github.com/cowprotocol/cowswap/commit/d6f2987b57e3b5bd90d029aca0215134ec1a050b))
</details>

<details><summary>common-const: 1.2.0</summary>

### Features

* **wallets:** support eip6963 multi-injected providers ([#4416](https://github.com/cowprotocol/cowswap/issues/4416)) ([85a78bb](https://github.com/cowprotocol/cowswap/commit/85a78bbfe9b0a8fe5428b25aba0b38944b10987d))
</details>

<details><summary>ens: 1.1.0</summary>

### Features

* **wallets:** support eip6963 multi-injected providers ([#4416](https://github.com/cowprotocol/cowswap/issues/4416)) ([85a78bb](https://github.com/cowprotocol/cowswap/commit/85a78bbfe9b0a8fe5428b25aba0b38944b10987d))
</details>

<details><summary>wallet: 1.3.0</summary>

### Features

* **usd-estimation:** add defillama price source ([#4341](https://github.com/cowprotocol/cowswap/issues/4341)) ([96a0343](https://github.com/cowprotocol/cowswap/commit/96a03437710b807c966debdaa8ce5219ddaff7a4))
* **wallets:** support eip6963 multi-injected providers ([#4416](https://github.com/cowprotocol/cowswap/issues/4416)) ([85a78bb](https://github.com/cowprotocol/cowswap/commit/85a78bbfe9b0a8fe5428b25aba0b38944b10987d))
</details>

<details><summary>wallet-provider: 1.0.0</summary>

### Features

* **wallets:** support eip6963 multi-injected providers ([#4416](https://github.com/cowprotocol/cowswap/issues/4416)) ([85a78bb](https://github.com/cowprotocol/cowswap/commit/85a78bbfe9b0a8fe5428b25aba0b38944b10987d))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/cowswap-v1.70.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/cow-fi-v1.0.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/widget-configurator-v1.2.1 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/analytics-v1.2.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/assets-v1.2.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/common-const-v1.2.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/ens-v1.1.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/wallet-provider-v1.0.0 :sunflower:

**Pull request merged**
