### PR TITLE
feat(yield): fetch balances for LP-tokens

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

1. Extracted `VirtualList` component in order to reuse it for LP-tokens list
2. Added styles for the LP-token selector ([figma](https://www.figma.com/design/iIblVIbidg7oG3SdgNCsde/Vampire-Attack-2024-Sept?node-id=0-1&node-type=canvas&t=11sRKIInKrIrFEzk-0))
3. Added balances caching. Only >0 values are cached into localStorage
4. Added balances and allowances fetching for LP-tokens. The fetching mechanism for LP is different:
 - it starts with 3 sec delay
 - it's longer, because it doesn't send all requests at once, but execute them one after another. We have to do that, because node starts answering 429 error due to too much requests

image

# To Test

1. In Yield widget, the token selector should display All, Pool tokens, CoW AMM only tabs
2. Pool tokens should be displayed
3. APR is hardcoded, tooltip is hardcoded, LP-token logo is not stylized yet

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job, thank you!

Some issues from my side: 
1. Should we show all these token lists on a chain (for now, on Sepolia) where there are no relevant tokens? 
sepolia
2. The lists are not displayed for geo-blocked area. Asked about it [here](https://cowservices.slack.com/archives/C07M5DZHMHC/p1729252605388729). But as for the current behavior it makes this feature not accessible from there. 
3. When nothing to display in the list (both on the Pool tokens and CoW AMM tabs) it would be nice to hide a table's header (?) and show a message like we do in a regular token list
cow amm no
nothing to display
4. Should 'Create pool' button navigate to a pool creator [app ](https://pool-creator.balancer.fi/cow)instead of balancer pools list? 
5. It would be nice to improve balances view in the list: 
tiny balance
6. There is no indication of a sort order in the table (it exists on the mock-up)
default sort indic
sort
7. It is impossible to select a token from a list: nothing happens when I click on it
8. Search for a token is not working on newly added tabs
9. (maybe for @fairlighteth ): it would be nice to improve the list displaying in a mobile view: 
icons mobile
scrollbar hor
view

Thanks!

**Comment by fairlighteth** [comment]
@shoom3301 I will handle the layout issues in https://github.com/cowprotocol/cowswap/pull/5014

**Comment by shoom3301** [comment]
@elena-zh 

1. I would spend time on special cases in Sepolia. The Yield feature is not really working in this network since there are not so much LPs. Since this is test-net I would keep it as it is.
2. Fixed
3. Fixed
4. This wasn't specified, but I trust you. Changed the link
5. Fixed
6. I will implement the sorting in another PR
7. Implemented in the next PR https://github.com/cowprotocol/cowswap/pull/5013
8. Implemented in the next PR https://github.com/cowprotocol/cowswap/pull/5013
9. Fixed in https://github.com/cowprotocol/cowswap/pull/5014

**Comment by elena-zh** [comment]
Hey @shoom3301 , everything is great besides geo-blocking feature: I still don't see these token lists from the blocked area: 
image

**Review by elena-zh — APPROVED** [review]
Approved then!

**Review by alfetopito — APPROVED** [review]
One issue I noticed, when I'm not connected the loading effect is playing 
image

**Comment by shoom3301** [comment]
> One issue I noticed, when I'm not connected the loading effect is playing image

Thank you! This is already fixed in another PR

**Pull request merged**
