### PR TITLE
fix(twap): allow creating orders with 100% slippage

### LINKED ISSUE #3734: Impossible to create a TWAP with 100% slippage
**Description**
The protocol don't allow pure market orders. At least you need to be willing to receive 1 wei of buy token (0 is not allowed)

Currently, if you define a slippage of 100%, then the order will show you are willing to receive 0 buy tokens.
image

This is an invalid order, therefore Watch Tower will drop it.

Watch Tower Logs:
image

**How to Reproduce**
1. Place a TWAP, make sure price proctection is 100%
4. Check watch tower logs

**Expected behavior**
The UI should force to receive at least 1 wei

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #3734

When price protection is 100%, then return 1 wei as buy amount

  # To Test

1. Setup a TWAP order
2. Set "price protection" to 100%
- [ ] Minimum receive should be ~"0.0000001"
- [ ] Order should be filled in the future

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @shoom3301 , great!
However, part hangs in the 'Creating' state and does not go to Open. Could you lease take a look? 
image

**Comment by anxolin** [comment]
```
2024-02-22T11:31:51.295Z DEBUG pollConditionalOrder:pollConditionalOrder: 11155111:5.8@5340592:  Polling id 0xa9b12fccdbde0dc61f2afebbe7cfdd4ca290af4ace02ed0a387174107fc191ea. Order twap (0xa9b12fccdbde0dc61f2afebbe7cfdd4ca290af4ace02ed0a387174107fc191ea): {"sellAmount":"100000000000000000","sellToken":"0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14","buyAmount":"0","buyToken":"0x0625aFB445C3B6B7B929342a04A22599fd5dBB59","numberOfParts":"4","startTime":"AT_MINING_TIME","timeBetweenParts":900,"durationOfPart":"AUTO","receiver":"0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531","appData":"0x9017376397342b120a2c3cfc447833ba934c622df5e9fc61f9f7d2d9c8532a75"} using block (5340592)....
```

According to the logs, we still add `buyAmount: 0`

**Comment by shoom3301** [comment]
@elena-zh @anxolin oops, sorry, fixed.
Now order successfully created.

image

**Review by elena-zh — APPROVED** [review]
Works now, thank you!

**Review by anxolin — COMMENTED** [review]
Thanks!

**Pull request merged**
