### PR TITLE
Add zengo wallet option

### LINKED ISSUE #786: Add ZenGo wallet (to Web3Modal)
Based on slack message here: https://cowservices.slack.com/archives/C036G0J90BU/p1657102524972719

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #786

This adds a separate Zengo wallet option that uses a wallet-connect connector

Screenshot 2023-02-23 at 12 39 01

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @nenadV91 , nice changes!
I have not been able to run all transactions when connected to Zengo, will do it a bit later as gas prices are too high now. But Wrap TX works. 

Some issues that I noticed: 
1. When connected to Zengo, 2 options are highlighted in the connect modal: 
2 options are highlighted
I think, we should highlight only Zengo if we are connected to it, and disable WC option + show tooltip above the disabled WC button that will explain that user needs to disconnect Zengo in order to connect another WC wallet
2. I have been able to connect to another WC wallet using Zengo (and as far as I can understand we have nothing to do with this). So in this case I would highlight only WC option and disabled Zengo option in the connection modal + show the same tooltip as I have described in the p1.
3. I see 'Vercel' in the connection modal/confirm TX modals Is this OK for now? 
image

Could you please take a look at these issues?

**Comment by elena-zh** [comment]
For mobile connection, can we show ZenGo at the top of the list once we open the WC modal?
image
Or can we 'pre-fill' Zengo in the search field inside this modal?
image

Frankly, search field is not working on my mobile device, so I'm not sure whether we can change there or not :(

**Comment by elena-zh** [comment]
The last note: it would be great to hide this option when the app is opened in MM integrated browser ;)

**Review by anxolin — COMMENTED** [review]
Code wise, fine with me, but pls note that you are in an outdated branch.

Yesterday i mentioned that I would update develop to move most of the files so we can start to structure this files better and reduce our dependencies

**Review by anxolin — APPROVED** [review]

**Comment by nenadV91** [comment]
Hi @elena-zh,
1 and 2 should be fixed in the following Ambire PR
3. does this happens on prod also when you use WC connector?
4. For the mobile, I think that can be a good to have and we leave it for now.

**Comment by elena-zh** [comment]
> does this happens on prod also when you use WC connector?

**Comment by elena-zh** [comment]
@nenadV91 , 
> does this happens on prod also when you use WC connector?

On Prod it shows correct icon 
image

**Comment by nenadV91** [comment]
@elena-zh I think it will show correct text once its deployed to prod also

**Review by elena-zh — APPROVED** [review]
Approved given the fact that issues 1-2 are fixed #2055, issue 3 will check in Dev/Staging/Prod, and case 4 is listed in the [notion ](https://www.notion.so/cownation/Questions-and-discussion-testing-notes-062bad75d0424f27ad67e8a379edc8af) doc for further discussion

**Pull request merged**
