### PR TITLE
Explorer add feebreakdown

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Adds a breakdown component for Order Surplus and Cost & Fees
- Fixes the order detail view (cc @elena-zh ) to have a fixed view without horizontal scrolling
- Misc. code optimisations and cleanup

Screenshot 2024-07-05 at 13 54 13

https://github.com/cowprotocol/cowswap/assets/31534717/212179be-c9ce-40a4-adf0-f041bb8f8521

## Todo:
- Right now most values in the breakdown are marked as TODO and still need to be implemented with the actual retrieved/calculated values.

### CODE REVIEW

**Comment by fairlighteth** [comment]
Commented out the NumbersBreakdown for when the API is ready

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Opened #4690 and #4691 tasks for issues I've faced

**Review by anxolin — COMMENTED** [review]
Looks great

**Comment by MindyCoW** [comment]
### **Tooltip texts ahoy!**

**Tooltips for existing elements:**
- Order Surplus: The difference between the order’s limit price and the actual execution price. (This number is averaged for orders with partial fills.)
- Costs & Fees: The network costs and any fees paid for this order. (This will show a progressive number for partial fills. It might take a few minutes to update.)

**Let's add info icons & tooltips to the following elements in the Order Surplus and Costs & Fees breakdowns:**
- Protected Slippage: This is the difference between the limit price and the price quoted in the UI. On another exchange, this amount may have been lost to MEV.
- Price Improvement (User Share): These are extra tokens a user receives on top of the amount they were initially quoted. All extra tokens the protocol generates above the quoted amount are currently split 50/50 between CoW Protocol and the user. 
- Network Costs: The cost of settling the order. This includes gas costs, LP fees, and any other costs incurred by the solver.
- Fee: (Normal “total fee” tooltip text)

Finally, **can we please update the capitalization** of "Order Surplus" and its breakdown elements so that each word is capitalized (i.e. not "Order surplus" but "Order Surplus", not "Price improvement (user share)" but "Price Improvement (User Share)"?

**Pull request merged**
