### PR TITLE
[ETH-FLOW] Address comments

### PR DESCRIPTION
**Pull request by W3stside**
Addresses comments by @elena-zh here: https://docs.google.com/document/d/1brzImR3f5_YVm3FUU3XZ-rl-nFpubg3yfe7RQ_wN4yg/edit?pli=1

1. [styles for gnosis safe](https://github.com/cowprotocol/cowswap/issues/1055)
2. wrap/unwrap eth modals
3. [creeping border-radius in wrap cards](https://github.com/cowprotocol/cowswap/issues/818#issuecomment-1239389351)

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @W3stside , the #818 issue is fixed here and looks great!
As for the  #1055 issue, I noticed that the boarder is removed from the modal. 
boarder is missing
Just want to clarify it with the team @fairlighteth , @alfetopito , @anxolin : if it looks good to you? 

As for the issue with a number of Transactions on the modal, it seems still not fixed: the 1st transaction is displayed at the bottom, the 2nd transaction is displayed on the top
order is not changed

Thanks!

**Comment by alfetopito** [comment]
> Just want to clarify it with the team @fairlighteth , @alfetopito , @anxolin : if it looks good to you?

Looks ok to me. Anything specific that you think is not ok?

**Comment by elena-zh** [comment]
> > Just want to clarify it with the team @fairlighteth , @alfetopito , @anxolin : if it looks good to you?
> 
> Looks ok to me. Anything specific that you think is not ok?

Nope, It looks good to me as well. But don't want to make a judgement on behalf of the team based on my opinion only.

**Comment by W3stside** [comment]
merging these changes, we can address more in another PR

**Comment by elena-zh** [comment]
LGTM!

**Pull request merged**
