### PR TITLE
Fix modal overlay (full height)

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Fixes https://github.com/cowprotocol/cowswap/issues/1790

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Hey @fairlighteth , great job!
The PR also fixes #1778 bug. 

I have some issues with rights in the GH now, and I can't connect this issue to the PR. Could you please to it? 

Thank you!

**Comment by fairlighteth** [comment]
Pushed another fix to add padding to the header in the ERROR modal:

Screenshot 2023-01-09 at 17 13 58

**Review by alfetopito — APPROVED** [review]

**Comment by alfetopito** [comment]
@fairlighteth wrong branch!
Please point it to `release/1.29.0` instead

**Review by elena-zh — APPROVED** [review]
I have also connected #1802 issue to the PR. 
Approved!

**Pull request merged**
