### PR TITLE
fix: vercel redirects

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Follow up to https://github.com/cowprotocol/cowswap/pull/4643 which broken sounds, some images, manifest for the Safe and so on.

This PR updates the rules so that the following prefixes and suffixes are NOT redirected:

- /#
- Anything that has an extension that's between 2 and 15 chars. E.g.: `/assets/bal.png`

# To Test

1. Open CoW Swap in a private browsing window (to prevent your browser's cache)
2. Use the app as usual
* All images (favicons, etc) should load
* Sounds should be played
* App should be addable to Safe as a custom Safe app
4. For sanity's sake, `curl` OR load them in the browser, one of each category. It should load the asset and NOT say `Redirecting...` if using `curl`, or just load/download the asset on the browser.

image

5. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/451.html
6. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/emergency.js
7. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/android-chrome-512x512.png
8. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/assets/network-arbitrum-one-logo-blue-CyPKvBTx.svg
9. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/safari-pinned-tab.svg
10. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/audio/success.mp3
11. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/fonts/Inter-roman.var.woff2
12. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/.well-known/walletconnect.txt
13. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/browserconfig.xml
14. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/manifest.json
15. https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app/manifest.webmanifest

# Note

As a nice trick to see which assets/paths should be accessible, we can check the Vercel build static assets https://vercel.com/cowswap/swap-dev/22CLcVfNgzY6qRANVHARrBSohbf2
image

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
Should te slashes be scaped? 
image


https://regex101.com/r/rr4K2v/1

**Comment by alfetopito** [comment]
> Should te slashes be scaped? image
> 
> https://regex101.com/r/rr4K2v/1

Back slashes, yes. Regular slashes, no need.
And it's not a regular regex, but a `path-to-regexp` https://www.npmjs.com/package/path-to-regexp

The resulting regex will have it escaped:

```
/^\/+(?:((?!#|assets\/|audio\/|fonts\/|images\/|manifest\.|\w+\.xml|.+\.html|.+\.png|.+\.svg|.+\.txt|.+\.js).+))(?:\/+)?$/i
```

image

**Review by elena-zh — COMMENTED** [review]
Hey @alfetopito , everything works great!
However, I'm able to catch a crash in incognito mode for https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app//11155111/swap/WETH
image

**Comment by alfetopito** [comment]
> Hey @alfetopito , everything works great! However, I'm able to catch a crash in incognito mode for https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app//11155111/swap/WETH image

I managed to reproduce this.

1. Load the page as usual
2. AFTER it's loaded, change the URL to a broken version, such as https://swap-dev-git-fix-vercel-redirects-cowswap.vercel.app////11155111/swap/gno/cow
3. It'll fail to load and serve an empty page

If the URL is accessed directly, it'll redirect and load fine.
I gave it a try and I suspect this issue is in the service worker.
Since it seems that most use cases don't cause a crash anymore, unless the user is actively inserting a bad URL, I'd like to merge it as is, and address that in another issue PR.

Would you be ok with that?

**Review by elena-zh — APPROVED** [review]
@alfetopito , works for me!

**Pull request merged**
