### PR TITLE
Fix order cancelled styling

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Fixes https://github.com/cowprotocol/cowswap/issues/4149 

Screenshot 2024-04-03 at 17 08 22
Screenshot 2024-04-03 at 17 06 42
Screenshot 2024-04-03 at 17 04 25
Screenshot 2024-04-03 at 17 04 05

Screenshot 2024-04-03 at 17 03 46

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by anxolin — APPROVED** [review]
Not a big deal, and i don't think is related to this PR, but for some reason Cosmos has different styles:

image

**Comment by elena-zh** [comment]
Hey @fairlighteth , thank you!
Just some nitpicking: for both cancelled and replaced states, it would be great to cross out the 'Receive GNO' on the last stet, and add a red label 'Transaction failed' to the 2nd step. 
image
same for replaced


See an example for the failed order:
like on failed case

Could you please fix this? 

Thanks!

**Comment by fairlighteth** [comment]
From my test, the extra label should be shown if `rejectReason` is available and provided in `apps/cowswap-frontend/src/modules/swap/pure/EthFlow/EthFlowStepper/steps/Step2.tsx` L34

Screenshot 2024-04-04 at 19 21 53
Screenshot 2024-04-04 at 19 23 04

**Comment by fairlighteth** [comment]
Also it should cross out on these conditions:
```
const crossOut = !isSuccess && wontReceiveToken
const wontReceiveToken = !isFilled && (isExpired || isOrderRejected || isRefunding || isCanceling || isRefunded)
```

**Comment by shoom3301** [comment]
>It seems that at least on my ETH trade on Sepolia a reason was not present for failure.

@fairlighteth in the case when transaction is replaced we don't have `rejectReason`, the only we have are `creationCancelled` and `creationReplaced`

**Comment by elena-zh** [comment]
> Just to confirm if we see the same, as for me the token is crossed out here: Screenshot 2024-04-04 at 19 07 07
> 
> And this is in the modal: Screenshot 2024-04-04 at 19 07 35

Hey @fairlighteth , I don't see 'view details' link on the 2nd step when an order TX was cancelled or replaced: the order in this case can't be created, so no link to Protocol Explorer should exist. 

I can't insist on the 'Transaction failed' or 'Transaction replaced' labels on the 2nd step as they duplicate messages in the 1st step, however, if a user does not receive a buying token (due to order was not created), IMO, logically, it would be nice to cross out this message (~~Receive GNO~~) on the 3rd step (add this cases into the condition?) :)

Thanks!

**Pull request merged**
