### PR TITLE
Fix scroll style

### LINKED ISSUE #1797: Scrollbar is displayed under the modal
Related to #1785

1. Connect to a wallet 
2. Open Account modal and scroll down its content
3. Check the right top and bottom corner

**AR**: Scrollbar is displayed under the modal

**ER**: Scrollbar does not exceed the height of a modal

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Fixes #1797

https://user-images.githubusercontent.com/31534717/211568629-ddad8793-26c8-468c-bea0-53b274603e45.mov

https://user-images.githubusercontent.com/31534717/211568475-2813e659-0a05-46e0-a927-17b9e632e3bf.mov

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @fairlighteth , great job!
However:
1. there is no scrollbar on the Review limit order modal now: 
no scroll

2. Content of every modal on Limit orders page is shifted to the right in an Android device: 
image 
image
image
image
image
image

Could you please take a look at these issues?

Thanks!

**Comment by fairlighteth** [comment]
@elena-zh pushed some updates

**Comment by elena-zh** [comment]
Hey @fairlighteth , modal look much-much better!
However, there is a weird thing in Android devices: when Your orders table has 'Open orders' tab active, modal look good on the Limit orders page. But when I switch to 'Orders history', modal become shifted to the right. Could you please take  a look at it?

One more nitpick is that the bottom area of 'Waiting' modals has become expanded:
bottom

And 'truncated' modals have also appeared in this PR  (#1802 issue) :)

**Review by shoom3301 — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh Thanks again for reviewing all this. Pushed some fixes:

Screenshot 2023-01-11 at 17 06 51

https://user-images.githubusercontent.com/31534717/211870971-ab554308-387f-44ba-b7e5-f6d12da50604.mov

https://user-images.githubusercontent.com/31534717/211870977-4f2a2191-e4de-4ebb-b257-0bded9d6202d.mov

I could not reproduce the Android issue you reported. Could you provide me with a screen record?

**Comment by elena-zh** [comment]
Hey @fairlighteth , 'waiting' modal looks good to me. 
As for the Android issue, here is the video (I test it on Huawei P20, Android 12)


https://user-images.githubusercontent.com/70885163/212063753-fbc233bd-d7dd-4053-8443-e79d1fa5b1c5.mp4

**Review by anxolin — APPROVED** [review]
Code-wise looks convincing. You will need to convince Elena :)

**Comment by fairlighteth** [comment]
@elena-zh Tried to replicate this on a similar device, without success. Should we create a separate ticket for this to investigate further?

Screenshot 2023-01-13 at 13 16 33


https://user-images.githubusercontent.com/31534717/212328894-83d8e33e-3544-4ddd-b4e3-65308eec797a.mov


Screenshot 2023-01-13 at 13 24 28

**Review by elena-zh — APPROVED** [review]
Hi @fairlighteth , I have created #1870 issue for this edge case. 
All the rest changes are approved.
Thanks!

**Pull request merged**
