### PR TITLE
feat: add styling for hooksitems in review modal

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Adds styling for hook items in the review modal

Screenshot 2024-10-01 at 12 04 30
Screenshot 2024-10-01 at 12 04 38
Screenshot 2024-10-01 at 12 04 50
Screenshot 2024-10-01 at 12 05 03
Screenshot 2024-10-01 at 12 05 14
Screenshot 2024-10-01 at 12 05 24

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]
Perfect!

**Comment by fairlighteth** [comment]
@shoom3301 Added Hook website + GA tracked link:

Screenshot 2024-10-02 at 12 11 57

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!!
Only one trivial nitpick is that in IOS (real device) 'pre' or 'post' looks a bit truncated in the Account modal: 
image

Also, I have a question: will you address Explorer changes in the current PR on in a separate one? 
image

@shoom3301 , these issues I'm addressing to you: 
1. When I open the app in another browser, I can see that some hooks were used for a trade in the Account modal. But all of them are recognized as 'Unknown' hooks. Might this be fixed somehow?
hooks placed in another PR
2. When I add a custom hook (e.g. omnibridge), it is recognized as 'Unknown hook':
custom hook (omnibridge)
3. (discussed in the meeting today): it would be great to show hooks closer to the fields, and warnings closer to the button: 
between warnings

Thanks!

**Comment by shoom3301** [comment]
>(discussed in the meeting today): it would be great to show hooks closer to the fields, and warnings closer to the button:

@fairlighteth @elena-zh fixed that (in this PR)

**Comment by elena-zh** [comment]
Hey @shoom3301 , thank you for addressing cases 2-3. 
As for the case 1: I have run a custom hook from the current branch, then placed an order using this hook in Chrome. 
Then I opened the app in Firefox, connected the same wallet in the same chain: Account modal shows 'Unknown hook' there
image
image

**Comment by elena-zh** [comment]
I've caught an accidental crash on this PR when I navigated to the Hooks page being connected to a wallet on GC:
image

My local storage is 
[3 (1).txt](https://github.com/user-attachments/files/17231596/3.1.txt)

**Comment by shoom3301** [comment]
@elena-zh thanks!
Fixed both

**Comment by elena-zh** [comment]
Hey @shoom3301 , great, thank you!
One more issue I've faced: explorer shows 0 (or 00) in the Hooks field when no hooks added. 
Reproducible for all orders (swaps/limit/twaps):
1. No post-hook: 
image

2. No hooks at all:

**Comment by shoom3301** [comment]
>When only pre-hook is added to an order, 'pre' label is truncated in the Account modal

@elena-zh @fairlighteth fixed that

**Review by elena-zh — APPROVED** [review]
Fixes #4940 as well. 
Approved. 
For remaining issues I've opened #4945

**Pull request merged**
