### PR TITLE
Number input arrows

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses https://github.com/cowprotocol/cowswap/issues/2890

https://github.com/cowprotocol/cowswap/assets/31534717/b265afe0-9332-4d3f-a3a2-c23ba4c57e13

## Todo
- Does not have the actual click logic implemented (on click).

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , it would be great to add all these fancy arrows to the Custom duration fields as well: 
arrows

**Review by shoom3301 — APPROVED** [review]

**Comment by alfetopito** [comment]
Mostly done, holding off the PR until the final piece is merged: https://github.com/cowprotocol/cowswap/pull/3003

**Review by alfetopito — APPROVED** [review]
Double approve

**Comment by elena-zh** [comment]
Great job!

**Pull request merged**
