### PR TITLE
🎨 🎅🏼 Winter theme footer image

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Adds the Winter theme footer image (provided by Clement)

Screenshot 2022-12-19 at 13 17 36
Screenshot 2022-12-19 at 13 17 49

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , love these winter cows!
Only one nitpick is that cows are too tiny in a mobile view now: 
image

**Comment by fairlighteth** [comment]
@elena-zh I made some changes to scale up the image on medium + mobile:

Screenshot 2022-12-19 at 16 55 22
Screenshot 2022-12-19 at 16 55 09
Screenshot 2022-12-19 at 16 54 38
Screenshot 2022-12-19 at 16 54 18

**Comment by fairlighteth** [comment]
@elena-zh Also fixed a mobile margin issue on the content pages:

Screenshot 2022-12-19 at 16 48 53

**Review by alfetopito — APPROVED** [review]
❤️

**Review by anxolin — APPROVED** [review]
Looks great!

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!
Just 1 question: won't the FAQ changes be reverted then the winter theme is removed?

**Comment by fairlighteth** [comment]
@elena-zh This should not be a problem due to this addition https://github.com/cowprotocol/cowswap/pull/1770 - which allows use to simply not import the Winter footer. But we need to keep a close eye on this for sure.

**Pull request merged**
