### PR TITLE
feat: update legal pages

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Add new legal pages on /legal/
- /legal/cowswap-terms
- /legal/cowswap-privacy-policy
- /legal/cowswap-cookie-policy
- Removed unused images in the cow-fi images folder

Screenshot 2024-06-25 at 17 55 26

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , 
1. I see discrepancies in the doc names like: 
image
image

2. Then, there are some areas that are highlighted with red on the previous version, and are not highlighted in the current one 
image
Terms:
image
image
image


3. One more useful thing that is missing - table of content. Will it be possible to add it? 
image

4. Forum link is missing on the Terms page 
image

5. Terms are missing 'Welcome' 
image

6. Table when scroll the content on the Cookie policy page: 
image

Thanks!

**Review by alfetopito — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh Thank you for reviewing:

1. Updated titles
2. Highlighted now
3. For now not
4. Link is already above that text. I think this text is simply stating what the url is in the terms.
5. Don't think it's needed
6. Addressed (horizontal scroll for mobile)

**Comment by fairlighteth** [comment]
Also removed unused images in the cow-fi images folder

**Comment by elena-zh** [comment]
Hey @fairlighteth , thanks for addressing this!

As for the forum link, I've reported this issue as currently it is displayed as a link, not like a text 
image

Then, I still see that widget terms and conditions are written differently
image
image

The last question: could you please clarify whether terms/policies pages should be removed from CoW Swap once Legal section goes live?
image

Thanks

**Comment by fairlighteth** [comment]
@elena-zh Good point about the menu items on swap.cow.fi - I now point to the exact page on cow.fi - IMO we should keep those links. Otherwise updated the title on the terms.

**Pull request merged**
