### PR TITLE
Rebrand CowSwap into CoW Swap

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Apply the rebranding from CowSwap into CoW Swap.

It replaces all the titles, labels, and messages from the app into CoW Swap. 

## Warning
This will also change the appCode we use in the meta-information attached to the orders. So the IPFS cid will change.

## Additionally
It deletes the files for the metadata that contained the hashes, and appDatas. They were only documentation, and were not used in the project. They also should change because of this PR, but it doesn't have any value, because we also never use those codes anymore since we are adding now the slippage information which already changed the IPFS document.

# To Test
Make sure the app is not broken and all labels have the right name.

### CODE REVIEW

**Comment by avsavsavs** [comment]
(Angry face) I missed one!! in the second question

**Comment by elena-zh** [comment]
Hey @anxolin , great job!
Some issues from my side: 
1. FAQ-General-What makes CoW Swap a "Meta" DEX aggregator?
image
2. FAQ-Protocol-What are CoW Protocol's Solvers? : shouldn't it be CoW DAO?
image
3. The same question for FAQ-Token:
image
image

4. FAQ-Token-What was the criteria for the token airdrop?: maybe CoW Stars?
image

5. I noticed that we have different spelling for cow-mmutity in FAQ-Affiliate-Who can follow the referral link? and in Discounts modal
image
image

6. FAQ-Affiliate-Who can follow the referral link?: 
image

7. T&C: 5. FEES
image

Thank you!

**Comment by anxolin** [comment]
Nice catch! Fixed!

**Comment by anxolin** [comment]
Confirmed with marketing that the right word now is `CoWmunity`

**Comment by elena-zh** [comment]
Hey @anxolin , great!

I'm approving the PR with some nitpicks: 
1. It would be nice to change a Cow to CoW on the 'Play the CoW Runner Game' button on the Order Submitted pop-up 
cow runner
image
2. Question: it is OK that T&C show August 21 as the last updated date?
last updated 1 y

Thanks!

**Review by elena-zh — APPROVED** [review]

**Comment by anxolin** [comment]
@elena-zh you are incredibly good at finding issues :) 
I did another search, and I think this was the last `Cow` we have in the code the one of the game. Nice catch!

The T&C, we didn't change the content (other than for rebranding), I prefer to not update the date. Legal is reviewing the text, then we will update and change the date with the latest version.

**Comment by elena-zh** [comment]
Thank you, @anxolin !
Now everything LGTM!

**Pull request merged**
