### PR TITLE
Profile: Conditional 'Add Token' vs 'Copy contract address': Waterfall PR[6]

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Conditionally shows the 'Add Token' (to MetaMask) component vs. the 'Copy contract' based on library (MetaMask) detection.

**WalletConnect with a Safe**

https://user-images.githubusercontent.com/31534717/161952595-d812d8ed-aed5-44a5-864e-febb024a3870.mov

**MetaMask**

https://user-images.githubusercontent.com/31534717/161952672-ca29b8b4-22b6-48b3-8dd4-c8a71ec499ce.mov

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , great changes!
Could we need to add a 'copy' action to the vCOW card? WDYT?
image

All the rest changes LGTM!

**Comment by fairlighteth** [comment]
@elena-zh Was thinking about it indeed... you think it makes sense? In that case we add the 'Copy token contract' but not the 'Add To Metamask' ? Because the token is non transferable anyway? I think at the very least we add the 'copy token contract'.

**Comment by elena-zh** [comment]
@fairlighteth , agree with you that there is no need to add 'Add to MM' button to the vCOW card. It is enough to have 'Copy' there with no regard to a type of connected wallet.

**Comment by fairlighteth** [comment]
Build complete after merging in waterfall PR [7]. Tested and works. Continuing merging.

**Review by anxolin — COMMENTED** [review]
approve

**Review by W3stside — COMMENTED** [review]
good

**Pull request merged**
