### PR TITLE
Fix formula

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Attempt to fix the issue with the formula. 

The formula only works if we use it in the units that is expected. So it's very important to know if we have the prices in sell tokens or buy tokens.

`FEP = (A * LP) / (A - F)`   ---> If prices are in buy tokens
`FEP = (A - F) * LP / A`    ---> If prices are in sell tokens

Because how we construct the price here, it is expressed in BUY TOKENS
https://github.com/cowprotocol/cowswap/blob/use-buy-token-formula/src/custom/state/orders/utils.ts#L282

For this reason, 
* The formula are `FEP = (A * LP) / (A - F)` 
* ...and we use `MAX` (not `MIN`) for the Est. Execution Price 
* `EEP = MAX(FEP, FBOP)`

Tested a few cases with tokens with different decimals. I tested also to use for some USDC as the sell token, and DAI as the sell token for other ones.

Screenshot at Mar 27 18-22-39

## Not included
I see some minor issue that should be reviewed independently

If you set a super-low price (as we are willing to receive virtually 0 like in the picture), we will select the Fill Price as the likely execution price.
Screenshot at Mar 27 18-31-14

For some reason, it shows the message that the price needs to go down 0.04% in order to execute. In reality, this is not TRUE! We should show either exactly the same price as the "Market Price" or a number below it. So it should show the message "It will execute soon".

### CODE REVIEW

**Comment by alfetopito** [comment]
Elena, please post merge review, I'll consolidate everything in the parent PR

**Comment by elena-zh** [comment]
Leandro. reviewing this rn!

**Comment by elena-zh** [comment]
Hey @anxolin , @alfetopito , works great! And now I can easily to understand what is the status of my order. 
Thank you!

**Comment by anxolin** [comment]
Glad to hear

**Pull request merged**
