### PR TITLE
[1.24] Fix trade state update for not-connected wallet state

### LINKED ISSUE #1382: [1.24] Swap form is not filled in with tokens when open a shared link with tokens
Related to #1317

1. Open a browser tab in incognito mode
2. Paste the link https://swap-dev-git-release-124-cowswap.vercel.app/#/100/swap/WETH/COW

**AR**: Tokens are not displayed in the fields, **Select a token dropdown is disabled**

**ER**: tokens should be auto-populated into Swap form

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1382

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
However I have found an issue: network and token info in the swap form is not updated when I paste a copied link to the tab with already opened app both for connected and not connected users. It works good when I open the link in a new tab. Could you please fix it? 

Also there is a different behavior when I open the link in a new tab for a connected user: the app sends a request to change a network in MM (works fine), but then tokens info is reset on the Swap form. Is this OK? 

Thanks!


. It works only for the new tab
 - connected user: network and token info in the swap form is not updated when I paste a copied link to the tab with already opened app, + tokens info is reset when I open the link in the new tab

**Review by elena-zh — CHANGES_REQUESTED** [review]
see the notes above

**Comment by shoom3301** [comment]
>the app sends a request to change a network in MM (works fine), but then tokens info is reset on the Swap form. Is this OK?
@elena-zh Yes, this is ok, because we reset the Swap form on network changes

**Review by nenadV91 — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @shoom3301 , might there be any issues with the build? 
I still can see these issues: 
1. Paste the link with another network indicator when a user is connected to the already opened tab: no request to change a network is sent to MM
2. When I change a network indicator to an unsupported one (4): the app does not show an error pop-up, no network switcher, and it does not appear when I change a network indicator to a supported network again (1, 5, 100)

change to correct
not supported banner
3. Issue with not saving network on disconnect is still here (#1386 ):
disconnect

**Comment by shoom3301** [comment]
2 - @elena-zh in this case I just change network indicator in the URL back. For example:
 - open /1/swap/ETH
 - navigate to /137/swap/ETH
 - expected result: navigate to /1/swap/ETH (back)

**Comment by elena-zh** [comment]
Hey @shoom3301 , great changes!
#1382 and #1386 issues are fixed. 
As for #1369, there are several side issues: 
1. Case 2 https://github.com/cowprotocol/cowswap/pull/1384#issuecomment-1313879047 is not working as you describe when you change a network for 4 (former Rinkeby). For other cases it works good
not changed to 100

2. When I change a network using a network selector and an indicator, and I'm not connected, tokens are not removed from the URL, user is not connected
not removed
3. The same issue with tokens in the link when I connect a wallet using WC, and it does not support other chains but Ethereum: 
return back
4. When I change a network indicator in the URL (to 4, 5, 100) being connected to a wallet that does not support a network switch (supports only 1), it would be great to return the indicator to 1 

Thanks!

**Review by elena-zh — APPROVED** [review]
Hey @shoom3301 , thank you!
I have created a separate issue #1391 for cases 3-4, and added a [comment ](https://github.com/cowprotocol/cowswap/issues/1324#issuecomment-1315190507) to the case 1 to the existing issue to address all these cases later. 
So now I'm approving the current PR.

**Pull request merged**
