### PR TITLE
Hide 'discount' section when fees is null

### LINKED ISSUE #912: Hide 'discount' section when there are no fees for a trade
Currently, Fees section is displayed when a trade is free of fees

It would be great to hide this section when there are no fees for a trade

### PR DESCRIPTION
**Pull request by adiaholic**
# Summary

Fixes #912

Screenshot 2023-02-14 at 12 57 12 PM

### CODE REVIEW

**Comment by adiaholic** [comment]
recheck

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @adiaholic , thank you so much for your contribution to the project!
I have retested your changes and have some issues to report: 
1. #912 issue was about removing the 'Fee discount' field **entirely** only for the case when fees=0
image
In the PR I see that the field is displayed, and it still shows 5% discount, however, 5% from 0 = 0 , so there is no need to show this field
image


2. There is no need to remove the fee discount value/button when:
 -  token pair is not selected
 -  token pair is selected, no amount to trade
image
image
This is due to the button gives a user info about discounts levels based on the vCOW/COW token balance. 

Could you please take a look and fix these issues?

Thank you!

**Comment by adiaholic** [comment]
Hi @elena-zh, thanks for the great explanation. 

I have incorporated the feedback. Please let me know if you expect any more changes.

**Comment by elena-zh** [comment]
Hey @cowprotocol/frontend , could you please help me to get the latest preview link with new commits there?

**Comment by adiaholic** [comment]
Hi @shoom3301, I have pulled the latest changes from the develop branch

**Comment by alfetopito** [comment]
I have approved the re-deployment on Vercel
@elena-zh you should be able to test it again once it completes

**Comment by elena-zh** [comment]
Hey @alfetopito , seems like the build has failed again :(

**Comment by adiaholic** [comment]
I've tried running the cypress tests on the parent branch, [cowprotocol:develop](https://github.com/cowprotocol/cowswap) locally and it fails there as well.

Do you think it is something I need to check in this PR ?

**Comment by alfetopito** [comment]
> Hey @alfetopito , seems like the build has failed again :(

The Vercel build succeeded: https://github.com/cowprotocol/cowswap/pull/2000#issuecomment-1430990333

https://swap-dev-git-fork-adiaholic-fix-912-cowswap.vercel.app/

And that's what matters.

> Do you think it is something I need to check in this PR ?

The other build steps (test, lint and cypress) won't because they depend on repo secrets, which are not available on forks.

Nothing you can do @adiaholic, we can check the behaviour using the deployment link above

**Comment by alfetopito** [comment]
> > The Vercel build succeeded: [#2000 (comment)](https://github.com/cowprotocol/cowswap/pull/2000#issuecomment-1430990333)
> > https://swap-dev-git-fork-adiaholic-fix-912-cowswap.vercel.app/
> 
> I have retested the changes in this link, and still see issues I reported above: image

Hmmm, checking what's deployed, it's the first commit https://github.com/cowprotocol/cowswap/commit/96c1084482616261a13f48244fa1a1076ab3b34f
image

I'll see if I can get the latest code deployed

**Comment by alfetopito** [comment]
Aha! Now I found out how to trigger the right build

image

@elena-zh now it has the latest

image

**Comment by elena-zh** [comment]
Hey @adiaholic , great job!
Some issues: 
1. It would be great to remove [-5%] label from Receive/From tooltips both on the form and order confirm modals
image

2. uber-nitpick: can we remove discount section while order details are being loaded? (actually, not sure if we can do this)
See the video: https://loom.com/share/0bb99c70603a4c9cb5151eae96bcc788

Thanks!

**Comment by adiaholic** [comment]
Hi @elena-zh, 

Thanks for going through my PR again.

I am yet to work on the latest review. I'll be working on them later this week after I'm done with my mid term exams.

I'll approach you once I push a fix for that.


Thanks !

**Comment by elena-zh** [comment]
Hey @adiaholic , any updates on this?
Otherwise I'd like to close the PR.

Thanks

**Pull request closed without merging**
