### PR TITLE
feat(hooks-store): import external hook-dapps

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Importing external hook-dapps via Iframe.

## Demo

https://github.com/user-attachments/assets/52332206-3bc9-4e11-9937-e076f64e7d2b

# To Test

1. Run `yarn start`
2. Run `yarn start:omnibridge-hook` in another terminal tab
3. Go to "Add Post-hook Action" -> "External Hooks" tab -> "Add external hook" -> Insert "http://localhost:4317/hook-dapp-omnibridge" -> "Add" -> "I understand"-> "Add external hook"
4. When you delete an external hook-dapp, then all applied hooks of this dapp should also be removed

### Hook-dapp manifest validation (possible errors)
1. `'name', 'image', 'version', 'website'` fields are no set - when one or more of mandatory fields are not set
2. The app does not support smart-contract wallets. - when manifest contains `conditions.smartContractWalletSupported=false` and current wallet is smart-contract
3. The app is might be used only as a post-hook. - when manifest contains `conditions.position=pre` and you try adding this hook-dapp as a post hook and vice versa. When `conditions.position` is not set it means both positions are supported
4. Manifest does not contain "cow_hook_dapp" property. - when manifest json structure is not valid
5. Can not fetch the manifest.json - when we couldn't fetch the mainfest.json file

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
Some issues I faced: 
1. When I add an external hook as a not connected user, the app is crashed. It continues crashing when I connect a wallet and then try adding this hook. The only workaround is to clear out the local storage and try again with a connected wallet. 
disconnect-reconnect
2. When I add an external hook, then navigate to the Swap page, the receiver is displayed there. IMO, it would be great to remove it from the Swap form. 
swap
3. (maybe for @fairlighteth ): it would be great to truncate preceding and trailing spaces when adding a hook URL
image


Just FYI: 
1. I do not report issues related to the hook itself like empty fields ("") in manifest, or changing recipient field on the form assuming that a user is responsible to all these technical details
2. I did not test UI issues here as they should be addressed in #4912.

**Comment by elena-zh** [comment]
Hey @shoom3301 , case 3 LGTM. thank you for addressing this!
As for the case 2, I cannot check it as the app gets crashed when I enter a hook's URL (no matter if I'm connected or not): https://www.loom.com/share/b55bd2ae63e2433080de36159447af3f

**Comment by shoom3301** [comment]
@elena-zh I can't reproduce that, is it still relevant?

**Comment by elena-zh** [comment]
> @elena-zh I can't reproduce that, is it still relevant?

Yes it is.

**Comment by shoom3301** [comment]
> > @elena-zh I can't reproduce that, is it still relevant?
> 
> Yes it is. I've updated the branch with the latest changes, and now it is crashes on a hook add action image
> 
> https://www.loom.com/share/4b475a0a63194fcb9d79a68a5019657d

Fixed in https://github.com/cowprotocol/cowswap/pull/4912

**Review by elena-zh — APPROVED** [review]
Tested in #4912: approved.

**Pull request merged**
