### PR TITLE
Add back to top button to content pages

### LINKED ISSUE #1879: [1.29] Add 'Back to top' button to Terms and Policies pages
Add 'Back to top' button to pages:
 - Terms and conditions
 - Privacy Policy
 - Cookie Policy

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1879

This PR adds "Back to top" button at the end of following pages
- Terms and conditions
- Privacy Policy
- Cookie Policy

# To test
- go to pages mentioned above
- scroll at the bottom
- test the button

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @nenadV91 , great job!
The only one note that the button looks different in comparison with the FAQ section in the dark mode. 
Could you update the button's style to match the one on the FAQ page?
button dark mode

Thanks!

**Comment by nenadV91** [comment]
@elena-zh Should be fixed now

**Review by elena-zh — APPROVED** [review]
LGTM!

**Comment by nenadV91** [comment]
Lets do a post code review.

**Pull request merged**
