### PR TITLE
fix: don't reset network cache in JsonRpcProvider

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

`useBlockNumber()` subscribes on block and fetch them on every block, besides of that it also fetches `eth_chainId` what is excessive. To avoid that I patched `json-rpc-provider.js` to prevent network cache resetting. For some reason in the lib they cache it only for the current event loop.

Before:
image

After:
image

  # To Test

1. Open dapp
2. Open dev tools with network tab
- [ ] AR: there are batches by two requests with `useBlockNumber` initiator
- [ ] ER: there are single requests with `useBlockNumber` initiator
3. Network switching should work (with not connected wallet)
4. Network switching should work (with connected wallet)

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
I don't understand the original code very well.
Normally, the setTimeout 0 you use it to plan some execution when the main thread is free, so you let all the UI to re-paint, etc.

I don't get why this is done in this case... 

Anyways, I tried and I see we still check the chainId on every block now. 
I think Tukan also researched on this problem and had a open PR, maybe you can check what he did too

image

**Comment by shoom3301** [comment]
>I don't understand the original code very well.
>Normally, the setTimeout 0 you use it to plan some execution when the main thread is free, so you let all the UI to re-paint, etc.

Afaiu they intended it as a cache for the current tick, but I also don't fully understand

**Comment by shoom3301** [comment]
>Anyways, I tried and I see we still check the chainId on every block now.

@anxolin fixed, now it should request chainId only 1-2 times at the beginning

**Comment by shoom3301** [comment]
>I think Tukan also researched on this problem and had a open PR, maybe you can check what he did too

Yeah, I remember [his solution](https://github.com/cowprotocol/cowswap/pull/2271), it's more advanced and covers more problems than the current PR

**Comment by shoom3301** [comment]
https://github.com/ethers-io/ethers.js/blob/main/src.ts/providers/provider-jsonrpc.ts#L644

@anxolin I also see they got rid of this `setTimeout()` in the next version

**Comment by anxolin** [comment]
Alright, so you want to merge this, or you want to update to the next version?

**Pull request merged**
