### PR TITLE
Release/1.31.0

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

- Zenhub kanban automation
- Wallets refactor
- Fix circular deps for cosmos
- Add Zengo, Ambire and Alpha wallets
- Limit orders reiteration
- Other fixes

## Details
```
git log --oneline v1.30.1..release/1.31.0
```
2b4a7e5fa (HEAD -> release/1.31.0, origin/release/1.31.0) Wallet/remove view more button (#2157)
a86163dc1 Bump the version to 1.31.0 in package.json
5650ac823 Wallet/alpha enabled (#2148)
0c03c193c (origin/hackaton-soll, hackaton-soll, develop) Merge branch 'release/1.31.0' into develop
f16bfb9f6 Merge branch 'hotfix/1.30.2' into release/1.31.0
44e6305b3 Merge branch 'hotfix/1.30.2' into develop
69ec1d249 Simplify Gnosis Safe state (#2107)
3506efdd4 (origin/hotfix/1.30.2) Add 1inch price estimation (#2131)
e21be343f Add view more wallets button (#2100)
86183f315 Add Alpha wallet option (#2099)
7b5c8f12f Fix detection of Gnosis transactions (#2120)
02aac3f58 UnsupportedToken state for the swap form (#2119)
d06b28502 Remove Coinbase wallet from BACKFILLABLE_WALLETS
93fd76372 Invert tokens when user selected the same token (#2123)
e0874c4a7 Move back AsyncConnector (#2121)
6f817236c Fix CurrencyInputPanel value changes (#2115)
86f8a5bbd Fix focusing of search input in walletconnect modal (#2118)
0c4c82bc5 Add wallet state (#2101)
1b60a3c06 Add Ambire wallet option (#2096)
f8e8f4f80 Simplify dependencies with web3-react (#2098)
5b313aa29 Limit orders reiteration (with hidden est. execution price) (#2093)
41de39899 Add zengo (#2092)
f67cdbe14 Merge branch 'main' into develop
db0d9d9c8 [wallet-refactor-5] Dumbify components, and move web3-react dependant to its directory (#2073)
a64f0b90a Revert "Add zengo wallet option (#2044)"
1c93532b4 Add zengo wallet option (#2044)
6595b5fa1 Fix circular deps for Cosmos (#2076)
43426c717 [wallet-refactor-5] Remove Mod and unify WalletModal (#2061)
072ac9ad3 [wallet-refactor-4] Disconnect hook (#2060)
608c36c64 [wallet-refactor-3] Move AccountDetails to new module #2058 (#2059)
95e87764e [wallet-refactor-2] Move AccountDetails to new module (#2058)
a267da3c3 Wallets/initial refactor (#2056)
38f757a75 Merge branch 'main' into develop
241c9d7b8 Check is network supported in Currency List component (#1996)
6f7f09a19 Fix Zenhub kanban automation triggers conditions
848c29e11 Fix Zenhub kanban automation triggers
d78517d4a Remove Zenhub kanban automation js script
b31924a16 Refactor Zenhub kanban automation to curl
209560486 Fix Zenhub kanban automation install node-fetch
e309e0ef7 Fix Zenhub kanban automation install node-fetch
dc5d04541 Fix Zenhub kanban automation clone repo
9280b120e Fix Zenhub kanban automation issuesIds
46c2cc5a1 Fix Zenhub kanban automation issuesIds
c0be81240 Fix Zenhub kanban automation
4d8186998 Zenhub kanban automation (#2001)

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
The PR looks good to me. 
However, there are several issues that would be great to address: 
 - #2161  : link is not updated to the latest one
 - #2159: impossible to sign transactions with  ZenGo wallet. Maybe we need to hide this option for now? 

Thanks!

**Comment by tukantje** [comment]
Added cherry picked commit of a29fa597a5842e9cc0b73b2a482902a5ece4e491 (merge commit of https://github.com/cowprotocol/cowswap/pull/2149)

**Review by elena-zh — APPROVED** [review]
ZenGo issue is not on our side. 
Dune link is fixed.

**Review by anxolin — APPROVED** [review]
Looks good to me, althought before relasing, I think it would be nice to do a test in barn for the 1inch/legacy price. This can be done with the config branch once merged into staging

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
