### PR TITLE
fix: fix e2e

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Restores a change that was lost in this PR https://github.com/cowprotocol/cowswap/pull/2707/files#r1238279108

The change was making amplitude env optional. If it is not present, the app breaks

## context

- https://cowservices.slack.com/archives/C0361CDG8GP/p1687870587361509
- 

# To Test

Check cypress e2e result

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
This is not it. Cypress is still failing:

https://github.com/cowprotocol/cowswap/actions/runs/5393809945/jobs/9794073525?pr=2733

Same issue with the missing types is still present 
image

If this is for cosmos, though, it's only visible after merging to dev:

image

So, I'll merge to check whether this fixes the problem

**Comment by alfetopito** [comment]
Merging to test, if it doesn't work I'll revert it

**Comment by alfetopito** [comment]
Did not work: https://github.com/cowprotocol/cowswap/actions/runs/5398639123/jobs/9804805476

The issue is the same as with cypress, types are not available:

image

**Comment by alfetopito** [comment]
Change reverted 29280fe3ff685a0d00e340ec88fa6d1bcb31ea6e

**Comment by anxolin** [comment]
> The issue is the same as with cypress, types are not available:

I think is unrelated, my hunch is that it has to do with caching the types

**Pull request merged**
