### PR TITLE
[3] feat: library iframe-transport to communicate between app and iframe

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

We already have some functions and classes which are resposible for communication between iframe and app. But those entities are bound to widget domain.
To reuse this code I create a new library `@cowprotocol/iframe-transport` which includes:
- `IframeRpcProviderBridge` class which main goal is forwarding messages and events from eip-1193 provider into iframe
- `WidgetEthereumProvider` class serves inside of iframe and receives what `IframeRpcProviderBridge` sent
- `IframeTransport` class is responsible for listening and sending post-messages between windows. The main feature of this class is typings of messages and payloads. This class was transformed from [function from widget-lib](https://github.com/cowprotocol/cowswap/blob/d80267927d7362981514dca52c55d329d8d3bda3/libs/widget-lib/src/messages.ts#L13).
- `iframeRpcProviderTransport` an instance of `IframeTransport` for any `eip-1193` messages

# To Test

No need to test

### CODE REVIEW

**Comment by alfetopito** [comment]
All builds are failing. Is this expected for this PR?

**Comment by shoom3301** [comment]
@alfetopito yes, this is expected. Everything should work at the last PR in the sequence: https://github.com/cowprotocol/cowswap/pull/4890

**Review by alfetopito — COMMENTED** [review]
Code looks ok, but build is broken

**Review by alfetopito — APPROVED** [review]
Ah ok, keep on then

**Pull request merged**
