### PR TITLE
feat(progress-bar-v2): load solvers info from cms

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Load solvers info from CMS

image (2)

- Solver display name
- Solver image
- Total number of solvers
- Fixed solver ranking sorting (it was inverted)

# To Test

1. Place order
2. Wait for order to execute
* Total number of solvers should match the chain (mainnet: 24, gchain: 11, arb1: 13, sepolia: 3)
* Depending on the solver, there might be custom images

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @alfetopito , I got different number of solvers on each network: 
sepolia 5, arb - 12, GC - 10. On Ethereum I don't see solvers number at all (I placed 2 orders: [1st](https://dev.explorer.cow.fi/orders/0x7b1e8e6fc3d2cb9bfb1c518e3d4544b8c56fed50167b6f9654cc7c9dee27786b9fa3c00a92ec5f96b1ad2527ab41b3932efeda5866be2a93?tab=overview), [2nd](https://dev.explorer.cow.fi/orders/0xd9a9f948d184df506207ecc9558cef2b719b17ccb711a0a3d579c325587b85e79fa3c00a92ec5f96b1ad2527ab41b3932efeda5866be2af4?tab=overview))

arb 12
no solvers on maiinet
sepolia 3
Could you please check it?

**Comment by alfetopito** [comment]
> Hey @alfetopito , I got different number of solvers on each network: sepolia 5, arb - 12, GC - 10. On Ethereum I don't see solvers number at all (I placed 2 orders: [1st](https://dev.explorer.cow.fi/orders/0x7b1e8e6fc3d2cb9bfb1c518e3d4544b8c56fed50167b6f9654cc7c9dee27786b9fa3c00a92ec5f96b1ad2527ab41b3932efeda5866be2a93?tab=overview), [2nd](https://dev.explorer.cow.fi/orders/0xd9a9f948d184df506207ecc9558cef2b719b17ccb711a0a3d579c325587b85e79fa3c00a92ec5f96b1ad2527ab41b3932efeda5866be2af4?tab=overview))  arb 12 no solvers on maiinet sepolia 3 Could you please check it?

Thanks, the query was not returning all solvers from cms. Fixed now 🤞

**Comment by elena-zh** [comment]
Hey @alfetopito , great, thank you!
But still I see 5 solvers in Sepolia and 25 solvers on Ethereum. Could you please check it?

**Comment by alfetopito** [comment]
Merging to parent to consolidate. Post merge review etc.

**Comment by elena-zh** [comment]
Number of solvers looks good now. 
The only one issue is left: missing number of solvers for filled orders: 
image

**Pull request merged**
