### PR TITLE
Hotfix/1.26.1

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

WIP: Small hotfixes for the release

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

**Comment by anxolin** [comment]
APPROVED (i cannot approve officially my own PR)

**Comment by elena-zh** [comment]
Hey @nenadV91 , the issue #1684 is still reproducible in the PR. 
image

It was fixed in #1687, but not merged (@shoom3301 closed it). 
I think, it would be great to reopen that PR and merge it to the current Hotfix.

**Review by elena-zh — COMMENTED** [review]
Besides the issue above, it would be great to add #1711 PR as well here.
All the rest changes LGTM!

**Comment by shoom3301** [comment]
@elena-zh thanks! FIxed: https://github.com/cowprotocol/cowswap/pull/1715

**Review by elena-zh — APPROVED** [review]
LGTM!

**Pull request merged**
