### PR TITLE
fix(twap): deduplicate safe transactions with the same order

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Context: https://cowservices.slack.com/archives/C036MD8ADMG/p1702647376040919

The case:
1. Propose and execute a transaction with TWAP order creation
2. Propose another transaction with the same call data
3. Cancel/replace the proposed transaction

AR: the order from the first tx is NOT displayed in the orders table
ER: the order from the first tx is displayed in the orders table

  # To Test

See the case above

### CODE REVIEW

**Comment by alfetopito** [comment]
I can now see the orders from the active TWAP \o/

image

But I don't see the other TWAP order :/

**Comment by shoom3301** [comment]
>But I don't see the other TWAP order :/

@alfetopito there is actually only one order in [the Safe from the example](https://app.safe.global/transactions/history?safe=gno:0x42cEDde51198D1773590311E2A340DC06B24cB37), so, it's expected

**Comment by alfetopito** [comment]
> > But I don't see the other TWAP order :/
> 
> @alfetopito there is actually only one order in [the Safe from the example](https://app.safe.global/transactions/history?safe=gno:0x42cEDde51198D1773590311E2A340DC06B24cB37), so, it's expected

No, there are more TWAPs for this Safe.
Check the order history for this address on Explorer https://dev.explorer.cow.fi/gc/address/0x42cedde51198d1773590311e2a340dc06b24cb37

[This one](https://dev.explorer.cow.fi/gc/orders/0xbe15231f1363bc021fbd25112605c2f4e0d51503bc52da91dce51d17a700804242cedde51198d1773590311e2a340dc06b24cb3764f8a10f?tab=overview) was part of a TWAP placed on September, but I don't see it anywhere in the CoW Swap UI. Created [in this Safe tx](https://app.safe.global/transactions/tx?safe=gno:0x42cEDde51198D1773590311E2A340DC06B24cB37&id=multisig_0x42cEDde51198D1773590311E2A340DC06B24cB37_0x637f73197501cb044161f7f3952506a195c83dfa6c47695df3375a8423136505) if I'm not mistaken.

Is it because of the id collision you mentioned?

**Comment by shoom3301** [comment]
@alfetopito ahhh, I see.
It's because they are too old :) 
There is `SAFE_TX_HISTORY_DEPTH` const that defines how deep we go in the transactions history.
So anyway, this is expected

**Review by alfetopito — APPROVED** [review]
Turns out the fix is simpler than expected 👍

**Comment by alfetopito** [comment]
Don't forget to point this to https://github.com/cowprotocol/cowswap/pull/3501 before merging

**Comment by shoom3301** [comment]
https://github.com/cowprotocol/cowswap/pull/3521
Reopened the PR because target branch was changed to release

**Pull request closed without merging**
