### PR TITLE
Fix issues

### LINKED ISSUE #1825: [1.29] Cookie policy issues (PR#1793)
Reported in https://github.com/cowprotocol/cowswap/pull/1793#pullrequestreview-1228952741
1. Fixed in #1821
2. ~~We should use the same format for all 'Last updated' sentences across all content pages~~
@alfetopito [suggestion](https://github.com/cowprotocol/cowswap/pull/1791#issuecomment-1365259375):
```
I would make sure all of them (T&C, Cookie and Privacy policy) follow the same pattern.

For example. 
- This: `(Last Updated: November 2022)`
- Cookie policy: `(updated: November 2022)`
- T&C: `Last updated: November 2022`
```

3. I don't think we need an additional background area for paragraphs. I think, we need to use the same format for all content pages (no additional bg): 
no need in bg
4. Do we really need to highlight it in red? It is not highlighted in the doc:
not in red

5. For me, it is difficult to scroll the table: long press selects and highlights the text, but does not scroll the table content. Can we add a scroll effect on the long press action? 
image
6. It would be great to enhance the scroll bar itself in Win11
image
7. The table in a mobile view does not look good: 
image
8. Some links exceed the screen width in a mobile view:
image

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1825

3. Fixed
4. Fixed
5. Not sure I understand this one
6. Maybe this is fixed now
7. Should be better now
8. Should be fixed

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @nenadV91 , great! Some notes:
1. Case 6 is not fixed (scroll at the bottom of the table)
2. Besides, I would enhance the table itself: add boarders or so. Something like we have on the Terms page. However, I can report another task for the table enhancement
table
3. I would replace period, comma and missing punctuation with a semicolon here (like everywhere else in this policy listings)
period-comma-nothing
4. I still don't like that links are wrapped in the text :(
link terms
links
pages

**Comment by nenadV91** [comment]
@elena-zh 

1. Maybe we can skip this for now
2. Fixed
3. Fixed
4. Changed this to only break word on mobile only

**Review by elena-zh — APPROVED** [review]
Hey @nenadV91 , I have created: 
#1886 issue for the table scrollbar
#1888 issue for the links wrap in a mobile view. 

All the rest changes LGTM!

**Comment by nenadV91** [comment]
Merging this for the release and we can do post code review

**Pull request merged**
