### PR TITLE
chore(release): release/1.47.0

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Release 1.47.0

# Big changes

- Refactor of usd estimations (https://github.com/cowprotocol/cowswap/pull/3081)

# Small changes

- Only update pending orders for current account (#3078)

## Bug fixes

- Check allowance before pending tx for approval state (https://github.com/cowprotocol/cowswap/pull/3090)
- Add a space between "Added COW" (#3094)
- Clean form amounts after wrap/unwrap (#3095)
- Update token logo cache after tokens list loading (#3100)

## Technical debt
- Fix build warnings (#3093)
- Add bundle analyzed (#3096)
- Set order-book API urls from env file if present (#3086)
- Manual chunk management (#3098)

# Test plan

## ✨ NEW FEATURE ✨ 

- [x] Load sell and buy token USD values (SWAP/LIMIT/TWAP) * (Mainnet/Gchain/Goerli)
- [x] Load price impact (SWAP/LIMIT/TWAP) * (Mainnet/Gchain/Goerli)

## Regular flow testing

Smart contract wallet (Safe):
- [x] Just swap
- [x] Approve + swap
- [x] Wrap + approve + swap (eth-flow)
- [x] Wrap/unwrap
- [x] EthFlow swap
- [x] EthFlow cancellation
- [x] Order placement and fill (Limit/Twap)
- [x] Hard cancel order (Swap/Limit/Twap)

EOA wallet (Metamask):
- [ ] Just swap
- [x] Approve + swap
- [x] Wrap + approve + swap (eth-flow)
- [x] Wrap/unwrap
- [x] EthFlow swap
- [x] EthFlow cancellation
- [x] Order placement and fill (Limit/Twap)
- [x] Hard cancel order (Swap/Limit/Twap)
- [x] Soft cancel order (Swap/Limit/Twap)

WalletConnect v1:

- [x] Wrap/unwrap on SWAP
- [x] Wrap/unwrap on LIMIT
- [ ] Wrap/unwrap on TWAP
- [x] Just swap
- [x] Approve + swap
- [x] Wrap + approve + swap (eth-flow)
- [x] EthFlow cancellation
- [x] Order placement and fill (LIMIT)
- [x] Hard cancel order (SWAP/LIMIT)
- [x] Soft cancel order (SWAP/LIMIT)

WalletConnect v2:

- [x] Wrap/unwrap on SWAP
- [x] Wrap/unwrap on LIMIT
- [x] Wrap/unwrap on TWAP
- [x] Just swap
- [x] Approve + swap
- [x] Wrap + approve + swap (eth-flow)
- [x] EthFlow cancellation
- [x] Order placement and fill (LIMIT)
- [x] Hard cancel order (SWAP/LIMIT)
- [x] Soft cancel order (SWAP/LIMIT)

Account page:
- [x] add token to Metamask
- [x] approve token
- [x] COW balance displaying
- [x] token search by name/address
- [ ] add token to Metamask
- [x] favorite token add/remove

Common (WalletConnect/Metamask):
- [x] network switching
- [x] network persisting between modules
- [x] wallet disconnect
- [x] change wallet
- [x] balances loading
- [ ] appzi
- [x] all FAQ pages open

### CODE REVIEW

**Comment by anxolin** [comment]
I can do "WalletConnect v2" tests

**Comment by alfetopito** [comment]
I'll start with `new feature` tests.
Would be good to someone test it too for sanity.

**Comment by alfetopito** [comment]
I'll start now `Smart contract wallet (Safe)` on gnosis chain

**Comment by alfetopito** [comment]
I found a few issues with Safe app on Gnosis chain https://github.com/cowprotocol/cowswap/issues/3105

Moving on to `EOA wallet (Metamask)`

**Comment by alfetopito** [comment]
Done with `EOA wallet (Metamask)`

Nothing new to report.

Will start with `Account page`

**Comment by alfetopito** [comment]
Done with `Account page`

Found one app crashing issue. Reported on Major section https://github.com/cowprotocol/cowswap/issues/3105

**Comment by alfetopito** [comment]
Will now test `Common (WalletConnect/Metamask)`

**Pull request merged**
