### PR TITLE
Release 2024-05-28

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

- feat: add devcontainer (#4434) 
- feat: add support for ERC-3770 on recipient addr (#4418) 
- feat: improve message for wrong prefix on networks (#4468) 
- feat: don't pollute the history with widget changes (#4470)
- fix: fix safe read-only button tooltip (#4475)
- feat(arbitrum): add arbitrum_one (#4407) 
- ci: fix react-hooks eslint rules (#4484)
- fix(wallets): update provider when eip6963 wallet changed (#4483)
- fix(limit-orders): don't update trade context after review modal open (4476)
- fix(limit-orders): adjust almost fully filled orders displaying (#4477)
- fix: navigate with widget awareness (#4471) 
- fix(explorer): adjust almost fully filled orders displaying (#4482) 
- feat: add arbitrum uni token list (#4488) 
- fix(usd-estimation): no usd estimations for native (#4352) 
- chore: use mapped tokenlists for arb1 (#4492)

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
Reviewed to code, all good.
Will start the testing flow now.

**Comment by alfetopito** [comment]
Tested the regular flow with:

- Safe App on Gnosis Chain
- Save via WC on Arbitrum one

Issues so far:

- SWAP Order shown as cancelled before trading
- It's possible to wrap/unwrap more than balance on LIMIT
- Not possible to scroll page while notification is open
- No low allowance warning for TWAP part (was it always fill or kill?)
- Need to update threshold for minimum gas in wallet for arbitrum 
	1. Connect with safe via WC
	2. ETH as sell, anything else as buy
	3. Click on swith to WETH

|Step 1|Step 2|
|-|-|
| image | image |

**Comment by alfetopito** [comment]
Every time I switch networks when connected with MM, the app disconnects.

1. Connect with MM
2. Pick a different network in the network selector
3. The app is disconnected

https://github.com/cowprotocol/cowswap/assets/43217/3ae7dab4-9c6c-4254-95d8-aa5fe56f977b

**Comment by alfetopito** [comment]
Done with EOA injected.
No new issues found.

**Comment by anxolin** [comment]
This link was broken:
image

Takes you to https://dev.explorer.cow.fi/arb1/address/0x79063d9173C09887d536924E2F6eADbaBAc099f5 . Selects mainnet
image

Looks like is talking me to my account not the TZ

Also the notification tooke me to a 404, I believe cause the explorer path is `ABR` and the link is `ARB`

https://dev.explorer.cow.fi/arb1/orders/0x48750ca3b8d870336027a1283253b71316319dd0f9c8b4844d5b80a01abbc4cb6dfe75b5ddce1ade279d4fa6bd6aef3cbb6f49dbffffffff

https://dev.explorer.cow.fi/abr1/orders/0x48750ca3b8d870336027a1283253b71316319dd0f9c8b4844d5b80a01abbc4cb6dfe75b5ddce1ade279d4fa6bd6aef3cbb6f49dbffffffff?tab=overview

**Comment by anxolin** [comment]
WETH is asking me for a regular permit

Screenshot at May 28 18-59-23


But is suppoused to be permittable
Screenshot at May 28 19-00-51

**Comment by shoom3301** [comment]
Custom recipient testing:
1. When you try to add some text at the beginning of the address or in the middle then cursor jumps to the input ends. It's a new bug, it's not reproducible on prod
2. When prefix doesn't match to the current network we only show the warning, but allow placing an order with this recipient. I think it must block an order placement

image


image

**Comment by shoom3301** [comment]
Tested navigation in the widget, it works as expected corresponding to https://github.com/cowprotocol/cowswap/pull/4471 test description.
When you change colors in the configurator, then it doesn't add entries into history.
**But, when you switch between swap/limit/twap pages it does.**

@anxolin is this expected?

**Comment by shoom3301** [comment]
>Almost fully filled orders
>Not easy to reproduce. Does anyone have an pending order like this to check?

@alfetopito unfortunately no :( I've mocked the state in my PR

**Comment by alfetopito** [comment]
> This link was broken: image
> 
> Takes you to https://dev.explorer.cow.fi/arb1/address/0x79063d9173C09887d536924E2F6eADbaBAc099f5 . Selects mainnet image
> 
> Looks like is talking me to my account not the TZ
> 
> Also the notification tooke me to a 404, I believe cause the explorer path is `ABR` and the link is `ARB`
> 
> https://dev.explorer.cow.fi/arb1/orders/0x48750ca3b8d870336027a1283253b71316319dd0f9c8b4844d5b80a01abbc4cb6dfe75b5ddce1ade279d4fa6bd6aef3cbb6f49dbffffffff
> 
> https://dev.explorer.cow.fi/abr1/orders/0x48750ca3b8d870336027a1283253b71316319dd0f9c8b4844d5b80a01abbc4cb6dfe75b5ddce1ade279d4fa6bd6aef3cbb6f49dbffffffff?tab=overview

Fixed on https://github.com/cowprotocol/cowswap/pull/4493/commits/09b897112ae6ca80431c2d5d27ed004572e6c98e

**Pull request merged**
