### PR TITLE
Fix cypress

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Fix Limit order tests

image

It was not waiting enough for the limit order input to be enabled. 
I refactord the tests so they are easier to read and less error prone (dryer)

# To Test
Check cypress result in this PR

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @anxolin , fails for Limit orders: 
image

**Comment by anxolin** [comment]
Why?? locally works. 

Taking another look!

image

**Comment by elena-zh** [comment]
Hey @anxolin , now I see only 1 test instead of 7
image

**Comment by anxolin** [comment]
The main issue was solved, but still the tests sometimes don't work. They were broken before this version, so i will merge to not delay more the RC (since it was broken, and this PR only improves, and because of the time it takes to run them all i need to postpone this fix)

**Pull request merged**
