### PR TITLE
332/refactor use address

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Follow up to this comment https://github.com/cowprotocol/cowswap/pull/647#discussion_r903639364

# To Test

1. Test regular affiliate flow
* Should work like before

### CODE REVIEW

**Comment by elena-zh** [comment]
Originally reported in https://github.com/cowprotocol/cowswap/pull/747#pullrequestreview-1020311557

Once I opened the PR preview link, I started seeing an affiliate program message. However, I had not shared a referral link . Moreover, when I stitched to Mainnet, 'invalid referral code' message started to be displayed. 
Could you please take a look at this issue?
no referral
reff
affiliate

**Comment by alfetopito** [comment]
> Originally reported in [#747 (review)](https://github.com/cowprotocol/cowswap/pull/747#pullrequestreview-1020311557)
> 
> Once I opened the PR preview link, I started seeing an affiliate program message. However, I had not shared a referral link . Moreover, when I stitched to Mainnet, 'invalid referral code' message started to be displayed. Could you please take a look at this issue? no referral reff affiliate

Thanks!

Can you check again now? (after the build completes)

**Comment by alfetopito** [comment]
> @alfetopito , I still see this message when I open the app link for the 1st time image

It was (another) silly mistake.

Should be all good now! ™️ (famous last words)

**Comment by alfetopito** [comment]
Elena, I'm merging this to the parent PR to consolidate.
I think it makes sense for you to test it all there instead https://github.com/cowprotocol/cowswap/pull/629

I can always create a new PR if there still something to be addressed

**Pull request merged**
