### PR TITLE
Fix input in CurrencyInputPanel when value is zero

### LINKED ISSUE #1658: [no LIMIT] Allow to delete one caracter in "0.1"  so it shows "0." instead of 0 "0." in inputs,

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1658 #1677

In `CurrencyInputPanel` there was a wrong overriding of `typed value` for zero values (`0` or `0.` or `0.0`).

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , MAX button is missing on the Limit orders page
image

**Comment by elena-zh** [comment]
Hey @shoom3301 , just 1 nitpick that I have noticed, and it is related to the Max button when ETH token is in the Sell field: 
when press on it, we show ETH balance - 0.01. In this case we hide Max button. See: Swap form: 
image

Limit orders form: 
image

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , MAX button works great for wrap/unwrap transactions, but it is still not fixed for orders/when TO field is empty: 
image
image

Thanks!

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by anxolin — APPROVED** [review]
Looks good, and fixes the issue with `0.` but, nitpicking, its also strange we remove the DOT `.` when we delete a character in `2.5` --> `2` (Imagine i just want to change 2.5 for 2.4)

**Comment by shoom3301** [comment]
> Looks good, and fixes the issue with `0.` but, nitpicking, its also strange we remove the DOT `.` when we delete a character in `2.5` --> `2` (Imagine i just want to change 2.5 for 2.4)

@anxolin good point! Fixed

**Pull request merged**
