### PR TITLE
feat(number-input-arrow): add arrows to custom deadline input

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Waterfalls onto https://github.com/cowprotocol/cowswap/pull/3001

Add and wire up arrow keys to custom deadline inputs

Screenshot 2023-08-04 at 09 18 37

## Notes

- Styles have been broken and need re-work. Out of the scope of this PR. @fairlighteth can you take care of it?

# To Test

1. On TWAP form, open the custom deadline modal
* Both fields should have arrows
* Arrows should change the values
* Up and down keys should change the values

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , nice, however, here are issues I faced: 
1. Why minutes are limited by 100 000 (about 70 days)? In terms if hours it is OK (as duration should not be longer than 6 months), but minutes should not be limited, IMO
image
2. When a set a custom deadline, and then open the modal once again, it shows 0 instead of the selected value (see the fix #2952 )
after refresh shows 0
3. When I select 5 hours, for example, close the modal without clicking on the Apply, and open it once again, it shows 5 hour and 5 minutes. However, it should show the selected value in the Total duration field (or 0s if a custome deadline is not selected)
4. As I mentioned in the #3001, pressing on arrows other labels are highlighted :)

**Comment by alfetopito** [comment]
> Hey @alfetopito , nice, however, here are issues I faced:
> 
>     1. Why minutes are limited by 100 000 (about 70 days)? In terms if hours it is OK (as duration should not be longer than 6 months), but minutes should not be limited, IMO
>        image

Limitation removed

>     2. When a set a custom deadline, and then open the modal once again, it shows 0 instead of the selected value (see the fix [fix(twap): display actual value for num of parts and custom deadline #2952](https://github.com/cowprotocol/cowswap/pull/2952) )
>        after refresh shows 0

Fixed
 
>     3. When I select 5 hours, for example, close the modal without clicking on the Apply, and open it once again, it shows 5 hour and 5 minutes. However, it should show the selected value in the Total duration field (or 0s if a custome deadline is not selected)

Fixed
 
>     4. As I mentioned in the [feat(number-input-arrow): wire up number input arrows #3001](https://github.com/cowprotocol/cowswap/pull/3001), pressing on arrows other labels are highlighted :)

Won't fix (for now) (also, not reproducible on FF :))

**Comment by elena-zh** [comment]
Hey @alfetopito , everything mostly fixed, however, the value is reset when I refresh the page: 
image

**Comment by alfetopito** [comment]
@elena-zh should be fixed now 🤞

**Review by elena-zh — APPROVED** [review]
Great job, Leandro!

**Review by fairlighteth — APPROVED** [review]

**Pull request merged**
