### PR TITLE
Add zengo

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Adds Zengo wallet. Again...

Re-applies these changes https://github.com/cowprotocol/cowswap/pull/2044/files

# To Test
Zengo wallet works

### CODE REVIEW

**Review by nenadV91 — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @anxolin , I have done my tests for this PR. 

- When connect to Zengo app in iOS from desktop version, everything works as expected. 
- When connect to Zengo in Android, then I can't run any type of transactions: no order confirm request appear in the wallet there. 
- The same is when connect to Zengo in Android from the mobile browser in Android. 
- When connect to Zengo in iOS, orders are placed. But I have noticed 1 issue when signing onchain transactions in iOS: when I return back to the CoW Swap app in the browser, I see a white screen there
image


Also, just to mention: in the wallet connect modal Zengo Wallet is placed to the 14th page. search is not working
image


And in this PR issue with highlighting 2 connected options is returned back
option

(it was fixed in #2057)

Thanks

**Comment by nenadV91** [comment]
@elena-zh Except for the last point that will be fixed in following PR's, I think those other points are not specific to this PR and you will probably get the same issues if you connect Zengo wallet to the wallet-connect on prod. I would suggest that we continue with merge and we can address those issues later.

**Comment by elena-zh** [comment]
@nenadV91 , you are right that all these issues exist on the Prod. However, we are adding this wallet option, so I have to report this issue in one of the current PRs to let you know about them. 
For me it is not a good idea to leave these issues as they are, and show the button for the wallet that is not properly working.

**Comment by elena-zh** [comment]
Reported all these issues in the separate task #2097

**Comment by anxolin** [comment]
Yes, sorry @elena-zh. i'm re-applying nenad's PR only to test the refactor works as intended. 

@nenadV91 @elena-zh  I will leave it up to you when you want to merge.

**Review by elena-zh — APPROVED** [review]
Hey @anxolin , @nenadV91 , I have created a separate task for issues I reported, so they can be addressed later. So I'm approving the current changes.

**Pull request merged**
