### PR TITLE
[1.23] Fix fee discount color in ReceiveAmountInfo tooltip

### LINKED ISSUE #1159: [1.23]Barn: Fee with discount is not in green
1. Open the app in Barn
2. Connect to a wallet that has COW tokens for a fee discount
3. Specify a token pair and an amount to trade
4. Open 'Receive (incl fee) tooltip

**AR**: Fee with discount line is not in green

**ER**: the line should be in green (when it contains a discount)

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1159

image

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
LGTM!

**Review by anxolin — COMMENTED** [review]
Great changes, but functionally, if we have a fee that is negative, its a discount, right? 

Shouldn't we have positive sign, leave it green, and replace `Fee` by `Discount`?

**Comment by shoom3301** [comment]
@anxolin Unfortunately I don't know :( I just copied from the previous UI

**Comment by alfetopito** [comment]
> @anxolin Unfortunately I don't know :( I just copied from the previous UI

Agreed, let's address this in a separated issue.

**Comment by elena-zh** [comment]
> Great changes, but functionally, if we have a fee that is negative, its a discount, right?
> 
> Shouldn't we have positive sign, leave it green, and replace `Fee` by `Discount`?

Hey @anxolin , it was discussed in https://cowservices.slack.com/archives/C036G0J90BU/p1648462406919099

**Pull request merged**
