### PR TITLE
feat: add loading logo for hook

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses https://github.com/cowprotocol/cowswap/issues/5098 

https://github.com/user-attachments/assets/b153cb33-a6aa-4257-9f62-3fa9201a5929

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , I like the new loader very much!
One question: is this OK that sometimes 1 loader is changed to another one? See the video: https://www.loom.com/share/7d9847e1c6f44eb1bc992f76ef2d996c

I've also provided you a video with steps I do for the second case reported in https://github.com/cowprotocol/cowswap/issues/5098#issuecomment-2488008774

**Comment by fairlighteth** [comment]
@elena-zh thanks for reviewing
1) So what happens is that for external hooks (loaded using an Iframe) we show a loading logo before the iframe is loaded. The second circular spinner you see, actually comes from the externally loaded hook (iframe) itself and is not something that is controlled in the CoW Swap app.

2) Thanks for the clarification, I will review this.

**Comment by fairlighteth** [comment]
@elena-zh please check the tooltip issue, this should be resolved now.

**Review by elena-zh — APPROVED** [review]
LGTM!

**Comment by fairlighteth** [comment]
@elena-zh should be fixed now:
Screenshot 2024-11-20 at 16 43 10

**Review by shoom3301 — APPROVED** [review]
Awesome!

**Pull request merged**
