### PR TITLE
goerli: adding tokens with liquidity

### PR DESCRIPTION
**Pull request by W3stside**
GNO: https://goerli.etherscan.io/address/0x02ABBDbAaa7b1BB64B5c878f7ac17f8DDa169532
0x: https://goerli.etherscan.io/address/0xe4E81Fa6B16327D4B78CFEB83AAdE04bA7075165
BAT: https://goerli.etherscan.io/address/0x70cBa46d2e933030E2f274AE58c951C800548AeF
DAI: https://goerli.etherscan.io/address/0xdc31Ee1784292379Fbb2964b3B9C4124D8F89C60
POLY: https://goerli.etherscan.io/address/0x9e32c0EfF886B6Ccae99350Fd5e7002dCED55F15
USDC: https://goerli.etherscan.io/address/0xD87Ba7A50B2E7E660f678A895E4B72E7CB4CCd9C

image

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
USDC and DAI addresses are wrong, right?

**Review by nenadV91 — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @W3stside , could you add COW token to the list? 
https://goerli.etherscan.io/address/0x3430d04E42a722c5Ae52C5Bffbf1F230C2677600

**Comment by W3stside** [comment]
> Hey @W3stside , could you add COW token to the list? https://goerli.etherscan.io/address/0x3430d04E42a722c5Ae52C5Bffbf1F230C2677600

it's already there, does it not show up?

**Comment by elena-zh** [comment]
I did not notice it in the code part, and I can't see it on UI as we disabled Gorli network. 
So I added this comment just in case it is not added.

**Comment by W3stside** [comment]
merging this, please verify cow is there after goerli is re-enabled

**Pull request merged**
