### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Minor fixes pulled from https://github.com/cowprotocol/cowswap/pull/978

1. No longer defaults to wrapped native -> USDC
2. Show cow discount 0% when on unsupported network
3. Only show activities count if > 0
4. Do not show price estimation for wraps
5. Show `connect wallet` when wrapping and wallet is not connected

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , I have noticed that 'Insufficient balance' error is displayed to a not connected user when ETH/WETh token pair is selected, amounts are 0
insuff balance

Compare with Prod: 
image

**Comment by elena-zh** [comment]
All the rest changes (besides #997 issue) LGTM!

**Comment by alfetopito** [comment]
Merging to release to consolidate onto release branch.
Will address any issues in a follow up PR

**Comment by elena-zh** [comment]
LGTM!

**Pull request merged**
