### PR TITLE
Refactor progress bar / animations

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

https://github.com/user-attachments/assets/8c14f709-30c9-4ae6-9075-61c3ba82c81e

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Something broke here and I can't tell what.
The bar remains in the first step forever.

**Comment by elena-zh** [comment]
@fairlighteth , I see that 'Executing' step is labeled as step 2 instead of 3

**Comment by MindyCoW** [comment]
Currently got a trade that's been stuck at Placing for over 3 minutes

**Comment by fairlighteth** [comment]
> Something broke here and I can't tell what. The bar remains in the first step forever.

Had committed with debug mode on. Should have been off

**Comment by alfetopito** [comment]
@fairlighteth I merged the parent branch into this one to address the conflicts

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
