### PR TITLE
Hooks store styleimprove

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses comments from https://github.com/cowprotocol/cowswap/issues/4945

Screenshot 2024-10-07 at 18 03 02
Screenshot 2024-10-07 at 18 02 43
Screenshot 2024-10-07 at 18 02 35

---

Screenshot 2024-10-07 at 17 37 27
Screenshot 2024-10-07 at 17 33 11
Screenshot 2024-10-07 at 17 32 56

### CODE REVIEW

**Comment by elena-zh** [comment]
@fairlighteth , the build for swap-dev is failed. Could you please retrigger it once again?

**Comment by elena-zh** [comment]
As for Explorer changes, look great!
However, some issues: 
1. I'd show dash in the hooks field when it is empty like we do for all the rest fields: 
dash
2. When there [is only one hook added](https://explorer-dev-git-hooks-store-styleimprove-cowswap.vercel.app/sepolia/orders/0xc816e9029f4d28b5f717e38c34275ac7a05e01cc8b6562a24a0b5500187ca6839fa3c00a92ec5f96b1ad2527ab41b3932efeda5866fe86be?tab=overview), there is an excessive intend at the bottom of the field (same started to happen with the AppData field). Might it be reduced?
room
3. Could you please make font-size the same in these links? 
font

Thanks!

**Comment by fairlighteth** [comment]
Re-triggered build @elena-zh

**Review by shoom3301 — APPROVED** [review]
Codewise all good!

**Comment by elena-zh** [comment]
Hey @fairlighteth , thanks!

Changes on CoW Swap also LGTM, however: 


1. It would be great to improve mobile views: mobile
2. WDYT about making all this line clickable? 
image
3. The last message to clarify: Hooks section inside the account modal should be left as it is, correct? 
image

Thanks!

**Comment by fairlighteth** [comment]
@elena-zh Addressed all Explorer and CoW Swap feedback points now. As for:

> WDYT about making all this line clickable?

The idea here is that in the future there could be more links in there

> The last message to clarify: Hooks section inside the account modal should be left as it is, correct?

Yes

**Comment by elena-zh** [comment]
Hey @fairlighteth , Explorer changes LGTM!

One question related to the CoW Swap: when I press on the 'Select token' button, the token list is opened at the top of the form. Depend on a device, sometimes the screen is not scrolled to the top on this action, so it looks like that I press on the button, and nothing happens: 
on top

Might this be fixed somehow?

**Comment by shoom3301** [comment]
@elena-zh @fairlighteth I've fixed the issue above

**Pull request merged**
