### PR TITLE
Token page improvements 1

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

This PR fixes few issues mentioned by @elena-zh 
- loading effect on balances
- pagination to first and last
- disable balance sorting on no wallet connected
- return to start of table page on chain change

### CODE REVIEW

**Comment by elena-zh** [comment]
@nenadV91 , changes LGTM!

Some tiny issues: 
1. It would be great to make pagination look nicer in a mobile view (my device is iPhone 12 mini): 
image
2. It would be nice to remove a glove from 'Balance' column, pagination arrows when they are disabled
hover effect
the same for pagination
like we do for other columns
emample

Thanks!

**Comment by anxolin** [comment]
@nenadV91 u need to push your workmates for reviews! If you see they ignore your PR, send some reminders in our channel

cc/ @W3stside can u review?

**Comment by elena-zh** [comment]
Hey @nenadV91 , 
I have done another round of testing and noticed, that 
1. Account page shows only 2 sections now. Is it OK? 
2 sections
2. It would be nice to remove a glow from pagination arrows when they are disabled
glove
3. I do not remember, maybe I reported it in one of related PRs: Favourites tokens table is eternally loading when navigate to the 2nd page, then press on the 'Restore defaults' button. See the [video](https://watch.screencastify.com/v/22Pvv6COuA9pci29B40T). 

Thank you!

**Comment by nenadV91** [comment]
@elena-zh 
1. Yea, its fine for now until we create those other pages
2. If you meant the hand cursor, that is done in the next PR
3. Fixed this in next PR

**Review by elena-zh — APPROVED** [review]
Approved then!

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
