### PR TITLE
feat: add tag styling for tokenlist

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses https://github.com/cowprotocol/cowswap/issues/3498 

# Todo

The current height of each Tokenitem is not re-calculated after the given estimated height (`const estimateSize = () => 56`)
for the Virtual list. @alfetopito @shoom3301 if possible review this PR and see if we can re-calculate the actual height of each token item container. Also on resize of the viewport (https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) would be good to detect if height changes.

## Desktop 
Screenshot 2024-01-22 at 13 15 46

## Mobile / small viewport
Screenshot 2024-01-22 at 13 05 00
Screenshot 2024-01-22 at 13 04 45

As you see above the Token item for USDC stays at 56px height whereas it should be higher.

**This is what the expected result should have been:**

Screenshot 2024-01-22 at 13 04 30Screenshot 2024-01-22 at 13 04 19

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @fairlighteth , thanks for fixing this!
However, I have some issues to report: 
1. Look: 'selected' area looks like hides all these labels (desktop view+reduced screen)
selection
2. In a mobile view 'gas-free' approval label is placed closer to the next token's balance, so it confuses me a bit
related

Could you please take a look at these issues? 
Thanks

**Review by shoom3301 — APPROVED** [review]

**Comment by shoom3301** [comment]
@elena-zh issues you mentioned are fixed

**Comment by fairlighteth** [comment]
@shoom3301 Thanks for fixing the calculation of dynamic heights! 

Pushed some updates to improve the layout further:

Screenshot 2024-01-29 at 17 46 03

Screenshot 2024-01-29 at 17 45 52

Screenshot 2024-01-29 at 17 45 41

Screenshot 2024-01-29 at 17 44 56

Screenshot 2024-01-29 at 17 44 43

Screenshot 2024-01-29 at 17 44 32

Screenshot 2024-01-29 at 17 44 16

**Comment by elena-zh** [comment]
Looks good, thank you!

**Comment by anxolin** [comment]
Nice work!

**Pull request merged**
