### PR TITLE
Parse sell/buy amount from URL and apply to Swap widget

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Parse `sell/buy` amount from `URL` and apply to Swap widget
Examples:
`/#/1/swap/WETH/COW?sellAmount=750.20`. 
`/#/1/swap/WETH/COW?buyAmount=750.20`. 

In case when both `sellAmount` and `buyAmount` are specified, `buyAmount` will be ignored.

The old format:
`/#/swap?inputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&outputCurrency=0x6b175474e89094c44da98b954eedeac495271d0f&exactAmount=1500&exactField=output`

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job. 
Some issues:
1. it would ne nice to make parameters case-sensitive
case sensitive
2. the link is not working when insert a comma into the amount
period
3. I think, it would be nice to clear out the URL when an amount is incorrect (however, it might be not a bug, but a feature)
not cleared out
4. I think it would be create to enter decimal amounts that start with a period
period pre
5. Maybe I'm a terrible link constructor, but when I filled in the link with both parameters, none of them was not applied
2 types
6. We do not apply these changes to limit orders page, correct?
does not work for linit orders

Thanks!

**Review by anxolin — APPROVED** [review]
Works great! do we plan to add same for limit orders later?

**Comment by shoom3301** [comment]
https://github.com/cowprotocol/cowswap/pull/1708
@anxolin @elena-zh for Limit orders

**Comment by shoom3301** [comment]
@elena-zh thanks!

1. Keys signatures must be accurate, we should do this
2. We allow only integers and floats. Example: 500, or 12.005. Comma is not allowed
3. Good! Fixed!
4. Fixed here: https://github.com/cowprotocol/cowswap/pull/1708
5. Must be: `?sellAmount=2222&buyAmount=111`
6. https://github.com/cowprotocol/cowswap/pull/1708

**Comment by alfetopito** [comment]
> 3rd case LGTM! However, I would also clear out the URL when an incorrect parameter is entered there image

Let's create another issue to deal with that and merge as is right now

**Comment by elena-zh** [comment]
> > 3rd case LGTM! However, I would also clear out the URL when an incorrect parameter is entered there image
> 
> Let's create another issue to deal with that and merge as is right now

Reported in #1781

**Pull request merged**
