### PR TITLE
[1.23] Update CoW logo

### LINKED ISSUE #1114: Change COW token icon
Discussion: https://cowservices.slack.com/archives/C0361CDG8GP/p1664356608688319

1. Open Account pages: Tokens page and Overview
2. Check the Cow token logo

**AR**: the old token logo is displayed

Token lists: 

**Should be:**

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary
Fixes #1114

See all logo changes in #1114

Before: 
image

After:
image

### CODE REVIEW

**Comment by shoom3301** [comment]
@elena-zh I haven't updated CoW logo in the Token list, because it should be updated in the listing: token-list.cow.eth. I will ping you when it will be change.

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
I have just clarified that it would be great to change vCOW icon as well. 
image

Here it is 
Copy of 2022_micro-vCOW-token

Could you please do this?

**Comment by shoom3301** [comment]
@elena-zh Done

**Comment by elena-zh** [comment]
Hey @shoom3301 , changes LGTM besides the icons in token lists, but you mentioned about it: 

> @elena-zh I haven't updated CoW logo in the Token list, because it should be updated in the listing: token-list.cow.eth. I will ping you when it will be change.

Given the fact that these icons should be updated outside of the current task, the PR is approved.

**Review by elena-zh — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
Approved!

Only minor question:

Why do we have what seems to be a repeated image and on top of that the second image is much larger than the original?

Screen Shot 2022-10-06 at 08 38 55

**Review by alfetopito — APPROVED** [review]
Approved!

Only minor question:

Why do we have what seems to be a repeated image and on top of that the second image is much larger than the original?

Screen Shot 2022-10-06 at 08 38 55

**Review by anxolin — APPROVED** [review]
Approved!

@elena-zh for now v token we will leave like that. However, I think we have a problem with the logos we show in `Account`

There's 3 logos of tokens:
- vCOW: ✅
- COW: ✅
- vesting COW from GNO Contract ❌

The problem I see, is that we represent this last one in the same way as $COW. This causes some confessions (I recently received feedback) @fairlighteth does it make sense to just change the background for vesting COW for GNO locked tokens (or some other differentiation)

Anyways, approving because its out of the scope of this PR

**Comment by elena-zh** [comment]
> Approved!
> 
> @elena-zh for now v token we will leave like that. However, I think we have a problem with the logos we show in `Account`
> 
> There's 3 logos of tokens:
> 
> * vCOW: ✅
> * COW: ✅
> * vesting COW from GNO Contract ❌
> 
> The problem I see, is that we represent this last one in the same way as $COW. This causes some confessions (I recently received feedback) @fairlighteth does it make sense to just change the background for vesting COW for GNO locked tokens (or some other differentiation)


I have created created #1177 issue for this case.

**Pull request merged**
