### PR TITLE
Feature/limit UI update - #2164 negative price

### LINKED ISSUE #2164: 'Executes at' may show a negative price
**TO reproduce:**
1. Go to the Limit orders page
2. Place a tiny Limit buy order (e.g. buy 1 COW per WETH)
3. Check Executes at price

**AR**: 'Executes at' shows a negative price

**ER**:  'Executes at' can't show a negative price

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #2164 

Should no longer show prices with negative values

## Before
Screenshot 2023-03-23 at 11 00 19
## After
image

# To Test

1. Place one order with a tiny sell amount
2. Wait for the fees to higher than the sell amount
* You should NOT see a negative price

### CODE REVIEW

**Comment by alfetopito** [comment]
@elena-zh @anxolin 

I know this is terrible, so please tell me.
What should I show when fee > sell amount?
Both for the price and for the tooltips

image
Screenshot 2023-03-23 at 15 20 50

**Comment by alfetopito** [comment]
Update based on Anxo's proposal:

image

**Review by anxolin — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @alfetopito , great changes!
One of my proposals is not to show 2 warnings at a time for unfillable orders as they repeat one another from my point of view
image
image


Also, I noticed that one of my orders is hanging with the green icon for a long time, and is not executed. 
From one hand, the green indicator is displayed due to Executes at is less than a market price. 
less then market

But when I revert a price, I see that the Executes at is greater than the Market price, and it is greater by more than 0.5% (and it should be blue indicator). 
greter than market
Could you please check this? 

Thank you!

**Comment by alfetopito** [comment]
> Hey @alfetopito , great changes! One of my proposals is not to show 2 warnings at a time for unfillable orders as they repeat one another from my point of view image image

Done, will not show the first tooltip when `unfillable`

> Also, I noticed that one of my orders is hanging with the green icon for a long time, and is not executed. 

That we talked about before, and might be due to other factors

> From one hand, the green indicator is displayed due to Executes at is less than a market price. less then market
> 
> But when I revert a price, I see that the Executes at is greater than the Market price, and it is greater by more than 0.5% (and it should be blue indicator). greter than market Could you please check this?

It's expected. When you invert the price, the opposite is true: higher is better.
So anything above the market price will show the green dot

**Comment by elena-zh** [comment]
Hey @alfetopito , thank you!
Last nitpick: could you please remove a glove from the Unfillable button as It is not clickable
remove glow
And I can't understand why for several orders Executes at price can't be loaded 
image
You can check it when connect to the 0x9FA3c00a92Ec5f96B1Ad2527ab41B3932EFEDa58 account in Gorli.

**Comment by alfetopito** [comment]
> Hey @alfetopito , thank you! Last nitpick: could you please remove a glove from the Unfillable button as It is not clickable remove glow 

I can certainly remove it, and it makes sense.
Just as an easter egg, have you tried clicking on the unfillable label? ;)

And I can't understand why for several orders Executes at price can't be loaded image You can check it when connect to the 0x9FA3c00a92Ec5f96B1Ad2527ab41B3932EFEDa58 account in Gorli. Or here is [the link](https://dev.explorer.cow.fi/goerli/orders/0x8b0a62d50a6e23f80bef8163e0b3455be8cc7dc5a7a3103258c69f1d27f898549fa3c00a92ec5f96b1ad2527ab41b3932efeda586425ee17) for one of orders where Executes at cant' be loaded

I'll check your account again, and I already have a hunch as this happened to me before:
Similar to one of the issues you raised on https://github.com/cowprotocol/cowswap/pull/2155, when we query for an amount whose fee is too high, the backend doesn't return a value, but instead an error.
In that case, we can't calculate the execution price as we don't have a base from the backend.
So it stays pending. Can you create an issue in the mean time? I probably won't be able to address it before the release

**Comment by alfetopito** [comment]
Yep, that's the case for at 2 of your pending orders
image

Although this is not optimal, I find the UX ok as it just means we don't have a price for it yet
The best approach would be to detect this and use the unfillable label, but I won't be able to finish this today.

Can you create an issue on the backlog for this then?

**Comment by alfetopito** [comment]
FYI, I'll merge to the parent to consolidate.
Unless there's a blocking bug, follow up issues will have to go to the backlog

**Comment by elena-zh** [comment]
Hey @alfetopito , 

> Just as an easter egg, have you tried clicking on the unfillable label? ;)
I tried, nothing happened:)

> Can you create an issue on the backlog for this then?
Here it is https://github.com/cowprotocol/cowswap/issues/2183

**Comment by alfetopito** [comment]
> Hey @alfetopito ,
> 
> > Just as an easter egg, have you tried clicking on the unfillable label? ;)
> 
> I tried, nothing happened:)


It should: 

https://user-images.githubusercontent.com/43217/228006054-a78c1a7c-ee71-423e-82f8-31065d749759.mov


> > > Also, I noticed that one of my orders is hanging with the green icon for a long time, and is not executed.
> > 
> > 
> > That we talked about before, and might be due to other factors
> 
> Finally, I can understand why these orders are not executed: now I see a hight fee warning for them. image

Maybe this is something else... we are working on it

**Pull request merged**
