### PR TITLE
feat(hook store): Add CoW AMM withdraw iframe dapp

### PR DESCRIPTION
**Pull request by yvesfracari**
# Summary

- Adds the CoW AMM Withdraw Pre Hook into the hook store registry by integrating with Bleu repository (https://github.com/bleu/cow-hooks-dapps/tree/main/apps/withdraw-pool)

image
image
image
image
image

# To Test

1. Go the hooks tab on Sepollia chain
2. Connect your wallet and switch to Sepollia chain
3. In Hooks > Add Pre-Hook Action, the withdraw hook should appear in the "All hooks" section. 
4. To fully test the featureyou must have liquidity on one CoW AMM pool. I already added some for these addresses:
  - 0x8FAb71C0d4272698A3B2d1F3Ed5FC3c1B9b3E531
  - 0xFF714b8b0e2700303eC912BD40496C3997ceEa2b
  - 0xFF714b8b0e2700303eC912BD40496C3997ceEa2b

# Note:

- Smart Wallets are not supported yet since we have to define how the transaction flow would work (on the approval). If you have some idea, please share with us 😃

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @yvesfracari , great job!

But some issues from my side :) 
**Functional issues:** 
1. It would be nice to hide a token selector if a user does not have CoW AMM LP tokens and show a validation message instead:
no liquidity
2. Adding a hook got stuck after I approved a LP token partially
ыегсл
3. The app makes me to approve a LP token once again if I've already approved it (partially), but a withdrawal amount is =< the approved one. 
approved
4. Edit a hook button opens an initial hook screen instead of showing an added hook details
5. Numbering should start with 1 

6. Might it be possible to show token's balances or, at least, their USD estimation in a token list? 
image
7. When I pick a liquidity token, or pick a percentage to withdraw, the screen blinks

---

**UI-UX issues:** 
Overall, all elements should inherit the CoW Swap's style
1. Button
image
compare with 
image

2. Token list 
image
compare with 
image

If it is possible to you, you can inherit it from the Rescue funds feature: 
example
you can find it by clicking on this link
same like in resque

3. Text area: 
image
may be inherited from a fee container 
image
or from a token list UI

4. Stepper: 
image

Might be inherited from a permit flow
image

5. It would be great to show an approved token (see the example above) and rename the 2nd step into 'Add pre-hook'
steps


6. It would be great to use the same style for the 'Connect wallet' message like we have in all the rest hooks: 
connect font
font1

7. It would be great to improve responsive views: 
image

**Comment by yvesfracari** [comment]
Thanks for all feedbacks @elena-zh !

I just pushed some changes and here is a summary based on your points.

Functional issues:
1- Added the message that you requested.
2- Couldn't replicate it but changed it to use just the necessary token amount as default. let me know if the issue persists.
3-Same as 2.
4-This one is tricker. Since this is a more complex hook, it is hard to decode the data to restore the app's state. I pushed some changes to recover the pool, but the percentage is harder. Do you think that is necessary?
5-Thanks! Fixed it.
6-Added more information, could you take a look? Keep in mind that price info might be strange on sepollia.
7-Worked on it, could you test it again?

UI-UX issues:

Since I am developing the app outside this repo I think that I can't reproduce 100% or import the components. However, I am trying to make them more similar.
1-Done.
2-I refactored the component to be similar, however, this is a pool list and not a token. Let me know if you have any ideas on how to improve this.
3-Done.
4-This stepper that you showed was my first reference, however, there are some cases here where multiple steps are required, so I think that a vertical stepper would be better. I tried to make it more similar to the cowswap style, wdyt?
5-Done.
6-Done.
7-Done.

**Comment by yvesfracari** [comment]
Hey thanks again for the feedbacks

Functional issues:
- 1,2,4,6: I managed to reproduce and fix it.
- 3: I couldn't reproduce the issues on my side but made some changes that I think that fix it.
-5: I couldn't reproduce it, could you give more information about it?

UI changes:
1. I tried to make it more similar, and this component would be a bit different because is a pool selector (and not token selector). In terms of features, I think that both are equivalent. Can you share with me what parts of the atributes you would suggest to be more similar?
2. Updated the fonts.
3. Tried to make more similar with the tokens one.
4. I hid the percentage buttons on smaller screens and enhanced the scrollbars.
5. I updated the bg color of the pool selector.
6. I imported one spinner that I found on cowswap repo, let me know if it is better.
7. Let me know if you have any specific feedback.

**Comment by elena-zh** [comment]
Hey @yvesfracari , thank you! It looks better now!

Still I can see some issues: 
1. Still, the UI blinks when I pick a token in the dropdown
2. Thank you for fixinf 'edit hook' feature! The only one nitpick there is to change the button's name to 'Update Pre-hook' 
update
3. There is an issue with account change feature:
 - Open the prehook
 - pick a liquidity token in the selector
 - while the hook form is opened, change an account in the connected wallet --> the hook details will be still displayed on the form, however, they are not relevant to a newly connected user. It would be great to close the form in this case
 4. The issue with a partial approval is still here. I've recorded a video for you with STR: https://www.loom.com/share/6ef314cdcb254d5ebb7a069d9772337f
 5. There is a scrollbar that is always displayed on the hook even if it is not needed. So, it would be great to: 
- hide it when no scroll is needed
- apply more or less the same styling for it. See an example: 
image
6. When a user rejects an action in the wallet, it would be great to navigate him back to the initial screen or add a message that has a button that allows to go back to start again 
image
Something like 
image

7. As for the dropdown style, you can re-use the one we have on the Limit order confirm modal: 
dropdown dark
dropdown
8. @fairlighteth , kindly remind you to review this PR in terms of styling/wording/etc. and provide your valuable feedback on it. 

Thanks

**Comment by yvesfracari** [comment]
Thanks again @elena-zh !

1-There is one loading when you change the pool since if its data isn't on the cache it might take a while. When the data is in the cache this process is very fast and it can be similar to a blink. Do you think that is a problem?
2- Fixed
3- Thanks, fixed.
4-I added an error to cover this case.
5- Fixed. Can you check it?
6-Tried to improve the error messages and add a back button.
7-Improved the style of the component, let me know if it is better.

**Comment by elena-zh** [comment]
Hey @yvesfracari , thank you!

1. 

> There is one loading when you change the pool since if its data isn't on the cache it might take a while. When the data is in the cache this process is very fast and it can be similar to a blink. Do you think that is a problem?

Yes, I do. There is no other place on the CoW Swap UI where something blinks/shakes on load. This also creates bad UX  impression on a user in terms of a quality of a product, IMO. That is why I'm constantly reporting this issue here. 

2. Related to the 4th case from this https://github.com/cowprotocol/cowswap/pull/4947#issuecomment-2414076233 : thank you for adding a error state when this happens, so users will be aware of that is smth went wrong. 
But why this TX fails? For now, I've picked a liquidity token, decided to withdraw 25% of an amount, did not change anything in while approving the token (e.g. approved suggested value), but in the end TX failed anyways:
followed steps - failed

3. There is one navigation issue: 
 - Add this hook
 - Then press on the Edit button
 - Press on the Update button
 - When signing, press on the Cancel button in the wallet
 - Press on the Back button on the form --> you will see an infinite loader on the form
back

4. error rejecting approval TX looks this way 
image

5. As for the scrollbar, I still don't like it :( as it is still displayed where it is not needed, and when it is displayed, it differs from the one we have on the UI. 

6. As for the rest UI elements,  let's wait for @fairlighteth review :)

Thanks!

**Comment by fairlighteth** [comment]
@yvesfracari got some recommendations for you, after reviewing:

1. I'd add `overflow-y: auto !important; padding: 16px;` to the content container:
Screenshot 2024-10-18 at 14 43 32

2. When the pool selector is shown, I'd recommend following the same pattern as the general token selector on CoW Swap, where it takes over the whole container, with a back arrow:

Screenshot 2024-10-18 at 14 59 42Screenshot 2024-10-18 at 14 59 57

This allows for more available space to select a pool


3. In connection with point 2 above, you might consider using a similar design pattern we will start soon to display pools in the context of a list view. See this PR for a UI reference to that https://github.com/cowprotocol/cowswap/pull/5005 


4. I'll be looking into if the iframe can automatically adapt it's height to fully cover the iframe's content. Which then it will simply use the whole page's scroll functionality. But this allows for better (full) visibility of the iframe/hook content:
Screenshot 2024-10-18 at 15 06 15

5. General recommendations for CSS var colors (available in CoW Swap's general context):
- For text: --cow-color-text
- Grey text: --cow-color-text-opacity-70 
- For (table) borders: --cow-color-text-opacity-10 (or --cow-color-text-opacity-25)

 6. Would recommend adding a bit of spacing around selectable elements. Also adding a bit more visual hierachy. Here a full UI suggestion for you to consider:
 
Screenshot 2024-10-18 at 15 26 53


7. When dragging the percentage, could consider highlighting the 75% button as active, to sync up:
Screenshot 2024-10-18 at 15 23 59

**Comment by yvesfracari** [comment]
@elena-zh @fairlighteth thank you both for the review. I tried to implement all your suggestions and fix the errors. The only one that I couldn't reproduce was the second point reported by Elena. I think that the issue was related to slippage changes used on the withdrawal call and the approved amount. To fix this I changed it back to use MAX approves. In addition, I added a better log, so that if the error persists I can have more information to fix it.

**Comment by yvesfracari** [comment]
Thanks again @elena-zh ! About the points that you mentioned:

1 - Ok.
2 - In my opinion, you shouldn't be able to access the hook with a Safe Wallet (as we marked it as not support safe). cc @shoom3301 I think that this should be solved on cowswap app side.
3 - I optimized token logo renders. If the issue is still happening could you record the screen for me? There is a loading state since the component takes some time to render the first time you choose that pool since it will get the data to show. I tested removing this loading state but the user would have the wait on the selector or view a stale component information. The other option that I see is to artificially increase the loading time, let me know if you have any suggestions as well.
4 - Since this is a new pool, 25% of a pool token would be equal to 25 tokens. Since you had approved 15 I think that a new approval is expected, right?
5 - Fixed.

**Comment by shoom3301** [comment]
Yep, 2nd point should be handled on our side.
@elena-zh could you please create an issue? (or add the case to the existing one)

**Comment by elena-zh** [comment]
> 2\. I can pick a token and even can run Approve TX for it. Then it gets stuck

Opened #5015 for this case

**Comment by yvesfracari** [comment]
Thanks for the information @elena-zh !

1 - I think it might be related to a different OS, but with the video, I think that I understood what was happening and fixed it. Could you try again?

2 - I couldn't reproduce it but changed some conversations to be safe

3 - Actually it wasn't an error with the partial approves, but a specific characteristic of that pool. I managed to reproduce and fix it. Could you test it again?

**Comment by elena-zh** [comment]
Hey @yvesfracari , cool! I'm about to approve the PR (however, still I can see some blinking especially in cases when I press on the Edit hook button).
There is the last nitpick is left: when I withdraw 100% of a LP token, and then press on the Edit hook button, could you please remove this table as there is no pool selected in the dropdown
hide

Thanks!

**Comment by elena-zh** [comment]
Hey @yvesfracari , thank you. 

1. Again, facing some difficulties with withdrawing liquidity on [Ethereum](https://balancer.fi/pools/ethereum/cow/0x9bd702e05b9c97e4a4a3e47df1e0fe7a0c26d2f1): 
image
```
Object
calldata
: 
"0xa8481abe00000000000000000000000000000000000000000000000000000000000000a0313732393739343630313937390000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000671aa0200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000034000000000000000000000000000000000000000000000000000000000000005a00000000000000000000000009bd702e05b9c97e4a4a3e47df1e0fe7a0c26d2f1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006423b872dd0000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000009cdeda39d43c678000000000000000000000000000000000000000000000000000000000000000000000000000000009bd702e05b9c97e4a4a3e47df1e0fe7a0c26d2f1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4b02f0b7300000000000000000000000000000000000000000000000009cdeda39d43c678000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000003ef18048b0163c16000000000000000000000000000000000000000000000000000187deef636e19000000000000000000000000000000000000000000000000000000000000000000000000000000009585c3062df1c247d5e373cfca9167f7dc2b5963000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000184de792d5f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000270a082310200ffffffffff007f39c581f595b53c5cb19bd0b3f8da6c935e2ca0a9059cbb010100ffffffffff7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002000000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000000000000000000200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda58000000000000000000000000000000000000000000000000000000000000000000000000000000009585c3062df1c247d5e373cfca9167f7dc2b5963000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000184de792d5f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000270a082310200ffffffffff00def1ca1fb7fbcdc777520aa7f396b4e015f497aba9059cbb010100ffffffffffdef1ca1fb7fbcdc777520aa7f396b4e015f497ab000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002000000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000000000000000000200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda58000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041a60849636feecac1e4155896a0ad4bf3c21158478d71e5ae0e3f21aa895c9d36568207a0b683b8935e6c6752558ef1bc0e62d02ffb11f09474789b0f07659e0a1c0000000000000000000000000000000000000000000000000000000000000019"
chainId
: 
1
target
: 
"0x00E989b87700514118Fa55326CD1cCE82faebEF6"
```
2. Same on Gnosis chain ([pool](https://balancer.fi/pools/gnosis/cow/0xfcd125f4c5030137634863a2d3e5d6d89158f19c))
image
```
 {
    "chainId": 100,
    "calldata": "0xa8481abe00000000000000000000000000000000000000000000000000000000000000a0313732393739343935303233330000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000671aa17c0000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000034000000000000000000000000000000000000000000000000000000000000005a0000000000000000000000000fcd125f4c5030137634863a2d3e5d6d89158f19c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006423b872dd0000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000017d2f7a6c6568fbd00000000000000000000000000000000000000000000000000000000000000000000000000000000fcd125f4c5030137634863a2d3e5d6d89158f19c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4b02f0b7300000000000000000000000000000000000000000000000017d2f7a6c6568fbd0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000002bc0c02cca1be640000000000000000000000000000000000000000000000000abb08fa13cf9ce2000000000000000000000000000000000000000000000000000000000000000000000000000000009585c3062df1c247d5e373cfca9167f7dc2b5963000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000184de792d5f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000270a082310200ffffffffff00177127622c4a00f3d409b75571e12cb3c8973d3ca9059cbb010100ffffffffff177127622c4a00f3d409b75571e12cb3c8973d3c000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002000000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000000000000000000200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda58000000000000000000000000000000000000000000000000000000000000000000000000000000009585c3062df1c247d5e373cfca9167f7dc2b5963000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000184de792d5f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000270a082310200ffffffffff00af204776c7245bf4147c2612bf6e5972ee483701a9059cbb010100ffffffffffaf204776c7245bf4147c2612bf6e5972ee483701000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002000000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000000000000000000200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda58000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041cdd173e1c127363f3c3bc46f5cfbe4231a95986b5a6756ca2509a2912d1a02bf60dc80f4a216e9d11d1b001f5cf9a89ebea85313e14d9a3c21d7f3b3630e312c1b00000000000000000000000000000000000000000000000000000000000000a",
    "target": "0x00E989b87700514118Fa55326CD1cCE82faebEF6"
}
```
3. And on Arbitrum ([pool](https://balancer.fi/pools/arbitrum/cow/0x94a5afbf8f987d6eadb1c0fe73366321c5fe950b))
image

```
{
    "chainId": 42161,
    "calldata": "0xa8481abe00000000000000000000000000000000000000000000000000000000000000a0313732393739353038383330370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000671aa2200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000034000000000000000000000000000000000000000000000000000000000000005a000000000000000000000000094a5afbf8f987d6eadb1c0fe73366321c5fe950b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006423b872dd0000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda5800000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000001c86e8f127d4fed0000000000000000000000000000000000000000000000000000000000000000000000000000000094a5afbf8f987d6eadb1c0fe73366321c5fe950b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4b02f0b7300000000000000000000000000000000000000000000000001c86e8f127d4fed00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000006b5bbbe4c18e6c0000000000000000000000000000000000000000000000000000061c72c5017c000000000000000000000000000000000000000000000000000000000000000000000000000000009585c3062df1c247d5e373cfca9167f7dc2b5963000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000184de792d5f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000270a082310200ffffffffff0082af49447d8a07e3bd95bd0d56f35241523fbab1a9059cbb010100ffffffffff82af49447d8a07e3bd95bd0d56f35241523fbab1000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002000000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000000000000000000200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda58000000000000000000000000000000000000000000000000000000000000000000000000000000009585c3062df1c247d5e373cfca9167f7dc2b5963000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000184de792d5f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000270a082310200ffffffffff00912ce59144191c1204e64559fe8253a0e49e6548a9059cbb010100ffffffffff912ce59144191c1204e64559fe8253a0e49e6548000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002000000000000000000000000079932c178ad3d0a4864b0322ce7a8405d74de29000000000000000000000000000000000000000000000000000000000000000200000000000000000000000009fa3c00a92ec5f96b1ad2527ab41b3932efeda58000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041be0a9ae650b1dcbd25ee4e8d94381e511b629582bf89e99273b3ba678e62379e2e3aac91b780c266ced828c4058844504ff39e6e1b580a1859232271dae1005e1b000000000000000000000000000000000000000000000000000000000000003",
    "target": "0x00E989b87700514118Fa55326CD1cCE82faebEF6"

```}
4. I don't see that withdraw balances are recalculated when I change a percentage to withdraw
![not recaclulated](https://github.com/user-attachments/assets/41661df3-60e6-416e-a48d-3f760462eccb)

**Comment by yvesfracari** [comment]
@elena-zh After you reported this we did a big round of testing on multiple chains. With that, we found and fixed issues related with:

- 1. Stale data to encode hooks.
- 2. Rounding issue
- 3. Unsatable RPC gas estimations
- 4. Issues in withdrawing pools with low user liquidity.

All this was fixed and passed all the tests on our side. Please test it again and let me know if you get any other problem.

**Review by elena-zh — APPROVED** [review]
Thank you! It works now!

**Pull request merged**
