### PR TITLE
feat: release drag drop styling

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Replaces drag and drop to have a touch supporting drag and drop library
- General styling
- Introduce numbering

https://github.com/user-attachments/assets/6e7f5cfc-1416-4df9-a2a0-af016695d212

### CODE REVIEW

**Comment by fairlighteth** [comment]
The library also supports multi select/drag: https://sortablejs.github.io/Sortable/#multi-drag

But keeping it out of scope for this one

**Comment by elena-zh** [comment]
Hey @fairlighteth , the build has been cancelled. Was it done intentionally? If no, could you please retrigger it?

**Comment by fairlighteth** [comment]
@elena-zh build fixed now!

**Comment by shoom3301** [comment]
@fairlighteth it looks amazing now!
Btw, I see Tenderly simulation block is missing. Are you going to redesign it in this PR?

**Comment by fairlighteth** [comment]
@shoom3301 will be addressed in a separate PR

**Review by elena-zh — APPROVED** [review]
Hey @fairlighteth , great, thank you for improving this!

I'm approving the PR, however, I should let you know that there are still some style related issues reported in #4662: 
- [ ] 2. It would be great to add simple FE validation into the fields on the Add hook fields (plus enhance the UI of these fields)

- [ ] 5. it would be great to change colors for fields in the dark mode 
image

- [ ] 6. No bottom border radius for a hook description in a mobile view. Overall, it would be great to improve responsive views 
image

- [ ] 7. arrow to go back from a hook details is not clickable in a mobile view 
image

- [ ] 8. when I start typing into a custom hooks field, the app is auto-focused in a mobile device
image
image

- [ ] 9. General UI issues in a mobile view: 
image
image


It would be great if you take a look at them :)

**Review by alfetopito — APPROVED** [review]

**Review by shoom3301 — APPROVED** [review]

**Pull request merged**
