### PR TITLE
fix(wallets): don't request network change when connect injected wallet

### LINKED ISSUE #3541: Don't reset connection to MM when cancel network switch request
When I connect to MM, it always forces me to change the chain to the one that is selected in the CoW. If I don't want to, connection fails.
 
image
image

**Expected**: 
the connection should not fail. CoW Swap changes the network to the one in the wallet

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #3541

image

  # To Test

See #3541

### CODE REVIEW

**Comment by alfetopito** [comment]
I still got it 
image

Steps:
1. MM on gchain, app on ethereum
2. Connect
3. Accept connection
4. Reject network change
* Got the image above

**Comment by alfetopito** [comment]
Doing it a second time it worked :/ 🤷

**Review by alfetopito — APPROVED** [review]
It works, from the second time onwards.
Which is already a big win IMO, so I'm approving it.

**Review by elena-zh — APPROVED** [review]
Works great for me!

**Review by anxolin — COMMENTED** [review]
nice trick 👍

**Pull request merged**
