### PR TITLE
3023/shorten urls

### LINKED ISSUE #3023: Shorten URLs for Limit/Advanced orders
Mention https://cowservices.slack.com/archives/C0361CDG8GP/p1691505084109039

Currently, for Limit and Advanced orders there is '-orders' in the URL
It would be great to remove this lart and write simply
 - /limit/ instead of /limit-orders/
 - /advanced/ instead of /advanced-orders'

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #3023 

Shortened urls:
- `limit-orders` -> `limit`
- `advanced-orders` -> `advanced`

Added a redirect from older versions to the new ones

# To Test

1. Open the limit orders page
* Url should be `limit`
2. Change it to `limit-orders`
* It should redirect to `limit`
3. Repeat for advanced orders page

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]
Perfect!

**Review by anxolin — APPROVED** [review]

**Review by elena-zh — COMMENTED** [review]
Hey @alfetopito , great!
3 nitpicks: 
1. When I use 'limit-orders' in the URL, (or advanced-orders), I'm navigated to the correct page but the page is not highlighted on the UI
no highlight
no hightlight1
2. ubernit: it would be great to update the link in the FAQ . Btw, not related to the current PR, but the link does not respect an environment there and navigates to Prod only
nitpick
3. It would be great to update documentation after this change goes live: https://docs.cow.fi/front-end/cow-protocol-custom-linking

Thank you!

**Comment by alfetopito** [comment]
> Hey @alfetopito , great! 3 nitpicks:
> 
>     1. When I use 'limit-orders' in the URL, (or advanced-orders), I'm navigated to the correct page but the page is not highlighted on the UI
>        no highlight
>        no hightlight1
> 
>     2. ubernit: it would be great to update the link in the FAQ . Btw, not related to the current PR, but the link does not respect an environment there and navigates to Prod only
>        nitpick
> 
>     3. It would be great to update documentation after this change goes live: https://docs.cow.fi/front-end/cow-protocol-custom-linking
> 
> 
> Thank you!

@elena-zh fixed the first 2, will work on the docs now

**Comment by alfetopito** [comment]
Preview for the docs update: https://docs.cow.fi/~/changes/6pu7qZSMehqTfkcfHnuX/front-end/cow-protocol-custom-linking

**Review by elena-zh — APPROVED** [review]
Great job, Leandro!

**Pull request merged**
