### PR TITLE
Rebrand labels and improve tooltips

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Rebrand all the fee concepts as described in #3974

Adapt labels, values and tooltips for
- [x] Normal Flow
- [x] Eth Flow
- [x] Presign flow
- [x] Widget with partner fee
- [x] Widget without partner fee

## For CoW Swap
It will show 2 concepts:
- Fee: which should always be FREE as there's not protocol fee
- Total costs (the fee used for settlement) --> depending on the flow will show different information. See the TEST instructions

image

## For the Widget (if the widget adds a partner fee)
It will show 2 concepts:
- Total fee (the partner fee, if it has one)
- Total costs (the fee used for settlement) --> depending on the flow will show different information. See the TEST instructions

image

# Test

To review the label and tooltips in the following flows:

- ETH Flow: Just sell ETH or xDAI - [URL](https://swap-dev-git-fee-labels-cowswap.vercel.app/#/1/swap/WETH)
- Presign Flow: Use the Safe App- [URL](https://swap-dev-git-fee-labels-cowswap.vercel.app/#/1/swap/WETH)
- Normal Flow: Sell WETH- [URL](https://swap-dev-git-fee-labels-cowswap.vercel.app/#/1/swap/WETH)
- Gass-less approval flow: Pick a permittable token you don't have the approval for yet. Select it as sell token - [URL](https://swap-dev-git-fee-labels-cowswap.vercel.app/#/1/swap/WETH)
- Widget mode with `partnerFee` : Use configurator, pick a partner fee greater than 0 - [URL]( https://widget-configurator-git-fee-labels-cowswap.vercel.app/)
- Widget mode without `partnerFee` : Use configurator, pick a partner fee equal to 0 - [URL]( https://widget-configurator-git-fee-labels-cowswap.vercel.app/)

Make sure the Fee is correct:
- always shows `FREE` in CoW Swap
- shows `FREE` in the widget, if there's no partner fee
- shows a non zero `Total fee` for the widget when `partnerFee`

Make sure the Network Costs is correct.
- If using an EOA and normal tokens: shows the costs (our good old fee)
- If presign/eth flow, will include the +GAS label to show the fee don't include posting the order
- Tooltips are coherent and understandable, and explains the current flow

### CODE REVIEW

**Comment by MindyCoW** [comment]
image
Needs a period at the end.

**Comment by anxolin** [comment]
@MindyCoW fixed those issues. Please see the TEST notes, so you can review all flows.

image

**Review by elena-zh — COMMENTED** [review]
Hey @anxolin , great!
However, have some questions and issues here: 
1. From (incl.fee) and Receive (incl.fee): is this OK to leave 'fee' in the label and not to change it to 'cost'?
from
2. Tooltips values do not match to the new labels:
network costs
tooltip
3.  Same issue with widget tooltips:
widget tooltip
widget tooltip1
4. We show fee = Free, but our banners, error messages say 'Fees exceed'. Maybe we should change 'fees' to 'costs'?
fees on banner but costs
nwtwork costs
image

5. Also, change 'Fees' to 'Costs' in tooltips/other explanation messages on Limit orders page/order receipts (incl.TWAPs)
costs
costs1
costs 3
network costs1
lim execution price
fees receipt
fee receipt

6. TWAP says `Rate (incl.fee)`, but maybe `Rate (incl.costs)`?
twap costs

7. there is a duplicating period in the tooltip
2 periods

8. also, UI is a bit cluttered in a mobile view 
mobile


Thanks!

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Hey @shoom3301 , @anxolin , changes LGTM!

I have opened: 
1. #4011 task to update labels and tooltips on Explorer
2. #4012 task to update FAQ/About/other content pages
3. #3953 - UI task (mobile view)

@MindyCoW , could you please review the latest changes and provide your feedback on it? If needed, we will open a separate task and fix issues you will suggest in the next iteration. 

Thanks!

**Pull request merged**
