### PR TITLE
804 - Fix ETH wrap font colour

### LINKED ISSUE #804: ETH amount is not visible in the wrap my ETH section  in the dark mode
Open Cowswap app in the dark mode
Select a native token in the From field, specify an amount to sell
Select To token 

**AR**: ETH amount is not visible in the wrap my ETH section  in the dark mode

**ER**: amount should be visible

### PR DESCRIPTION
**Pull request by W3stside**
# Summary

Closes #804 

image

## TEST
1. wrap eth flow
2. check colour modes

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
👏

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @W3stside , now the account info is in black 
image
Could you please fix it?

**Comment by virgil-pastelle** [comment]
Ahha ok I'll fix it 1 sec

**Comment by W3stside** [comment]
Ahha ok I'll fix it 1 sec

**Comment by fairlighteth** [comment]
Screen Shot 2022-07-21 at 10 45 14

minor detail, for some reason the border radius isn't matching the outer container.

**Comment by elena-zh** [comment]
Hey @W3stside , now the account info is in black 
image
Could you please fix it

> Screen Shot 2022-07-21 at 10 45 14
> 
> minor detail, for some reason the border radius isn't matching the outer container.

it is also in Prod, so I can open a separate issue to address this unless  we decide to fix it here

**Review by elena-zh — APPROVED** [review]
Changes LGTM now. 
I have created a separate issue #818 to fix borders of the form in the Wrap your ETH section. 
Also, I have found another UI issue #816 related to the swap form.

**Pull request merged**
