### PR TITLE
Feature/partial fills order type tooltip

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes https://github.com/cowprotocol/cowswap/issues/2279

Updating couple of texts:

- Order type tooltip
- For consistency, updated all references to `Fill-or-kill` with `Fill or kill`
- Updated FAQ entries mentioning Partial fills were not available

image

  # To Test

1. Check order type tooltip
2. Check FAQs

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @alfetopito , great job!
However, some periods are missing on the Trading section: 
periods

**Comment by alfetopito** [comment]
> Hey @alfetopito , great job! However, some periods are missing on the Trading section: periods

Done

**Review by elena-zh — APPROVED** [review]
Approved!

**Comment by alfetopito** [comment]
Post merge review, yada yada

**Pull request merged**
