### PR TITLE
1186 - Eth-Flow - Fix issues

### LINKED ISSUE #1186: [ETH-FLOW-V2] Issues before release/1.23
From @elena-zh:

- [x] 1. It would be great to update texts and add periods to the end of sentences to modals from my previous comments. @anxolin , could you please help with this?

- [x] 2. For the cases 2, 4 in the Expert mode this issue is not fixed: 
image
- [ ] 3. 3-4 case, Expert mode: 'No need to wrap' modal blinks after the successful wrap before the Confirm Swap modal
- [x] 4. No buttons in the modals for 2, 3, 4 cases in Expert mode when Approve/Wrap transaction fails
2 case expert mode no buttons
3 case epert fails
4 case approve fails
- [ ] 5. Progress bar modal appears in the Expert mode after signing transaction (however, should be fixed in #1167)
- [ ] 6. Order of transactions for the 4 case in the exprt mode is incorrect
image
- [ ] 7. 4 case, regular mode: 'Insufficient approved' modal blinks after successfully approved transaction before the 'No need to wrap' modal. 
- [ ] 8. Incorrect token icon: https://github.com/cowprotocol/cowswap/pull/1158#issuecomment-1273195270

Thanks

_Originally posted by @elena-zh in https://github.com/cowprotocol/cowswap/issues/1158#issuecomment-1271782846_

### PR DESCRIPTION
**Pull request by W3stside**
# Summary
Closes 1-4 (core issues) of #1186 

## Note
I see that the EthFlow code is currently in `src/custom` but according to the new guidelines it should be moved into `src/cow-react` correct? In that case I will do so after this PR

I also noticed the division of the folders inside `src/cow-react/modules`. Question: should EthFlow be it's own module to keep the `hooks`, `utils` etc separate from the `swap` stuff? @anxolin 

## Checklist and screenshots
1 & 2 & 4. Punctuation: 
- [X] add periods at end of sentences
- [X] no button to retry `Wrap`, `Approve`, or `Wrap and approve` in expert mode when tx fails
- [X] insufficient approval confirmed and moves to swap modal screen

### Wrap and approve
image

### Wrap failed
image

### Approve failed
image

### Approve insufficient modal
image

### Incomplete tasks (lower prio)
 - [ ] 3. 3-4 case, Expert mode: 'No need to wrap' modal blinks after the successful wrap before the Confirm Swap modal
- [x] 5. Progress bar modal appears in the Expert mode after signing transaction (however, should be fixed in https://github.com/cowprotocol/cowswap/pull/1167)
- [ ] 6. Order of transactions for the 4 case in the exprt mode is incorrect
- [x] 7. Fourth case, regular mode: 'Insufficient approved' modal blinks after successfully approved transaction before the 'No need to wrap' modal.
- [x] 8. Incorrect token icon: https://github.com/cowprotocol/cowswap/pull/1158#issuecomment-1273195270

### CODE REVIEW

**Review by josojo — APPROVED** [review]
Nice. LGTM

**Comment by elena-zh** [comment]
Hey @W3stside , issue 2, 4 , 5, 7 are fixed in this PR. 
Issues 3, 6,  8 are not fixed, however, I vote for fixing the 8 issue as it had been fixed by @alfetopito  in #1152 PR, and the current PR will overwrite that changes :( 


Also, in the https://github.com/cowprotocol/cowswap/pull/1158#issuecomment-1268579143 in the case 3 I reported #1151 issue that ia also would be great to fix. 

Regarding the issue 1. Periods are added at the end of sentences, but there is another issue that requires text rewriting for different scenarios (this is why #1121 was created). So:
1.  scenario: _Native wrapped token is approved AND enough native wrapped token balance for swap_
 -  Regular mode: I think, it would be great to rewrite the text, as there are 2 sentences that look similar to me
image
Besides, I have not wrapped a token before, so why the modal says that I don't need to do this **any more**
image
Then, it would be great to add a sentence that a new feature is coming soon to this modal
 - Expert mode: there is no explanation at all why I see an order placement waiting modal with WETH token instead of the ETH. I think, it would be great to add a modal with an explanation

2.  scenario: _Native wrapped token is NOT approved AND enough native wrapped token balance for swap_
 - Expert mode: it would be great to explain a user why he/she approves WETH when ETH is specified in the field
image
3.  scenario: _Native wrapped token is approved AND NOT enough native wrapped token balance for swap_
 - Regular mode: there is a TODO in the modal: need to rewrite it
3 case to do!
 - Expert mode: it would be great to explain a user why he/she needs to swap with WETH 
add explanation 3 case expert

4.  scenario: _Native wrapped token is NOT approved AND NOT enough native wrapped token balance for swap_
 - Regular mode: Regular mode: there is a TODO in the modal: need to rewrite it
4 case to do
 - Expert mode:   it would be great to explain a user why he/she needs to swap and approve WETH 
4 case expert add explanation

**Review by shoom3301 — APPROVED** [review]

**Comment by anxolin** [comment]
@josojo catching up with past PRs. 
Did we agree with @elena-zh on merging this before getting her approval? 

This is something she mentioned in the past we should not. If we do, is good at least we justify in a comment why we go ahead with the merge. Otherwise we are just ignoring our Quality and Assurance if we don't follow up

**Comment by anxolin** [comment]
I keep reading PRs, I see a follow up here: https://github.com/cowprotocol/cowswap/pull/1193#issue-1408503161 

Elena, let us know if it's all good and we can have your stamp :) 

We should write before merging if we plan to do follow-up in another PR, otherwise, by reading only this PR is hard to tell if some comments were ignored or not

**Comment by josojo** [comment]
Yes, I also agree that we should always overcommunicate and state in written form where things will be addressed, or why they are not addressed.

**Comment by elena-zh** [comment]
> I keep reading PRs, I see a follow up here: [#1193 (comment)](https://github.com/cowprotocol/cowswap/pull/1193#issue-1408503161)
> 
> Elena, let us know if it's all good and we can have your stamp :)
> 
> We should write before merging if we plan to do follow-up in another PR, otherwise, by reading only this PR is hard to tell if some comments were ignored or not

Hey @anxolin , first of all, sorry about that. I really understand that it is a bit complicated to trace all following PRs and changes related to it. So in the future I will add notes and comments  to every PR in order to avoid this situation. 
As for the current PR, I added some notes to it, and issues were fixed in following PRs #1192 and #1193, afterwards all changes were merged to the main feature brunch #1121 , which has my approval with some issues. I noted it in https://github.com/cowprotocol/cowswap/pull/1121#pullrequestreview-1145582087

**Pull request merged**
