### PR TITLE
fix: remove Kleros token list because it's too big

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1734421577955559

Before:
```
allTokenListsInfoAtom:v4 5279.48046875 KB
```

After:
```
allTokenListsInfoAtom:v5 2361.544921875 KB
```

# To Test

Change network many times, the app should not crash

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Are you sure we won't miss any of those tokens. It looks like that list is updated frequently

I randomly picked two, and they were not relevant, but maybe some are?

**Comment by shoom3301** [comment]
>Are you sure we won't miss any of those tokens. It looks like that list is updated frequently

We 100% loose some tokens from this list (like you see on the picture). But since we have search using https://bff.barn.cow.fi/proxies/tokens we do not lose anything, people still can find and add them.

image

**Comment by anxolin** [comment]
> We 100% loose some tokens from this list (like you see on the picture). But since we have search using https://bff.barn.cow.fi/proxies/tokens we do not lose anything, people still can find and add them.

Technically I'm unsure if all tokens are included in BFF. We don't control the delegation to the API. Probably good to add an issue in BFF to add this token list to our future token search endpoint

**Review by elena-zh — APPROVED** [review]

**Comment by shoom3301** [comment]
>Technically I'm unsure if all tokens are included in BFF

BFF is just a proxy which uses Coingeck API

**Pull request merged**
