### PR TITLE
feat: update T&C for arb1

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

As per Legal request (see [thread](https://cowservices.slack.com/archives/C036G0J90BU/p1718631004943109))

# To Test

1. Check Terms and conditions
2. Highlighted parts should be updated (images are the old version being replaced)
image
T Cs update 1

### CODE REVIEW

**Comment by alfetopito** [comment]
Low impact change, I'm merging before review to include in the release.
Please do review post merge.

**Comment by elena-zh** [comment]
Changes LGTM!
One comment that these words differ a bit in comparison with the original text, but I assume that this is done intentionally. 
image
image

**Comment by alfetopito** [comment]
> Changes LGTM! One comment that these words differ a bit in comparison with the original text, but I assume that this is done intentionally. image image

Yes, I suggested it to Odran and he agreed to the change.

**Review by anxolin — COMMENTED** [review]
🙏

**Pull request merged**
