### PR TITLE
Updated ToC page

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

This PR updates ToC page with a new version of ToC as defined here https://docs.google.com/document/d/1xxTUoCFYnk4O0Wodqfi-WwhYGg9tTm2ayOYHuXDliLg/edit

# To test
- go to `/terms-and-conditions` page
- make sure the content is correct as defined in the doc

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @nenadV91 , great job!
Some issues I have faced: 
1. I think, it would be nice to add a link to the email that opens a mail agent with prefilled mailto address. WDYT?
call mail agent
mailto
2. 'Terms' should be in bold
termsin bold
3.  `in the “FAQ” section on the Interface.` should be  a link that navigates to the FAQ
link to faq
4. Appendix also should be the link with anchor that navigates to the Appendix
anchor
5. 'Dispute' should be in bold
dispute bold
6. Typo in the 10 paragraph:

7. I think, it would be great to make the page header height the same like on FAQ, About, other content pages. WDYT?
page name like about
image

Thanks!

**Comment by nenadV91** [comment]
@elena-zh Great comments, should be fixed now :+1:

**Comment by elena-zh** [comment]
Hey @nenadV91 , cool!
The last thing that is still missing is 'Dispute' in bold in the 17th paragraph:
disppute

Thank you!

**Review by elena-zh — APPROVED** [review]
Hey @nenadV91 , could you please make only 1 word in bold?
image
like here: 
image

All the rest changes LGTM now!

**Comment by elena-zh** [comment]
Fixed and LGTM now!

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
