### PR TITLE
feat(hooks-store): style hook store

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Consolidate general purpose styling for Hook apps
- Address comments from https://github.com/cowprotocol/cowswap/pull/4893#pullrequestreview-2309371589 

Screenshot 2024-09-17 at 14 29 56
Screenshot 2024-09-17 at 14 29 46
Screenshot 2024-09-17 at 14 29 35
Screenshot 2024-09-17 at 14 29 29

https://github.com/user-attachments/assets/25d1eb09-68fe-4de3-8458-22997b18e35a

### CODE REVIEW

**Comment by fairlighteth** [comment]
Pushed some mobile/responsive updates

**Comment by elena-zh** [comment]
Hey @fairlighteth , thank you for addressing this!
I have some trivial issues to report: 
1. It would be great to remove 'Gnosis' from the [Safe ](https://safe.global/wallet)wallet name 
Gnosis
2. It would be great to write words in the validation message in the same manner as labels are written (e.g. start with capitals, add spaces between words): 
lit
3. Arrows in the Gas limit field do not look good in the dark mode (at least, in Win11): 
arrows in the dark mode (win11)

**Review by shoom3301 — APPROVED** [review]

**Comment by shoom3301** [comment]
@elena-zh @fairlighteth I just pulled changes from develop in this branch and addressed the issues from @elena-zh .
@fairlighteth please, don't forget about commit message convention before merging this PR

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Approving, but it would be great if fields names on validation messages corresponded to the fields names 
image

image

**Pull request merged**
