### PR TITLE
fix(yield): show green banner only when vampire attack is ready

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

1. To avoid the banner state flickering, we should wait till we have all necessary data (lp balances and pools data) for its displaying.

image

2. Make APR label green only when:
 - both lp-tokens are comparable (have the same assets in the pool)
 - COW-AMM lp-token has bigger APR
image

image

# To Test

1. Open Yield widget
- [ ] the banner is not displayed
2. Wait till LP token balances are loaded
- [ ] the banner should appear

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , thanks :)

I have some questions/issues: 
1. I'd keep the banner to a not connected account 
image
Develop: 
image
2. When I change an account, I can see that the banner might be changed according to a newly connected account data. Might it be possible to hide the banner until the data is loaded?
3.I've noticed that banner shows data from a previously connected account. See: I don't have balances for these pools in the currently connected account, but the banner suggests me to swap my assets
previous account

Thanks!

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed all

**Comment by elena-zh** [comment]
Hey @shoom3301 , thank you, but the 3rd case is still here :( 
image

**Review by alfetopito — APPROVED** [review]

**Comment by shoom3301** [comment]
@elena-zh sorry, I got the problem, should be fixed now

**Comment by elena-zh** [comment]
Hey @shoom3301 , the issue is still reproducible to me :(

Now it takes a bit longer to wait till the banner is changed to a wrong one (up to 15-20 seconds), but it still happens. 

Also, case 2 from this [comment ](https://github.com/cowprotocol/cowswap/pull/5064#issuecomment-2456845638) appears to be reproducible again. See, when I connected another account the previous banner is displayed

but then it is changed to a correct one

Could you please hide the banner on 'change account' action and show it only when data is loaded?

**Comment by elena-zh** [comment]
Hey @shoom3301 , case 2 is fixed, but case 3 is still here :(
Since it is a low-prio issue and less likely will happen on Prod, I can open a separate task for this to address it later

**Review by elena-zh — APPROVED** [review]
Works now!!!

**Pull request merged**
