### PR TITLE
Logo rebranding + assets

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

Re-brands certain assets to support the brand unification:
- Updated favicon
- Updated social (link share) image
- Updated dark/light mode logos

**Please note:**
For light mode the new logo uses the same dark blue, as is currently in use in the overal COWSWAP color scheme. This is not the dark blue from the original branding kit. The idea is to update this logo/color in the UI, once the whole UI will have a make-over.

## Favicon
Screen Shot 2022-08-10 at 14 21 22

## UI
Screen Shot 2022-08-10 at 14 21 37
Screen Shot 2022-08-10 at 14 21 51

## Social share image (og tags)
og-meta-cowswap

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]
LGTM!
https://tinypng.com - would be great to optimize png using this service

**Comment by fairlighteth** [comment]
@shoom3301 For some assets I exported at lower bit color density + ran it through ImageOptim (https://imageoptim.com/mac)

**Review by alfetopito — APPROVED** [review]
looks good.

I just have to point out that the favicon icon is less visible than the previous
Screen Shot 2022-08-10 at 14 46 49

**Comment by fairlighteth** [comment]
> looks good.
> 
> I just have to point out that the favicon icon is less visible than the previous Screen Shot 2022-08-10 at 14 46 49

Yeah light vs darkmode. I think I'll need to add a background to it in that case. Thank you.

**Comment by elena-zh** [comment]
Hey @fairlighteth , nice changes!
The icon looks good especially in the dark mode. 
I connected #201 issue to the current PR as it fixes the issue as well.

Frankly, I do not like how the icon looks like in the light theme and background: for me it looks like a ghost neon cow. Can we make this light-blue color brighter a bit, or add a boarder to the icon?
light
дшпт идгу

Then, it would be great to change the icon on the appzi modals
ауувифсл
image


Maybe not related, but icon is not updated on the Join discord window, and in twitter as well.

Btw, should we update icons that are displayed on the Progress bar section?
image

And should I create a task to update icons on Explorer?

Thanks!

**Comment by fairlighteth** [comment]
@elena-zh Updated the favicon, should work better now.

Explorer.cow.fi you mean? I'm already working on. As for the progress modal, we need a task for it, I probably won't get at it today.

Appzi needs to be updated yes....I'll try to get at it tomorrow after the release (after the new brand is online). Made a note for it.

**Comment by elena-zh** [comment]
@fairlighteth , thanks!
The icon LGTM in the light mode. 
I have created a task #908 for the progress bar section.

**Review by elena-zh — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
I love the new logo.

One nitpick is the light verision color looks a bit bad with the current background. 
I see improves a bit IMO just adding more contrast 
image

Not sure if the approach above is good, or using a white version of it with a black outline is better. 

Anyways, take it only as nitpick

**Review by anxolin — APPROVED** [review]

**Pull request merged**
