### PR TITLE
Replace cow-load from gif to webp to save 18kb

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary
image

# To test
1. Check if the cow picking its nose is still displayed

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , could you please add some testing notes what I need to test here? 

Thanks!

**Comment by elena-zh** [comment]
If I understood correctly, I should check whether the nose picking cow still LGTM. 
So it looks nice. Still we have an issue with it in iOS devices (see the square boarders for it), but it is does not related to the current PR 
image

**Comment by shoom3301** [comment]
@elena-zh Thank you! You got the point right!
Also added description for testing

**Review by alfetopito — APPROVED** [review]
Looks good!

Only concern is regarding browser support.
Although, looking at https://caniuse.com/webp, ~97% of global support.
Still, would having a fallback be an option?

**Comment by shoom3301** [comment]
@alfetopito Thank you for the review!
I'm sure, crypto-folks use modern browsers :)

**Pull request merged**
