### PR TITLE
fix: address elena cow fortune style comments

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary
Addresses @elena-zh 's comments in https://github.com/cowprotocol/cowswap/pull/2361#issuecomment-1539835426

- Z-index for showing the Fortune Cookie button image similar to the Appzi button.
- Adds back a 💬 emoji in Tweet
- Fixed header for mobile on scroll, to keep the X close button sticky
- Replaced backdrop-filter: blur with a background image (not all browsers support backdrop-filter).

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , the button is lo longer displayed in modals in a mobile view. 
Also, the bg is changed and is no longer transparent. 
However, there are still some issues: 
1. quotes are hardly visible in the dark mode
slightly visible
2. Still, the cross is hidden in iOS nd truncated in Android. Besides, the modal is not scrollable in iPhone (1st time cookie opening)
image

Could you please take a look at these issues? 

Thanks!

**Review by alfetopito — COMMENTED** [review]
On Android, when the modal is displayed for the first time and the address bar is visible, it cuts half of the close button. 
When scrolling (and making the address bar disappear) the close button shows up in full

FF
signal-2023-05-09-153046

Chrome
signal-2023-05-09-153215

**Comment by fairlighteth** [comment]
@elena-zh Addressed your points, could you test on your end?

**Review by elena-zh — APPROVED** [review]
Hey @fairlighteth , LGTM now! However, my question related to the 
F' is still not clarified :)
image

@alfetopito , the button is not longer truncated from my end, could you please check it on your device?

**Review by anxolin — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
