### PR TITLE
Release/1.29.0 RC.0

### LINKED ISSUE #20: Custom slippage around 5% reverts for some values to a lower value
**Describe the bug**
When setting a custom slippage around 5% a wrong notification is shown for some values

**How to Reproduce**
1. Go to settings
2. Set custom value between 5.00 - 5.1% in 0.01% steps
4. See error for 5.02% and 5.06% - `Enter a valid slippage percentage`

**Expected behavior**
`Your transaction may be frontrun should` be shown

**Screenshots**
Bildschirmfoto 2021-04-08 um 11 02 38
Bildschirmfoto 2021-04-08 um 11 02 32
Bildschirmfoto 2021-04-08 um 11 02 47
...
Bildschirmfoto 2021-04-08 um 11 02 58

> Original issue https://github.com/gnosis/cowswap/issues/395 by @MareenG

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

- UI fixes
- Bug fixes
- EthFlow follow ups
- New Privacy Policy and Cookie Policy pages
- Updated ToC page 
- GA events simplification

## Details
```
git log --oneline v1.28.2..release/1.29.0
```
0606c13ce (HEAD -> release/1.29.0, origin/release/1.29.0) Revert "Consistent fee/numbers layout for fee tooltip (#1860)"
a69bfd0ba Additionally compare chainId in URL and in provider for trade state updates (#1867)
16b83439a Changed gchain explorer path from older `xdai` to current `gc` (#1871)
635df82c0 Add back to top button to content pages (#1890)
221a3e6bd Simplify event names (#1891)
138fe5f28 Remove gas cost label from ETH orders (#1887)
b4d8224e6 Fix issues (#1882)
d64f87620 Consistent fee/numbers layout for fee tooltip (#1860)
11689aa79 Address comments in issue (#1880)
f813687d6 Fix for wrap mode (#1877)
8394a01c5 Raplace useIsTradeUnsupported() by state from limitOrdersQuoteAtom for Limit orders (#1876)
538b5a37e Removed italic from Terms&Conditions last updated paragraph (#1875)
6cf4bde1c Merge remote-tracking branch 'origin/develop' into release/1.29.0
98ce5deee Fix scroll style (#1836)
9c2844d57 (develop) Updating domain urls (#1861)
2849ee011 Remove duplicates from inactive tokens lists in Currency search modal (#1865)
ed4cca6ac Search token by symbol and address for token importing from URL (#1857)
64cb75930 Make swap e2e tests more sustainable (#1866)
0a9e7b8db Remove duplicates from inactive tokens lists in Currency search modal (#1865)
d049a4d10 Refactor tokens list module structure (#1863)
31d020556 fix error modal footer margin (#1833)
bd66641fb Removed outdated E2E data (#1859)
dafd4db9d Merge remote-tracking branch 'origin/develop' into release/1.29.0
03a8dc4ed detect mobile/tablet by media query and not user agent (#1853)
dd7678eac Add open in metamask option on mobile (#1820)
1e8577109 Reset trade state when URL contains the same tokens with mixed case (#1856)
7955bb32e Fix tokens address usage in ImportTokenModal
d89e3a756 Fix useIsTradeUnsupported() usage
4f077301b Load fortmatic, coinbase, walletconnect and gnosis-safe wallets connectors asynchronously (-0.14MB gzip) (-1.5MB fortmatic!) (#1814)
23a3b0613 Removed usage of WrappedTokenInfo and removed redundant cycles with tokens lists (#1822)
6d7c70195 Remove tons of tokens lists recalculations by moving them to Updater (#1812)
70cc39306 Add warning when unsupported token is selected (#1714)
42287a6be fix FAQ padding (#1845)
6841fbc1e fix tooltip and txt component refactor (#1849)
ae1be16b3 fix initiating eth refund text (#1850)
9ec26c631 Do not reset page number if there are no orders to be loaded (#1843)
8db7a8ff9 Merge branch 'main' of https://github.com/cowprotocol/cowswap into develop
7d7895b0f PR comments: final changes
c837009d3 PR comments update: sender is in the outer obj
22704bb37 PR comments: more debugging as comment.sender seem empty??
0716462fa PR comments updated: one more debug log because I can't understand what's wrong
ef6d1d3e2 PR comments updates:
3723133d7 Updated pr_comments workflow:
84ed7437c Don't try to escape the event logs, it broke the summary display
96d96dae8 pr_comments updates:
7615735d2 Removed RAW_EVENT mapping. Trying just the `toJSON` version
f6f466a08 PR comments workflow (#1834)
0f8a8266d [EthFlow]#1586 progress bar starts not from 0 (#1819)
135ea87a4 Added pr_comments workflow with simple log of the whole pr comment event (#1832)
1451f5564 [EthFlow]#1586 progress bar starts not from 0 (#1819)
1c8a30924 Added pr_comments workflow with simple log of the whole pr comment event (#1832)
237b409b1 Fix modal overlay (full height) (#1830)
a7704262f Reduce bundle size by excluding unused files (#1813)
e0c6836fa Parse sell/buy amount from URL and apply to Limit orders widget (#1708)
292af9dc6 Merge remote-tracking branch 'origin/main' into develop
18affc9db Update terms icons (#1821)
bb2b82574 Fix react warning for styled-component props (#1823)
91c3d226b Update cookie policy (#1793)
62539ae66 Add new Privacy policy (#1791)
f5064f475 Use recursion to check props in genericPropsChecker() (#1817)
3a8c37142 Fix e2e tests (#1818)
e7a718ae2 1809/invalid order on orders table (#1810)
95122299a [EthFlow]#1294 - updated backend return types (#1796)
9dd972310 [EthFlow] Update cypress (#1808)
ae410b536 [EthFlow]#1787 failed sound on tx failure (#1799)
641bd19fa [EthFlow]#1445 more slippage business (#1807)
773980886 Fixed #20: JS and floats are not to be trusted (#1805)
47f598a9f [EthFlow]#1445 highligh invalid slippage (#1804)
0dc64eb5a Updated ToC page (#1789)
bda694dd3 🎨 Order table alignment: status labels (#1786)
8bef9f490 🎨 Style modals and scroll fix (#1785)
b53696f13 [EthFlow]#1294 handle failed txs (#1774)
9bc9c47ee Merge branch 'release/1.28' into develop
b3471afbb Parse sell/buy amount from URL and apply to Swap widget (#1703)
e78a15185 🎨 Rate impact styles (#1737)
65d0bd2a5 status label styling (#1748)

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
There might be a small issue https://cowservices.slack.com/archives/C0361CDG8GP/p1673546160007199

**Comment by elena-zh** [comment]
I think, it would be great to fix #1851 issue before we go live with this release

**Comment by alfetopito** [comment]
> There might be a small issue https://cowservices.slack.com/archives/C0361CDG8GP/p1673546160007199

Fix has been added to the release

**Review by elena-zh — COMMENTED** [review]
I have done with tests in this PR. 

It would be great to merge into it #1882, #1887, #1889 PRs , and address #1885 issue as it affects To amount calculation in the From/Receive tooltips. 

The list of the rest connected to the release issues can be found [here](https://github.com/cowprotocol/cowswap/issues?q=is%3Aissue+is%3Aopen+1.29).

**Review by elena-zh — APPROVED** [review]

**Review by shoom3301 — APPROVED** [review]

**Pull request merged**
