### PR TITLE
feat(twap-orders): twap orders deadline updates (8)

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

- Lots of code refactoring
- Updates the deadline selector
- Adds display for single interval time
- Adds custom selector for TWAP orders
- Adds hooks to parse predefined intervals or custom intervals to single interval time

Custom deadline selector
Screenshot 2023-05-15 at 16 52 54

Single interval time
Screenshot 2023-05-16 at 16 40 48

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @nenadV91 , could you please provide a bit more information what should and what I should NOT test here?

**Comment by nenadV91** [comment]
@elena-zh I would just test the functionality in general and if you think something is not working properly let me know.

**Comment by elena-zh** [comment]
Hey @nenadV91 , here are issues that I have faced: 
1. Sometimes the tooltip overlaps the selector, so I can't press on the time in order to open the dropdown
tooltup overlaps
2. When a part is less than 1 minute, the Part every section shows  dash. The same issue is when a part should be 1 minute and some seconds 
or when seconds
part every when less than 1 min
3. When I apply 0 minutes and 0 seconds, the dropdown shows 'Select time'. My proposal here is whether: 
 - not allow to set 0h and 0m, 
 - OR show a default value if 0h 0m is selected
0 0 - return to defaut
4. Can we convert to days/hours/minutes when we select big numbers of hours and minutes (like it is done for Part every field)?
convert to days like on parts
5. Can we keep the tooltip closer to the label in this case?
tooltip closer
6. I can copy and paste a decimal value into the field, and the value will be saved. However, pre part value will be not correct:
10 min
paste

Thank you!

**Comment by elena-zh** [comment]
Hey @nenadV91 , I have caught the app crash when I opened the Advanced orders tab 
image

**Pull request merged**
