### PR TITLE
feat: add og images for cow.fi product page

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

Adds specific OG images for the product landing pages on cow.fi

og-meta-cowswap
og-meta-mevblocker
og-meta-cowamm

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

**Review by shoom3301 — CHANGES_REQUESTED** [review]
image

@fairlighteth for some reason the image is not displayed for MEVBlocker and CoW Swap pages

**Comment by elena-zh** [comment]
Besides the issues @shoom3301 has reported above, I see 'old' images for articles (not sure if this is related to the current changes): 
image
image

**Comment by shoom3301** [comment]
🤦‍♂️ they don't work because they are not on prod yet, sorry

**Review by shoom3301 — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh the OG images for articles are taken from the 'cover' image. Fully controlled/managed in the CMS. So those articles still have the older images in their content.

**Review by elena-zh — APPROVED** [review]
Thanks for clarification!

**Pull request merged**
