### PR TITLE
[6] Adjust limit orders reiteration

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

1. Hidden est. execution price everywhere
2. Moved Limit price back on the limit orders form
3. Hidden execution time because we don't have data
4. Added back 0.1% slippage to market price

  # To Test

https://www.notion.so/cownation/Open-questions-f3d9cc8d7eda4f2e8f275225b7791adc

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!

Notes: 
1. UI issues I reported in #2077 
2. Date: it would be great to use the same date format for dates on the form and on the order confirm modals
the same date format
3. It would be great to open the menu to the left when there is not enough room for it
menu to the left
4. Link that should navigate to Etherscan/Gnosisscan is removed from the menu for Failed/Creating orders
5. When there is only 1 token is specified, it would be great to show 'Select input and output' instead of 'Price per' with empty space near Invert button
image
6. (TDB): It would be great to change the tooltip's text for the Executed Price column. @MindyCoW , could you please provide the text? 
7. Mobile OR reduces screen version: it would be nice to auto-close the menu when scroll the table to the left. So it will help to avoid this: 
image

Thanks!

**Comment by shoom3301** [comment]
@elena-zh thanks for the feedback!
1. Fixed 1 and 5 tasks. Also changed the font size for the orders context menu (made it smaller).
2. Changed the date format on the limit orders form
3. Fixed
4. Fixed
5. Fixed, also hidden the circle arrows button when both tokens are not selected
6. Will change when I receive the text from Mindy
7. It wasn't easy, but fixed :)
8. Fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
The only note is related to the #2077 issue with 5th case: the dropdown does not look good in iOS now
image
image

Could you please revert that fix so we can address it later? 

> Fixed 1 and 5 tasks, the rest can be fixed after the release. 
I would say that it would be great to take a look at 6-7 tasks there. I thin, they are important. But definitely in a separate PR. ;)

**Comment by elena-zh** [comment]
Hey @shoom3301 , thanks for fixing the dropdown boarder. 
However, I noticed that it has become narrower and glued to the right boarder
image

Can we fix this as well OR I should add it to the #2077 issue? 

Thanks

**Comment by shoom3301** [comment]
The PR was re-opened:
https://github.com/cowprotocol/cowswap/pull/2093

**Pull request merged**
