### PR TITLE
Disable appzi imtoken

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Follow up on https://github.com/cowprotocol/cowswap/pull/884

This PR disables appZI in imtoken

# To Test
Make sure imtoken browswer doesn't show appzi feedback button or NPS form

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @anxolin , changes LGTM!
However, I have to mention that now Appzi is disabled in imToken Android app as well, but it worked fine there. Can we re-enable it in Android app please? 

Thanks!

**Review by alfetopito — APPROVED** [review]
Checked imToken and I don't see it there, looks good

**Comment by anxolin** [comment]
@elena-zh can you copy and paste the message you get in your Imtoken in android if you visit https://hu1651.csb.app ?

**Comment by anxolin** [comment]
Optimistically merging

**Comment by elena-zh** [comment]
Changes LGTM!

**Pull request merged**
