### PR TITLE
General style fixes

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses open items mentioned in https://github.com/cowprotocol/cowswap/issues/3522

Screenshot 2024-02-19 at 16 40 07

https://github.com/cowprotocol/cowswap/assets/31534717/14b6e06c-a6b5-403b-9d37-4d88ab4dd20f

Screenshot 2024-02-19 at 16 35 50
Screenshot 2024-02-19 at 16 35 41

https://github.com/cowprotocol/cowswap/assets/31534717/fa397bfd-3fe6-4367-98c4-b1f210200472

https://github.com/cowprotocol/cowswap/assets/31534717/b7e2ac3b-56a6-4845-a75c-9380029610b3

Screenshot 2024-02-19 at 15 41 43
Screenshot 2024-02-19 at 15 02 53

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
looks great to me! reviewed the code, for thorough test I piggy back to Elena decision on the PR :)

**Review by shoom3301 — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!
One nitpick: still a token with no icon looks like a white circle on the Approve button in the light mode: 
broken icon
Could you please fix it? 

Thank you

**Comment by fairlighteth** [comment]
@elena-zh Did some updates:

Screenshot 2024-02-20 at 16 55 42
Screenshot 2024-02-20 at 16 55 35
Screenshot 2024-02-20 at 15 41 39
Screenshot 2024-02-20 at 15 37 34
Screenshot 2024-02-20 at 15 27 46
Screenshot 2024-02-20 at 15 27 40

**Review by elena-zh — APPROVED** [review]
Thank you, looks great now!

**Pull request merged**
