### PR TITLE
Account page (#593)

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

We can merge all Account and Header updates related PR's into this branch.

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @nenadV91 , @W3stside , 
in this PR I'm able to see token list only without 'favorite' and balances features. 
Here the list of issues I have found: 

- [ ] It would be great to reset pagination when switch between networks. To reproduce: flip several pages, change a network: you will remain on the 2-3-n page after network is changed. 
- [ ] Sometimes I can get an infinite loading effect in the table when I change networks: 
Screenshot_1

- [ ] It would be great not to reset pagination when navigate to a single token page and then go back. To reproduce: navigate to the 2nd page, open a token Sigle page, go back: you will see the 1st page in the table. 
- [ ] Could we add `<<` and `>>` arrows to the pagination? 

Thanks!

**Comment by elena-zh** [comment]
@nenadV91 , @W3stside , list of issues related to **'Favourite tokens'**

- [ ] 1. It would be great not to show OR disable 'Restore defaults' button when Favourite tokens list is not changed
- [ ] 2. When a user removes all tokens from the favourites list, the token list still shows a list of default tokens. From my perspective, the list of tokens should match in the token list window and on the Tokens page
no tokens
tokens

- [ ] 3. It would be great to make scroll in Favourites tokens in the Token list look nicer
scroll

- [ ] 4. As an enhancement, it would be great to have tokens total number (in brackets or so) for the 'Favourites' list. I think, might be useful if a user adds more than 10, and after pressing each time on a star a user stops seeing if a token is added or not to the list, as all tokens are added to the 2nd page. Maybe for 'All tokens' it would be nice to have a counter as well
image

- [ ] 5. it would be great to show tokens in the same order in a token list and on the Tokens page
order

- [ ] 6. Restore defaults button restores Favourite tokens for all networks, not only for the current one
- [ ] 7. I think it would be great to store favourites tokens not only per network, but for per account: currently, when change an account, only order of tokens is changed (weird enough). See the video: https://watch.screencastify.com/v/Ma0vuqoze7bvboVO9ktw
 Thanks

**Comment by elena-zh** [comment]
> - [ ] 2. When a user removes all tokens from the favourites list, the token list still shows a list of default tokens. From my perspective, the list of tokens should match in the token list window and on the Tokens page
no tokens
tokens

Reported a separate issue for this #663

**Comment by nenadV91** [comment]
Rebased to develop

**Comment by W3stside** [comment]
@fairlighteth the bg colours addressed here for Tokens and Affiliate

**Comment by W3stside** [comment]
merging...

**Pull request merged**
