### PR TITLE
HOTFIX 1.19.1

### PR DESCRIPTION
**Pull request by W3stside**
Remove goerli as we don't have prod API support

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
The network is not disabled when connect to a wallet and select Gorli in the conencted wallets
Screenshot_4
Besides, network selector looks different in this PR when connected to Gorli. This is how it should look like: 
image

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Looks much better!
The only think (low-prio) is when I type in  goerli into the URL param as a not connected user, the app recognizes this network
image

However, not a priority if we are going to enable the network in the near future.

**Review by elena-zh — APPROVED** [review]
Approving with an issue reported above

**Comment by elena-zh** [comment]
LGTM now!

**Pull request merged**
