### PR TITLE
[1.24] Use default values for the trade link in the main menu

### LINKED ISSUE #1325: [1.24]Show WETH token by default when navigate back from any content page
Related to #1270, #1317

1. Open Swap form 
2. Then open any Account/FAQ/other (but limit-orders) page
3. Press on the Swap menu button to go back to Swap page

**AR**: 'Select a token' is displayed in both fields

**ER**: WETH token is displayed in the From field

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1325

### CODE REVIEW

**Review by nenadV91 — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Hey @shoom3301 , changes LGTM!
As I have mentioned in https://github.com/cowprotocol/cowswap/issues/1327#issuecomment-1309972379 , now the amount is not cleared out from the Sell field when I return back to the Swap form, but it is another issue and needs discussion whether to fix this or not.

**Review by alfetopito — COMMENTED** [review]
One concern on the behaviour.
I understood the token selection and amounts would be kept when refreshing (that's the case).
I assumed it would be the same when going to a different page, but the buy token is erased:

https://user-images.githubusercontent.com/43217/201106367-833839b5-aed8-46aa-97e5-b56f45e4951d.mov

**Comment by elena-zh** [comment]
I'm also not sure if it is related to this current change or not, but I can see 'Price' filled in when I navigate from Limit order to any content page, and back to Limit orders page, however, the To token is erased. 
image

Let me know please if I need to open a separate issue for this. 

Thanks

**Comment by shoom3301** [comment]
@elena-zh @alfetopito Thanks! Fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , changes LGTM!
I will retest issue with Limit orders price in Develop, and if it there, will create a separate issue for this (and it is not a blocker for the current release).

As for the weird cases that are related to the saved amount in the Sell field, I described them in https://github.com/cowprotocol/cowswap/issues/1327#issuecomment-1309972379

Thank you!

**Pull request merged**
