### PR TITLE
feat: add click event add rpc

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

Adds click events around clicking the 'add rpc' also on success/error for the /mev-blocker page

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , thanks for implementing this!
Some issues from my side: 
1. When I reject adding the the RPC in the wallet, the event is recorded as a success
success
2. When I connect to a wallet (not yet added the rpc, just connect before adding) it also records the event as success
connect to a wallet
3. (not sure if we need to track it) there is no event on 'disconnect' wallet button click

**Comment by elena-zh** [comment]
Opened #4749 task for the issue reported above

**Review by anxolin — COMMENTED** [review]
I was able to see the click event

Screenshot at Jul 30 16-37-46


...but haven't been able to test the other events: success, error, reject, because I can get the message to pop in my Rabby wallet. Where is the injected wallet option? (or detection of rabby)

Screenshot at Jul 30 16-38-26

**Review by anxolin — APPROVED** [review]
Approving, but I think we need to iterate to upgrade the library

**Pull request merged**
