### PR TITLE
2440/uni merge

### PR DESCRIPTION
**Pull request by W3stside**
## Summary
(recreating from https://github.com/gnosis/cowswap/pull/2529)

Closes https://github.com/gnosis/cowswap/issues/2440

Merge with latest from original UNI code

PR deployment URL https://pr2536--gpswapui.review.gnosisdev.com/

### TO DOs
List of things that I know we should look at. There might be more...
- [x]  Network switcher: On hover effect
- [x]  Network switcher: No longer disabled for unsupported wallets
- [x]  connectors file might need to be updated
- [x]  useCurrency file might need to be updated
- [x]  AdvancedSwapDropdow file has been removed from original but we still have the mod
- [x]  UrlWarning file has been removed from original but we still have the mod -- we do want to keep it. [Older merge](https://github.com/gnosis/cowswap/blob/7900f01ae5b93d56bd832339c830d6636f61f28f/src/state/user/actions.ts#L37)
- [x]  Native currency on activity details has no icon because it's not tagged as native currency (eeee... address)
- [x]  Probably will need to fix integration tests...
- [x]  Locale/plurals are all screwed
- [x]  There's a component unreacheable on SwapMod
- [x]  Need to re-do useChangeNetworks based on changes from NetworkSelectorMod
- [x]  WETH/wxDAI -> USDC pair is pre-selected, but:
  - [x] Price for USDC is not loaded
  - [x] USDC is not selected on gchain
- [x]  ESlist on CI
- [x]  Loading balances via Wallet Connect is broken for some mobile wallets (MM, imToken, Token Pocket, Pillar, Argent). Worked flawlessly with Coinbase mobile wallet though
- [ ]  Identicon looking weird, need to be revisited - incoming #380 
- [ ]  Network switcher: Styles - incoming #380 
- [ ]  Widget command not starting - probably need to adjust the paths in the /lib/ files
- [ ]  Added app Suspense Loader from Uni. We might want to customize it
- [ ]  ErrorBoundary WIDGET and minor HTML changes we may want to apply
- [ ]  ListUpdatePopup file has been removed from original but we still have the mod
- [ ]  Need to understand and fix whatever rules-of-hooks is broken on SwapMod. Temporarily disabled the rule
- [ ]  Wallet connect wallet images no longer shown

### To Test
TEST EVERYTHING!!

### CODE REVIEW

**Comment by W3stside** [comment]
ah fucks sake. sorry uni team

**Comment by W3stside** [comment]
APPROVED

 (i manually opened this so cant self review)

**Comment by elena-zh** [comment]
Issued related to the current PR: 
#339 
#340 
#341 
#342 
#350 
#351 
#352

**Comment by W3stside** [comment]
> Issued related to the current PR: 
- [x] #339 
- [ ] #340 
- [ ] #341 
- [ ] #342 
- [ ] #350 
- [ ] #351 
- [ ] #352

**Comment by elena-zh** [comment]
When I press on the 'Buy COW' button, I see that 'Select token' in the From field is missing: 
image
image

**Review by alfetopito — APPROVED** [review]
Self five!

**Pull request merged**
