### PR TITLE
[1.23] Reset Swap form state when wallet disconnected

### LINKED ISSUE #1162: [1.23] Clear out the form and return it back to the default state when disconnect a wallet
The issue is reproducible both on Barn and Staging

1. Connect to a wallet
2. Specify a token pair, an amount to trade
3. Disconnect a wallet

**AR**: the form shows all specified values

**ER**: the form should be returned to the default state

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1162

Reset Swap form state on wallet disconnection

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , 
New Swap form is fixed, but 'Swap' form is not reset to the default state: 
image

**Review by elena-zh — APPROVED** [review]
However, the same issue van be found on Prod, so it is not related to the current PR. 
The current changes are approved.

**Comment by alfetopito** [comment]
Why do we want this behaviour?

Another counter example: 

I'm using metamask connected with account 1.
I filled in all fields but then realize I have no funds in this account.
I then switch to account 2.
The form is reset and my selection is wiped

--

Right now on prod/old swap the selection is kept when switching accounts and I rather keep this behaviour

**Review by anxolin — APPROVED** [review]

**Comment by alfetopito** [comment]
> @alfetopito , the issue is about clearing out the form when a wallet is disconnected (not an account is changed) to avoid this image
> 
> I can create another issue not clear out the form when an account is changed. It will be related to the New Swap form only, as on the current Swap form amounts are saved when I change accounts.

You are right, it's a different issue 👍

**Comment by elena-zh** [comment]
Hey @alfetopito and @shoom3301 
> You are right, it's a different issue 👍

I have created a separate issue #1176 for this.

**Pull request merged**
