### PR TITLE
feat: fortune cookie position fix

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Solves for a scenario where the fortune cookie overlays the orders table. Preventing a user from clicking on the 3 dot ellipsis context menu. Current situation:
Screenshot 2024-01-29 at 14 41 51

---

- The solution provided in this PR:
  - Relocates the fortune cookie
  - Adds padding so that you always have space to scroll down and see the table unobstructed
  - Forces the fortune cookie to the mobile/table footer bar

Screenshot 2024-01-29 at 13 24 28

https://github.com/cowprotocol/cowswap/assets/31534717/38c0149e-6c27-475b-bbef-a5cc8655d7aa

https://github.com/cowprotocol/cowswap/assets/31534717/699e566e-91d2-4586-9de2-e408bbe0789b

Tablet (960px viewport width and lower):
Screenshot 2024-01-29 at 14 43 43

Mobile:

https://github.com/cowprotocol/cowswap/assets/31534717/31444190-529c-4bb7-ad4c-78ed81ec5a45

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!
As a nitpick I should say that appzi icon also can overlap a limit order menu in the table. Should I open a separate issue for this? 
feedback

**Comment by fairlighteth** [comment]
But you can scroll down there, no?

**Review by anxolin — COMMENTED** [review]
Tested on different sizes, worked great to me

**Comment by elena-zh** [comment]
> But you can scroll down there, no?

I can!

**Review by shoom3301 — APPROVED** [review]

**Pull request merged**
