### PR TITLE
Release/1.46.0

### PR DESCRIPTION
**Pull request by shoom3301**
- feat(wallets): trezor wallet support
- chore: remove flaky test
- feat(trezor): control for selecting account
- fix(wallets): walletconnect v2 configuration
- chore: remove unused deps
- fix(snackbars): fix clickable area for closing
- fix(twap): rename advanced to TWAP

### CODE REVIEW

**Comment by shoom3301** [comment]
Test pan:

Smart contract wallet (Safe):
- [ ] Just swap
- [ ] Approve + swap
- [ ] Wrap + approve + swap (eth-flow)
- [ ] Wrap/unwrap
- [ ] EthFlow cancellation
- [ ] Order placement and fill (Limit/Twap)
- [ ] Hard ancel order (Swap/Limit/Twap)
- [ ] Soft cancel order (Swap/Limit/Twap)

EOA wallet (Metamask):
- [ ] Just swap
- [ ] Approve + swap
- [ ] Wrap + approve + swap (eth-flow)
- [ ] Wrap/unwrap
- [ ] EthFlow cancellation
- [ ] Order placement and fill (Limit/Twap)
- [ ] Hard ancel order (Swap/Limit/Twap)
- [ ] Soft cancel order (Swap/Limit/Twap)

WalletConnect:
- [ ] Just swap
- [ ] Approve + swap
- [ ] Wrap + approve + swap (eth-flow)
- [ ] Wrap/unwrap
- [ ] EthFlow cancellation
- [ ] Order placement and fill (Limit/Twap)
- [ ] Hard ancel order (Swap/Limit/Twap)
- [ ] Soft cancel order (Swap/Limit/Twap)

Account page
- [ ] add token to Metamask
- [ ] approve token
- [ ] COW balance displaying
- [ ] token search by name/address
- [ ] add token to Metamask
- [ ] favorite token add/remove

Common (WalletConnect/Metamask)
- [ ] network switching
- [ ] network persisting between modules
- [ ] wallet disconnect
- [ ] change wallet
- [ ] balances loading
- [ ] appzi

FAQ
- [ ] all pages open

**Comment by shoom3301** [comment]
I take **Smart contract wallet (Safe)**

**Comment by anxolin** [comment]
I take EOA wallet (Metamask)
I take Account page

**Comment by alfetopito** [comment]
I'll do `WalletConnect` v1 & v2

**Comment by alfetopito** [comment]
WalletConnect v1:

- [x] Wrap/unwrap on SWAP
- [x] Wrap/unwrap on LIMIT
- [x] Wrap/unwrap on TWAP
- [ ] Just swap
- [ ] Approve + swap
- [ ] Wrap + approve + swap (eth-flow)
- [ ] EthFlow cancellation
- [ ] Order placement and fill (LIMIT)
- [ ] Hard cancel order (SWAP/LIMIT)
- [ ] Soft cancel order (SWAP/LIMIT)

WalletConnect v1:

- [ ] Wrap/unwrap on SWAP
- [ ] Wrap/unwrap on LIMIT
- [ ] Wrap/unwrap on TWAP
- [ ] Just swap
- [ ] Approve + swap
- [ ] Wrap + approve + swap (eth-flow)
- [ ] EthFlow cancellation
- [ ] Order placement and fill (LIMIT)
- [ ] Hard cancel order (SWAP/LIMIT)
- [ ] Soft cancel order (SWAP/LIMIT)

**Pull request merged**
