### PR TITLE
release: 1.34.0

### PR DESCRIPTION
**Pull request by tukantje**
## Notable Changes

Refactoring away tons of legacy code
Refactoring of balances logics, abstract balances & new tokens module
Updated confirmation modal to show executed order details
Trust wallet
Keystone to wallets modal
Bug fixes galore - no more excessive requests 👀
Surplus executed popup
Multiple cancellations

`git log --oneline v1.33.2..v1.34.0-RC.0`

## What's Changed
* Fix/tokens page case sensitive search by @tukantje in https://github.com/cowprotocol/cowswap/pull/2235
* Ledger-live connector by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2103
* [Limit orders] Removed excessive currencyId update by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2236
* Refactor useTradeState() return type by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2242
* Updated cow-sdk that contains error parsing for getQuote() by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2241
* Fix MR comments by @tukantje in https://github.com/cowprotocol/cowswap/pull/2248
* Fix network switching detection by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2253
* Fixed wrong limit orders form state after network change by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2243
* Wallet modal UI improvements by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2201
* Add ZenGo wallet banner by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2226
* Ignore GnosisSafe NoSafeContext error by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2251
* Added keystone to wallets modal by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2249
* Added tally wallet implementation by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2191
* Added trust wallet implementation by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2198
* Don't show import if we have a token for you by @tukantje in https://github.com/cowprotocol/cowswap/pull/2260
* Disable Swap form while loading best price by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2254
* [Limit orders] Changed error text for UNHANDLED_ERROR by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2284
* Add information on minimum .env.local setup by @tukantje in https://github.com/cowprotocol/cowswap/pull/2261
* Apply back-off strategy for order-book API calls by @shoom3301 in https://github.com/cowprotocol/cowswap/pull/2288
* Surplus/executed popup by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2289
* Updated comfirmation modal to show executed order details by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2298
* Fix zero fee check to show free text by @tukantje in https://github.com/cowprotocol/cowswap/pull/2027
* Fixes some bugs with trust wallet by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2304
* Fix launch darkly env var by @alfetopito in https://github.com/cowprotocol/cowswap/pull/2315
* Refactor Balances Logics + Abstract Balances + New Tokens module by @anxolin in https://github.com/cowprotocol/cowswap/pull/2302
* Delete old code by @anxolin in https://github.com/cowprotocol/cowswap/pull/2307
* Address comments of #2302 by @anxolin in https://github.com/cowprotocol/cowswap/pull/2309
* Add retry limitations based on rawApiError by @tukantje in https://github.com/cowprotocol/cowswap/pull/2324
* Hide tally wallet for now by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2339
* Disable Ledger on Mobile by @nenadV91 in https://github.com/cowprotocol/cowswap/pull/2343

**Full Changelog**: https://github.com/cowprotocol/cowswap/compare/v1.33.2...v1.34.0-RC.0

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @tukantje , @shoom3301 , I don't see 
 - Hard cancellations #2277 with #2329 fix 
 - Multiple cancellations design #2293 
 - Multiple cancellations #2283
in this release PR. 
Should we add these features into here?

Also, as far as I can see, Tally wallet should be removed from the list of wallets (#2339 )

**Comment by tukantje** [comment]
@elena-zh https://github.com/cowprotocol/cowswap/issues/2293 I don't think this can be included since it was just a closed issue.

For the rest, I think we can include them from the looks of it. Will sync with @shoom3301.

As far as #2340, #2341 goes I'll give them a check to see if I can get them done in time, but given we are in Thursday, I'd say we should release this today to give ourselves time to see it in wild.

**Comment by elena-zh** [comment]
> @elena-zh #2293 I don't think this can be included since it was just a closed issue.

Hey @tukantje , thanks for noticing this. There was a typy in the PR number. I meant #2299

**Comment by tukantje** [comment]
Added cherry picks for these @elena-zh 

Since some of them were merged into `feature/multiple-cancellation` that cherry-pick (1e799b30f8569e1919a4ed5da3556ad92c557dc9) should cover them all.

**Comment by tukantje** [comment]
Created an RC out of this to be tested. https://github.com/cowprotocol/cowswap/releases/tag/v1.34.0-RC.0 - waiting for deployments @elena-zh

**Comment by elena-zh** [comment]
Hey @tukantje , I don't see the multiple cancellations feature in the current PR: 
image

**Comment by tukantje** [comment]
> Hey @tukantje , I don't see the multiple cancellations feature in the current PR: image But I can see hard cancellations here.

Just verified with sasha that it is in place, could it be a wrong url / not refreshed type of an issue?

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Approving with the list of issues https://github.com/cowprotocol/cowswap/issues?q=is%3Aissue+is%3Aopen+1.34

**Pull request merged**
