### PR TITLE
Add view all wallets button

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Adds "View all" button that will show all wallets that are hidden by default.

Screenshot 2023-02-24 at 10 27 28

Screenshot 2023-02-24 at 10 29 59

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @nenadV91 , nice changes!
So my notes: 
1. When I press on the button, close the modal, open it once again, the button  is not displayed again: I need to refresh the page in order to see it. Can we show it each time on opening?
2. WDYT about showing 3 options +View more option instead of 4 wallets +view more? It will make the modal more compact
3. I think, it would be great to have an option to collapse the wallet's list back once we press on the button. WDYT?
4. I think. it would be great to apply some styles to the button: hover effect, clicked state. Maybe we should apply the same styles like for the Try again button, WDYT? 
image


Thanks!

**Comment by nenadV91** [comment]
@elena-zh Great points, all should be fixed now 👍

**Comment by elena-zh** [comment]
Hey @nenadV91 , great job!!

Just some nitpicks: 
1. Can we show a collapsed modal each time on opening? Currently, if I press on View more, close the modal, open it once again, it is still expanded
2. I would change the button's name to 'Show more' and 'Show less' :)

Thank you!!

**Comment by nenadV91** [comment]
@elena-zh Should be fixed now

**Review by elena-zh — APPROVED** [review]
Great job!

**Review by shoom3301 — APPROVED** [review]

**Comment by nenadV91** [comment]
Closing in favor of new PR https://github.com/cowprotocol/cowswap/pull/2100

**Pull request closed without merging**
