### PR TITLE
Remove hover effect from the Beta label

### LINKED ISSUE #1707: Remove hover effect from the Beta label
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1670931113122089
the beta label has the underline when I hover over it
IMO it should not even be clickable

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1707

image

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @shoom3301 , I see that hover effect is removed not only from the label, but from Swap and Limit buttons 
image

Could you please return it back to the buttons, and show 'Beta' as a label, not button? 

Thanks!

**Comment by shoom3301** [comment]
@elena-zh done

**Review by elena-zh — APPROVED** [review]
Great!

**Review by fairlighteth — APPROVED** [review]
Approving so I can iterate on this.

**Pull request merged**
