### PR TITLE
feat(twap): refactor and wire price protection

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

On top of https://github.com/cowprotocol/cowswap/pull/2785

https://github.com/cowprotocol/cowswap/assets/43217/ddf31f0d-e6a5-467d-bf88-77d63aa02daf

# To Test

1. On TWAP tab, fill in order params
* Price protection should show the price minus slippage
* Clicking on price row should invert both prices

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @alfetopito , nice, thanks!
However, I don't see an amount when I'm not connected to a wallet.
image

Then, when we have 0 as an amount, maybe it is better to show 0 instead of the dash as it makes an impression that a value is a negative one? 


Could you please take a look at these issues?

**Comment by alfetopito** [comment]
> Hey @alfetopito , nice, thanks! However, I don't see an amount when I'm not connected to a wallet. image
> 
> Then, when we have 0 as an amount, maybe it is better to show 0 instead of the dash as it makes an impression that a value is a negative one? 
> 
> Could you please take a look at these issues?

Both addressed

**Review by elena-zh — APPROVED** [review]
LGTM

**Review by anxolin — COMMENTED** [review]
👍

not from this PR, but the style of the percentage should allow a few decimals. 
nit: Also, the default should be 10% not 10.0% right? 

image

Also, this is breaking if i add for example `10.12` in the slippage
image

**Pull request merged**
