### PR TITLE
Fix swap/limit container responsive styles

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Adds responsive styles for the swap/limit container

Left = this PR
Right = current `develop` 

Screenshot 2022-11-30 at 17 30 08

Screenshot 2022-11-30 at 17 35 14

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @fairlighteth , some issues from my side: 
1. Select token dropdown does not look good in a mobile view (screen width is 375 px)
swap
2. Max button is shifted to the 2nd line in mobile view (see the image above) 
3. Fields still seem cluttered in mobile view (iPhone 12 mini)
image
4. Noticed that revert price button is in white on the Order confirm modal
image
5. In general , the layout of the form is a bit different in comparison with the Prod now: in Prod it takes the whole screen width while we have a background 'boarders' in the current version
compare with prod

Could you please take a look at these issues?

Thanks

**Review by anxolin — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh 

1) Fixed. Made the font-size a tiny bit smaller and now it breaks `words` and not just on any character (break-all).
2) Fixed and re-styled the MAX button a bit.
3) Fixed
4) Fixed
5) Yes adding a bit of padding was a design choice here. Though I reduced it from 16px -> to 10px, which adds 12px to the available width.

**Comment by fairlighteth** [comment]
@elena-zh I will merge this one to expedite this. I can address any further issues in a new PR.

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!
I have created a low-prio issue #1608 that is currently on Dev, and is related to the changes introduced in the current PR.

**Pull request merged**
