### PR TITLE
Multiple cancellation design

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Figma: https://www.figma.com/file/9UJGrVP7AYtSa3M35uQPK5/2022---Limit-orders?node-id=2705-5408&t=m6wbi7WzTcBgN0h5-0

image

image

| - | - |
|--------|--------|
| image | image |

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
I like way more the new UX! this feature is great

**Comment by fairlighteth** [comment]
@elena-zh your last point 2. should be fixed in a PR (#2303) that is merged to this one.

**Comment by shoom3301** [comment]
@elena-zh 1st point was fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , case 1 looks the way better, but now there is different logic: 
1. when I press the box in the neader, it selects only orders that are displayed on the 1st page (current page). 
2. When I navigate to the 2nd page and select the rest ones, the header box behaves as expected. 
3. BUT when I press on the header box to deselect orders, it deselects all orders from both pages. From my respective, it should deselect orders only from the current page (as it is done in the 1st step). Right?

@fairlighteth , yes, thank you! Case 2 looks good now (buttons are center-aligned).

**Comment by elena-zh** [comment]
Hey @shoom3301 , some notes related to the https://github.com/cowprotocol/cowswap/pull/2283#issuecomment-1507229487

Case 5: still I can press on the cancel all button when orders are in cancelling state: 
image

Then, when I press on the cancel all orders and sign a transaction, The check in the header box is not removed. 
Actually, it can be unchecked/checked, but nothing happens in this case. 
I think, it would be nice to uncheck it, and disable it when there is nothing to select:
image


The last nitpick related to the disabled box: 
I think we need to gray out is a bit. WDYT?
disabled state - grey out

Thanks!

**Comment by shoom3301** [comment]
@elena-zh let's leave other points out of the scope of this task. You can create an issue for it, if you wish

**Review by elena-zh — APPROVED** [review]
I have created #2320 issue related to the UI of the boxes.

**Pull request merged**
