### PR TITLE
Fix network alert (only for gchain for now)

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixing network alert for gchain

## From

Screen Shot 2022-05-03 at 13 37 48
Screen Shot 2022-05-03 at 13 37 42

## To

Screen Shot 2022-05-03 at 13 26 19
Screen Shot 2022-05-03 at 13 26 13

  # To Test

1. Connect to gchain
2. Change between light/dark modes

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , nice changes!
However, I have found the issue here: the banner remains to be displayed when I switch from GC to an unsupported network
hide

I think, it would be great to hide this message when connected to an unsupported network. 

Then, I think it would be nice to add a 'hover' effect to the banner (highlight links or so). WDYT?
image

**Comment by alfetopito** [comment]
@elena-zh should be fixed, please try again once the build finishes

**Comment by elena-zh** [comment]
Hey @alfetopito , great!

However, I have noticed that only in this PR I have started to see 'Hang in here..' message when switching back from an unsupported network to a supported one. 
hang

Please, follow these steps to reproduce the issue: 
1. Connect a wallet to GC
2. Change to an aunsupported network
3. Change the networj to Ethereum --> you will see a hanging 'Hang in here' message

As for the hover effect, could we please change its color to orange as we do on the 'Profile' page for cards? 
orange

Thanks!

**Comment by alfetopito** [comment]
Hmmm, that's weird.
Locally everything is fine.
Trying it out in the PR link though I can reproduce it.
Will see what I can do.

**Comment by alfetopito** [comment]
In any way, that issue is definitely not related to the PR at hand and should be addressed separately.
I'll address your other comment regarding the orange in the link then proceed

**Comment by elena-zh** [comment]
@alfetopito , hm. I retested it in #502 PR, but it was not reproducible there. So I thought that it was related to the current PR. 
But now I have retested it again in #502 pr, and now I'm able to reproduce it there. So I have created #514 issue for this.

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Comment by alfetopito** [comment]
Merging as is, @fairlighteth feel free to post merge review

**Comment by fairlighteth** [comment]
Looks mostly good to me. One thing I noticed is a slight overlap of the Appzi button:
Screen Shot 2022-05-04 at 15 21 30

But it's something I can address at some point.

**Pull request merged**
