### PR TITLE
feat(twap): update TWAP price labels

### LINKED ISSUE #2665: Price is different from the Swap form on Mainnet
Reported in https://cowservices.slack.com/archives/C053B0162VD/p1686741790182889

1. Open Advanced orders on Develop
2. Select 1WETH to GNO (or any other token pair)
3. Make sure you have 1 part for the order
4. Check the Current Market price
5. Open Swap page
6. Select the same token pair and an amount
7. Check he price

**AR**: the price does not match

**ER**: the price should match

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Fixes #2665 

Form:
image

Review:
image

# To Test

1. On TWAP form, check the price field labels

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @alfetopito , thank you!
As one more nitpick, I'd add 'slippage' into the last field's label as it also includes it
image

**Comment by alfetopito** [comment]
> Hey @alfetopito , thank you! As one more nitpick, I'd add 'slippage' into the last field's label as it also includes it image

Done, but it does not look good IMO 
image

Hopefully it'll be better after Michel's PR

**Review by elena-zh — APPROVED** [review]
Thank you, Leandro!
I believe Michel will do his best!

**Review by shoom3301 — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
👍

**Pull request merged**
