### PR TITLE
Hotfix 1.13.2 - happy birthday 🍰 

### PR DESCRIPTION
**Pull request by alfetopito**
## DO NOT SQUASH!!! 

# Summary

- Adding an anniversary banner 🍰 
- Adding an anniversary sound 🔉 
  - On success
  - When sharing on Twitter 

# Changelog

`git log --oneline --no-decorate v1.13.1..HEAD`

eb29f1e3 Add sound (#478)
c3fca4d2 Add anniversary banner. (#475)

### CODE REVIEW

**Review by anxolin — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @alfetopito , footer elements are still displayed above the banner in a mobile view 
image

**Comment by elena-zh** [comment]
Still I see that the link is underlined on a hover effect 
image

**Comment by alfetopito** [comment]
> Hey @alfetopito , footer elements are still displayed above the banner in a mobile view image

Yep, that's still pending.
@fairlighteth is working on it.

As for the hover underline, don't think it's a big deal, we can fix if it's easy, otherwise I'm good to leave as is

**Comment by elena-zh** [comment]
Another issue I'd like to draw your attention at: Feedback button overlaps the message in mobile devices:
iPhone 12 mini, 6,7,8
image
iPhone 6,7,8 Plus, Pixel 5
image

**Comment by elena-zh** [comment]
Success sound is played on a successful convert vCOW to COW transaction. 
Are we OK with this?

**Review by elena-zh — APPROVED** [review]
approved!

**Pull request merged**
