### PR TITLE
When balance isn't loaded, show insufficient balance message

### LINKED ISSUE #451: Button to approve token appears when no token balance in the wallet
Connect to a wallet in the Ethereum Mainnet
Select a token pair, sell token with 0 balance in the wallet
Specify a token's amount to sell

**AR**: 'Allow CowSwap to use your 'token'' button appears
**There are no token balances in the fields**

**ER**: tokens' balances show 0; 'Insufficient balance' message is displayed, there is no button to approve a token's spend.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Attempts to fix #451 

To be clear, I could not reproduce, but this additional check should prevent the reported issue from happening

EDIT: Updated text to fix issue reported and to better reflect why swap can't happen
Screen Shot 2022-04-26 at 16 23 31

EDIT: Updated text to make it shorter. Now it reads `Couldn't load balances`

  # To Test

1. See #451

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , looks much better!
But it would be great not to break words when wrapping to another line in mobile views. Could you please fix it? 
image

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Review by anxolin — APPROVED** [review]

**Review by W3stside — APPROVED** [review]
dang nice cypress work, also
thank you for volunteering to be the cypress master owner! great to have ya on board

**Comment by W3stside** [comment]
@alfetopito can this go go go?

**Comment by W3stside** [comment]
merging it i want to finish this uni merge

**Pull request merged**
