### PR TITLE
🎨 Style modals and scroll fix

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Fixes https://github.com/cowprotocol/cowswap/issues/1657
- Headers on the account/order receipt are fixed on scroll

https://user-images.githubusercontent.com/31534717/208954921-47724af8-d5ef-4a81-833a-727204dd8128.mov

https://user-images.githubusercontent.com/31534717/208955011-9a9f2768-3a64-40b0-bff1-0d2f63842e6d.mov

https://user-images.githubusercontent.com/31534717/208954942-71c081bc-e048-4b7d-ac66-018e4ad4043b.mov

https://user-images.githubusercontent.com/31534717/208954969-195918d8-b38a-4991-a90d-66f03953da38.mov

  # To Test
- Open the account and order receipt modal, then test on different viewports.

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — COMMENTED** [review]
Hey @fairlighteth , great job!

I have connected #1495 issue to the current PR as it is also fixed here. 

However, I have some doubts in terms of other modals like Order Submitted, Confirm Order and Review Limit order modals. It would be also nice to enhance them. 
In addition, to fix this ugly scroll for the Review Limit order modal
confirm
order submitted
review

Can you fix these modals in the current PR or I need to create a separate issue for them? 

Thanks!

**Comment by fairlighteth** [comment]
@elena-zh I did a bunch of updates:
 - Fix the header on scroll on most modals
 - Match the styling of the switch arrow on Limit orders, with the one on the Swap page
 - Use a single uniform style for all the scrollbars

**Comment by fairlighteth** [comment]
https://user-images.githubusercontent.com/31534717/209188181-a15444d1-74db-40f1-9f5a-eaf4d46ea0ae.mov


https://user-images.githubusercontent.com/31534717/209188223-f652b2fc-0487-41f1-a6b9-c2054fc7f877.mov


https://user-images.githubusercontent.com/31534717/209188227-e9439cd3-c94c-41e9-8783-8df4b3f68afb.mov


https://user-images.githubusercontent.com/31534717/209188229-c186c546-5bdc-4bf9-bf2e-28516fc02cd4.mov

**Review by elena-zh — APPROVED** [review]
Hey @fairlighteth , changes LGTM!
I have created a separate issue for the Order Submitted modal: header is not displayed there when scroll down its content. 

Thanks!

**Pull request merged**
