### PR TITLE
Refactor ga and update custom dimensions

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

- Refactors ga a bit to make use of Uniswap setup
- Another try to fix custom dimensions with custom_map

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
I really don't get what you are suggesting to do here @nenadV91 
Do you want to kill our analytics refactoring? Its suppoused to be equivalent. Maybe only the initialization was missing, but it was centralising all the analytics logic in a single place instead of having it all over the project

Your PR undoes that, and leaves our refactored code as dead code?

**Comment by nenadV91** [comment]
@anxolin 

> Do you want to kill our analytics refactoring?

Not at all, this PR still keeps our approach with having event functions centralized in one place but also make uses of Uniswap implementation for initialization so that we can follow what they are doing and also have benefits of our approach. You can see that we still have all our event functions in `src/custom/components/anlytics/events`

**Comment by anxolin** [comment]
But i don’t get your point on why is better to make the reporter to implement the calls directly to react-ga4 library instead of delegating to our library

I refer to this comment for example:
https://github.com/cowprotocol/cowswap/pull/1006#discussion_r978002204

Aren’t we doing the same thing, but instead of having all the calls to `react-ga4` spread around the project, we have them all in `utils/analytics`

**Comment by nenadV91** [comment]
@anxolin 
Regarding the web-vitals comment that is a good point so I just did a change related to that.
All of the events are still defined in `components/analytics/events` and now we can also use the `GoogleAnalyticsProvider` class and I like that implementation

**Pull request merged**
