### PR TITLE
fix(hooks): support native currency rescuing from proxy

### LINKED ISSUE #5034: Impossible to rescue native tokens
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1729770030851169

1. I've sent a TX with buying xdai to my proxy [account](https://gnosisscan.io/tx/0x3c9b57fe897081e9034efc74af9a381f758a24ff411a2f61a32c79bd8d124a14)
2. When I connect to my wallet, go to hooks, and select xdai to rescue, it says that there is nothing to rescue
3. But it shows wxdai balance instead 

**Expected**: it should be possible to rescue native tokens

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #5034

image

# To Test

1. Send some ETH to your Shed proxy
2. Rescue the funds from Proxy using CoWSwap UI
- [ ] ER: all native tokens are transfered from Proxy to your account

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
It works, thank you!

While testing this PR I've found one more thing to improve. Reported it in #5063

**Comment by shoom3301** [comment]
@elena-zh thanks!
I've fixed the case in this PR

**Comment by elena-zh** [comment]
> @elena-zh thanks! I've fixed the case in this PR

Great, thank you!
I'm afraid, you've missed one case for wrapping and unwrapping states: 
image

**Comment by shoom3301** [comment]
@elena-zh fixed

**Comment by elena-zh** [comment]
Looks good now, thank you!

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
