### PR TITLE
feat: style safe tx + address comments

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses comments from https://github.com/cowprotocol/cowswap/pull/4808 

Screenshot 2024-08-20 at 14 17 07

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , great, thank you!

I've noticed that it is impossible to reopen Account modal when a progress bar is displayed on a real iOS device: 
1. Place an order
2. close the progress bar
3. Open Account modal
4. Press on the 'Show progress'
5. Try opening Account modal again --> impossible, progress bar is displayed
image

**Comment by alfetopito** [comment]
> Hey @fairlighteth , great, thank you!
> 
> I've noticed that it is impossible to reopen Account modal when a progress bar is displayed on a real iOS device:
> 
>     1. Place an order
> 
>     2. close the progress bar
> 
>     3. Open Account modal
> 
>     4. Press on the 'Show progress'
> 
>     5. Try opening Account modal again --> impossible, progress bar is displayed
>        image

I'll address that on my PR

**Review by elena-zh — APPROVED** [review]
Approved then!

**Review by alfetopito — APPROVED** [review]
Thanks!

**Pull request merged**
