### PR TITLE
Limit order responsive styles 2

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

Responsive orders table

https://user-images.githubusercontent.com/31534717/204794728-80c539ec-3632-4a3c-9940-d3ac42811711.mov

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , the table looks much better!

The only thing is that it is shifted to the right in mobile views:
iphone se
shifted surface

Could you please fix it?

**Comment by elena-zh** [comment]
Lower priority, but it would be nice to enhance a scrollbar in Win11 
image

**Comment by fairlighteth** [comment]
@elena-zh 
> The only thing is that it is shifted to the right in mobile views:

This should be addressed with the previous PR. I would suggest to merge and review after.

Let's create a separate issue for the WIN scrollbar. Not sure if this is something to solve for, given that's a mobile/responsive viewport dimension on Windows...

**Review by alfetopito — APPROVED** [review]

**Comment by anxolin** [comment]
I don't get any scroll bar, according to the video it has, right? 

https://pr1558--cowswap.review.gnosisdev.com/#/5/limit-orders/WETH?tab=history&page=1
image

**Comment by fairlighteth** [comment]
@anxolin It does, but starts sub < 960px width resolutions (medium). There's an in between that needs to be optimized for still.

**Comment by anxolin** [comment]
I promise I can't see them :) 

There's a scroll, but from the whole app. not like u show in the screenshots

image

**Comment by fairlighteth** [comment]
@elena-zh I committed a fix. I forgot to add/commit a 100% width (which is visible in my demo).

**Comment by elena-zh** [comment]
Hey @fairlighteth , I'm able to see the scrollbar for the table. 
And I was able to see it before. Let @anxolin checks whether it looks good to him now. 

And it also was reported above, but the table needs some optimization on the [960-1240] px screen width. Here is an issue #1551 for this

**Comment by anxolin** [comment]
Yes, now i can see it. thanks

**Pull request merged**
