### PR TITLE
Multiple order cancellations

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

image

## Changes
1. The feature is enabled only for wallets that support off-chain signing
2. The multiple cancellation menu is displayed only for the pending orders tab
3. Click on "Multiple cancellation" adds checkboxes to the orders table
4. Until zero orders are selected the "Cancel" button is disabled
5. Click on "Cancel" button opens the confirmation screen
6. "Cancel all pending orders" button cancels ALL pending orders, not only displayed on the current page
7. The checkbox in the orders table header toggles all orders on the current page

> Warning! The feature must be redesigned by @fairlighteth 

 # To Test

1. Pending modal should be displayed while a cancellation signing
2. Error modal should be displayed on any cancellation signing/send error
3. ETH-flow orders cannot be selected for multiple cancellation
4. I haven't checked edge cases, like a cancellation of 100 orders

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , something is wrong with infura in the current PR 
image

**Comment by shoom3301** [comment]
@elena-zh thank you!
Please, let's move to https://github.com/cowprotocol/cowswap/pull/2299 PR, since there are lots of changes.

1. It requires some effort, let's skip it for now
2. Fixed
3. How to reproduce it?
4. Should be fixed it https://github.com/cowprotocol/cowswap/issues/2214
5. Already fixed in #2299
6. Fixed

**Comment by shoom3301** [comment]
All changes were pushed in https://github.com/cowprotocol/cowswap/pull/2299

**Comment by elena-zh** [comment]
Hey @shoom3301 , case 3: 
 **To reproduce:** 

1. Place a market and a limit order
2. Select 2 these orders in the Your orders table to cancel
3. Call 'cancel order modal, send a TX request to the wallet, but do not sign it until the market order is executed
4. Immediately sign the TX in the wallet. 

So the signing will fail, the Filled order will be moved to the History, the number of selected orders will be still 2 on the button.

**Comment by shoom3301** [comment]
@elena-zh thanks! Let's create an issue for this case since this is edge case

**Comment by elena-zh** [comment]
Hey @shoom3301 , I have added my comments related to the current PR in https://github.com/cowprotocol/cowswap/pull/2299#issuecomment-1508359421

For the case 1 I reported #2312 issue
For the case 3 I reported #2313 issue. 

Thanks

**Pull request merged**
