### PR TITLE
Release/1.45.0

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

WIP

Mostly NX upgrade release

### CODE REVIEW

**Comment by shoom3301** [comment]
Test Safe on Goerli and Gnosis chain:
- [ ] Just swap
- [ ] Approve + swap
- [ ] Wrap + approve + swap (eth-flow)
- [ ] Wrap/unwrap
- [ ] Order placement and fill (Limit/Twap)
- [ ] Cancel order (Swap/Limit/Twap)

**Comment by alfetopito** [comment]
Tested With Metamask on Gnosis chain:
- [x] Just swap
- N/A Approve + swap
- [x] Wrap + swap (eth-flow)
- [x] EthFlow cancellation
- [x] Wrap/unwrap
- [x] Order placement and fill (Limit)
- [x] Cancel order soft/hard (Swap/Limit)

TWAP not available for EOAs

## Notes:
1. On Swap hard cancellation
- The UI (sometimes) doesn't show the status as `cancelling`, it remains `open`
- Once the cancellation tx is mined, the status changes immediately
- Still the order ended up `filled` 🤦 
- The [cancellation tx](https://gnosisscan.io/tx/0xc8b8e7afb44fecbf01f4ea601809cf0ab017d790a0fe4a0e5575cf06b7a419e1) happened the following block after the [batch settlement](https://gnosisscan.io/tx/0xf062f8dd0bc0f234d9fbfc0e8e41f701a834aa1e49460489005d9638cc4bb588)
- Tried again with another order and same thing happened, and now the [settlement tx](https://gnosisscan.io/tx/0xf1b97c7f61452416e09428f3c59d2e141969d5b4ad0d687419030baaf3e8c062) happened in the same block as the [cancellation tx](https://gnosisscan.io/tx/0x673c833f6773ae6288f01dec4ece775ebb78f0280c5de17bfbbe4cc6625ed6ae)
- Testing on goerli it worked as expected (except that it changed from open -> cancelling -> open -> cancelled)
2. Limit hard cancellation
- Like SWAP, UI (sometimes) doesn't show `cancelling` after sending the cancel tx
- Also tested on goerli because gchain was too fast

**Comment by shoom3301** [comment]
> The UI (sometimes) doesn't show the status as cancelling, it remains open
> Once the cancellation tx is mined, the status changes immediately

Elena reported it before, there should be an issue with it

**Comment by shoom3301** [comment]
Account page
- [ ] add token to Metamask
- [ ] approve token
- [ ] COW balance displaying
- [ ] token search by name/address
- [ ] add token to Metamask
- [ ] favorite token add/remove

Common (WalletConnect/Metamask)
- [ ] network switching
- [ ] network persisting between modules
- [ ] wallet disconnect
- [ ] change wallet
- [ ] balances loading

FAQ
- [ ] all pages open

**Comment by anxolin** [comment]
nit suggestion, can we call TWAP the tab instead of Advanced until we have DCA? 
https://cowservices.slack.com/archives/C036G0J90BU/p1692376011339719

**Comment by shoom3301** [comment]
@anxolin just after this release we are going to do another one, I will add this change there

**Pull request merged**
