### PR TITLE
chore: release 1.40.0

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Release 1.40.0 - Safe Eth Flow

# To Test

## Regression tests:

Make sure to test the happy path of the flows:
1. SELL and BUY orders (SWAP and LIMIT)
2. WRAP and UNWRAP (SWAP and LIMIT)
3. Cancel order (Soft and Hard) (SWAP and LIMIT)
4. Eth Flow (SWAP) (EOA only)
5. Approval bundling (SWAP and LIMIT) (Safe only)

Repeat all steps with: Injected EOA, Safe App, WC wallet

## New changes:

Refer to the testing steps in the respective PRs

1. Safe Eth Flow https://github.com/cowprotocol/cowswap/pull/2576
2. Sell all Native with Safe https://github.com/cowprotocol/cowswap/pull/2610
3. Remove `beta` label https://github.com/cowprotocol/cowswap/pull/2615

## Bug fixes: 

Refer to the testing steps in the respective PRs

1. Expired order being displayed https://github.com/cowprotocol/cowswap/pull/2558

### CODE REVIEW

**Comment by alfetopito** [comment]
I tested with Trust wallet via WC:

✅ SELL and BUY orders (SWAP and LIMIT)
🟨 WRAP and UNWRAP (SWAP and LIMIT)
Invert button on LIMIT when wrap/unwrapping does not work again

https://github.com/cowprotocol/cowswap/assets/43217/448f7ad7-eeb6-468c-99ae-b8bf44ecc099

🟨 Cancel order (Soft and Hard) (SWAP and LIMIT)
Order is marked as cancelled, then a few moments later goes back to cancelling, and then after a minute or so fully cancelled (like regular cancellations)

✅ Eth Flow (SWAP) (EOA only)
🤷 Approval bundling (SWAP and LIMIT) (Safe only)

**Review by shoom3301 — APPROVED** [review]
Test Safe:
1. Just swap
2. Approve + swap
3. Wrap + approve + swap (eth-flow)
4. Wrap/unwrap
5. Cancel order
6. Limit order creation

**Comment by alfetopito** [comment]
I tested with Safe App on Gchain:

✅ Safe Eth Flow
✅ Sell all Native with Safe
✅ Remove beta label

Will now test with Safe via WC

**Comment by alfetopito** [comment]
I tested with Safe via WC on Gchain:

✅ Safe Eth Flow (not available, shows link to Safe App as expected)
✅ Sell all Native with Safe
✅ Remove beta label

Will now test with Safe via WC

**Comment by alfetopito** [comment]
Anxo's test results https://cowservices.slack.com/archives/C0361CDG8GP/p1686135015525099

**Comment by elena-zh** [comment]
> 🟨 Cancel order (Soft and Hard) (SWAP and LIMIT) On _hard_ cancellations, both on SWAP and on LIMIT Order is marked as cancelled, then a few moments later goes back to cancelling, and then after a minute or so fully cancelled (like regular cancellations)

Hey @alfetopito , there is an issue for this #2325

**Pull request merged**
