### PR TITLE
feat: add Exodus wallet support

### PR DESCRIPTION
**Pull request by gutenye**
# Summary

We'd love to integrate Exodus wallet provider into Cowswap, thanks.

Screen Shot 2022-07-20 at 20 07 38
Screen Shot 2022-07-20 at 20 33 28

# To Test

1. Install [Exodus Browser Extension](https://www.exodus.com/browser-extension/)
2. Connect to a Wallet 
3. Select Exdous
4. Connect successfully

### CODE REVIEW

**Comment by W3stside** [comment]
hey @gutenye ! thanks for the contribution

we're currently in the process of refactoring a bit this wallet section so we'll put this on hold for now. we'll get back to you whenever possible, cheers!

**Comment by ExodusAndy** [comment]
@W3stside Hope you've been well - any update or feedback on this?

**Comment by W3stside** [comment]
> @W3stside Hope you've been well - any update or feedback on this?

Hey @ExodusAndy - so we're still discussing internally and as of now it seems likely that we will show a select few wallets on the main wallet selector comp and organise all others under an "Others" label.

The main discussion now is which wallets we will place on the front component.

Have a great week

**Comment by anxolin** [comment]
Just to add to @W3stside comment, we would need to also plan and implement the "Other" section in the modal, and we don't have capacity right now given our current priorities. 

If you want to make a proposal of adding a other section (like in a figma first) we are always happy to give feedback. Other than that, im afraid we won't be able to work on this right now

**Pull request closed without merging**
