### PR TITLE
Reposition banner in tree

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

Moves the banner up in the DOM tree, right above the Appzi button.

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @fairlighteth , I see that the banner overlaps the menu in this PR: 
image

**Comment by fairlighteth** [comment]
@elena-zh Yes that is intended. I would say this is a special purpose banner IMO allowing for it to 'take over' the app.

**Review by nenadV91 — APPROVED** [review]
Codewise LGTM :+1:

**Review by elena-zh — APPROVED** [review]
@fairlighteth , changes LGTM then!

**Pull request merged**
