### PR TITLE
fix(widget-cfg): don't request network switching with standalone mode

### LINKED ISSUE #4459: [1.70][EIP-6963] Widget+standalone: network is not changed when connected to Rabby
1. Open widget configurator
2. Select Standalone mode
3. Connect to Rabby wallet
4. Change network in the configurator 

**AR**: network is not changed in Rabby
image

**ER**: the network should be changed (like it is on Prod)
image

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #4459

Standalone mode means that widget doesn't depend on external wallet provider and works autonomously.
The "Network" field in the configurator is related only to the wallet connected in the configurator UI.

# To Test

1. Open configurator
2. Choose dapp mode and connect Metamask
3. Change network in the configurator UI
- [ ] Metamask should receive a request to switch network
4. Change mode to standalone
5. Change network in the configurator UI
- [ ] Metamask should NOT receive a request to switch network

### CODE REVIEW

**Comment by shoom3301** [comment]
@alfetopito the PR contains [chore: trigger dev build](https://github.com/cowprotocol/cowswap/pull/4463/commits/7d5dec57fe9aa7193c618e132220c9b652a7b2a7) commit but it's ok. I did it in `develop` to trigger deployment (dev was not up to date for some reason)

**Comment by alfetopito** [comment]
What about disabling the network switcher in the configurator when standalone mode is selected then, to make it clearer?

**Comment by elena-zh** [comment]
hey @shoom3301 , MM does not receive a request to change networks, but Rabby, connected to standalone mode, doe snot receive it either :( 
image

**Comment by shoom3301** [comment]
@alfetopito nice suggestion! Added it

**Comment by shoom3301** [comment]
>but Rabby, connected to standalone mode, doe snot receive it either

@elena-zh this is expected.

>Standalone mode means that widget doesn't depend on external wallet provider and works autonomously.
The "Network" field in the configurator is related only to the wallet connected in the configurator UI.

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @shoom3301  great job!
The only 1 issue I face here is that I'm not able to connect to TrusWallet extension (but I can in the release PR). Could you please check whether this issue is not on our side? 
image

**Review by elena-zh — APPROVED** [review]
The issue I've reported above appears to be not related to the current PR

**Review by anxolin — APPROVED** [review]

**Pull request merged**
