### PR TITLE
General style updates

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Consistent `theme.danger` color usage for impact and warning banners
Screenshot 2022-12-14 at 14 28 33Screenshot 2022-12-14 at 14 28 24

- Style 'no balance' warning label reported in https://github.com/cowprotocol/cowswap/issues/1524

https://user-images.githubusercontent.com/31534717/207622539-35ade1c2-6c5a-4d28-a682-d527433e173a.mov

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey  @fairlighteth , 
1. could you please add an extra-padding between Confirm button and the warning? 
image
2. Might me an edge case, but when an order is in 'Cancelling' status, and this warning added to it, the status is truncated in the table
image

Thanks!

**Review by anxolin — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh Addressed both points:
Screenshot 2022-12-14 at 17 54 16Screenshot 2022-12-14 at 17 54 24


Screenshot 2022-12-14 at 17 52 13Screenshot 2022-12-14 at 17 52 06
Screenshot 2022-12-14 at 17 51 53



Also addressed styles for the cancellation modal:
Screenshot 2022-12-14 at 17 49 40
Screenshot 2022-12-14 at 17 49 32
Screenshot 2022-12-14 at 17 49 22
Screenshot 2022-12-14 at 17 49 14

**Review by elena-zh — APPROVED** [review]
@fairlighteth , great job!
I have connected #99 issue that you fixed in the PR. 
Thank you!

**Comment by alfetopito** [comment]
Extra minor nitpick, the warning container is not horizontally aligned with the status label in the image you shared.
Take a closer look to the bottom of `cancelling` and the exclamation mark

**Comment by fairlighteth** [comment]
@alfetopito yes was fiddling with this without success. Will address in an upcoming PR!

**Pull request merged**
