### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by shoom3301**
:robot: I have created a release *beep* *boop*
---

<details><summary>cowswap: 1.95.0</summary>

### Features

* force release to release, pleaseeee ([a59eb27](https://github.com/cowprotocol/cowswap/commit/a59eb275a96fb13c9521784a051f734d947a1b1f))
</details>

<details><summary>explorer: 2.40.1</summary>

### Bug Fixes

* fix lint issues ([#5229](https://github.com/cowprotocol/cowswap/issues/5229)) ([25d30bb](https://github.com/cowprotocol/cowswap/commit/25d30bb6496a1fa51719b639948cc4d7b8ec5f20))
</details>

<details><summary>widget-configurator: 1.10.1</summary>

### Bug Fixes

* remove Kleros token list because it's too big ([#5217](https://github.com/cowprotocol/cowswap/issues/5217)) ([745e17f](https://github.com/cowprotocol/cowswap/commit/745e17f1515024f67c162091a42f3fd2864f894e))
</details>

<details><summary>cowswap-abis: 1.2.1</summary>

### Bug Fixes

* **orders-table:** display allowance warning in Safe ([#5207](https://github.com/cowprotocol/cowswap/issues/5207)) ([21e8c57](https://github.com/cowprotocol/cowswap/commit/21e8c57ddfbadb881e56295557a82ad5cb513664))
</details>

<details><summary>assets: 1.12.0</summary>

### Features

* add winter theme 🎅 ([#5213](https://github.com/cowprotocol/cowswap/issues/5213)) ([7db4b72](https://github.com/cowprotocol/cowswap/commit/7db4b72d54759394087e4c816dce9eeb6f282588))
</details>

<details><summary>common-const: 1.13.0</summary>

### Features

* add winter theme 🎅 ([#5213](https://github.com/cowprotocol/cowswap/issues/5213)) ([7db4b72](https://github.com/cowprotocol/cowswap/commit/7db4b72d54759394087e4c816dce9eeb6f282588))
</details>

<details><summary>core: 1.6.0</summary>

### Features

* **announcements:** load announcements from cms ([#5212](https://github.com/cowprotocol/cowswap/issues/5212)) ([b70703c](https://github.com/cowprotocol/cowswap/commit/b70703c7a206d5e040bbd29439dcc7eeddf72f42))
</details>

<details><summary>tokens: 1.13.1</summary>

### Bug Fixes

* remove Kleros token list because it's too big ([#5217](https://github.com/cowprotocol/cowswap/issues/5217)) ([745e17f](https://github.com/cowprotocol/cowswap/commit/745e17f1515024f67c162091a42f3fd2864f894e))
</details>

<details><summary>ui: 1.17.0</summary>

### Features

* add winter theme 🎅 ([#5213](https://github.com/cowprotocol/cowswap/issues/5213)) ([7db4b72](https://github.com/cowprotocol/cowswap/commit/7db4b72d54759394087e4c816dce9eeb6f282588))
</details>

<details><summary>wallet: 1.8.0</summary>

### Features

* **wallets:** add coinshift to allowed domains ([#4931](https://github.com/cowprotocol/cowswap/issues/4931)) ([8be3a45](https://github.com/cowprotocol/cowswap/commit/8be3a458d7918bd79c3f2bb636620c77b560f3b2))
* **wallets:** add metaMask SDK connector ([#5028](https://github.com/cowprotocol/cowswap/issues/5028)) ([fe8f376](https://github.com/cowprotocol/cowswap/commit/fe8f3767593684dc9d825d603a894c3b0934d894))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by anxolin — APPROVED** [review]

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/cowswap-v1.95.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/explorer-v2.40.1 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/widget-configurator-v1.10.1 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/cowswap-abis-v1.2.1 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/assets-v1.12.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/common-const-v1.13.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/core-v1.6.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/ui-v1.17.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/wallet-v1.8.0 :sunflower:

**Pull request merged**
