### PR TITLE
[3] fix: remove custom wallets

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Context: https://cowservices.slack.com/archives/C0369B2UF6J/p1714648983313309?thread_ts=1714384014.599879&cid=C0369B2UF6J

Removed custom logic for wallets:
1. Alpha
2. Ambire
3. Tally
4. Trust
5. Keystone

It means, we don't display separate buttons in the wallets list for them.

image

# To Test

This PR includes https://github.com/cowprotocol/cowswap/pull/4414 and https://github.com/cowprotocol/cowswap/pull/4416

1. All wallet-related functionalities: connect, disconnect, change wallet
2. All chainId features: changing chainId in the URL, in wallet, etc.
3. Add to Metamask
4. Check all supported wallets (injected, walletconnect, hardware, smart-contract)
5. Safe App integration
7. Widget integration
8. No injected providers
9. Single injected provider
10. Several injected providers
11. Mobile wallet dapp browser should be auto-connected

### CODE REVIEW

**Comment by alfetopito** [comment]
Have not checked the code yet, just the behaviour for now.

1. When I open the page, it tries to connect metamask without any action from my side.


https://github.com/cowprotocol/cowswap/assets/43217/c6eaa815-805f-4dfd-8cd9-6e894943792a


2. The app seems to think I'm connected to WC when I hover over the icon, but I'm not connected at all 
image

**Comment by shoom3301** [comment]
@alfetopito thank you! Fixed

**Comment by alfetopito** [comment]
Working nice now!

image

Caveats, which might be on the wallet side, not sure:

1. Taho is enable but doesn't show as an option
  I changed in the wallet setting to NOT be recognized as MM and it still didn't show up
image

2. Frame did not prompt the wallet 
  This one can be on the wallet side as I was not connected to the desktop app, but still, no pop up or anything 🤷 

Metamask, rabbit and coinbase worked perfectly

**Review by alfetopito — APPROVED** [review]
Awesome!

Code looks good.
I tested injected wallets and they are working mostly great. Check the other comment.
I did not try WC nor any mobile wallets/integrated wallet browsers.

**Comment by alfetopito** [comment]
Oh and check the linter.

**Comment by shoom3301** [comment]
>Taho is enable but doesn't show as an option

Because it doesn't support EIP6963

>Frame did not prompt the wallet

¯\_(ツ)_/¯

**Review by elena-zh — COMMENTED** [review]
Hey @shoom3301 , great job!

Some issues: 
1. Is this OK that  wallets order is changed, and, if enabled, Trust wallet is displayed ahead of MM and WC option? 
image
2. Broken wallet image when connect to Trezor, CoinBase (WC) options
trezor logo
екуящк дщпщ2
3. Add token feature is not working
4. Add token button should not be displayed when connected to any other wallet but MM.  Currently, it is displayed to every wallet. It should be replaced with 'Copy contract' button when connected to other wallets but MM. 
5. Also, Add token button should be replaced with 'Copy contract' when not connected to a wallet
image

6. Change wallets from MM to Rabby goes through disconnection. When follow a positive flow a user can see that MM is disconnected, then a wallet name is changed to 'Injected', and only then to 'Rabby'. IMO, all these transformations should be hidden under 'Connecting' modal
7. Change wallet from MM to Rabby: cancel the connection request in Rabby: a user appears to be disconnected. However, I'd expect a user to stay connected to MM 
change wallet disconn
8. (continuation of the case 7): when I press on the Connect to wallet button after change wallet rejection, the app does not connect to any wallet. Refreshing helps. 
9. Change wallet from MM to Trezor: the Account modal still shows MM as a connected wallet, however, the connection modal says that I'm connected to Trezor. Refreshing helps to resolve this. But it would be great to switch wallets without refreshing
MM
10. (continuation of case 9): same happens when change wallet from Rabby (or MM) to WC (Safe).  
rabby-wc
11.  When I change wallets with a network mismatch (e.g. I'm on Rabby GC, changing wallet to MM Sepolia), the app sends a request to change a network in the new wallet. If I reject it, the app does not connect to the new wallet and does not show an error, just 'Connect a wallet' modal with no terms on it. **Expected**: the app should connect to the selected network in the wallet. 
network change
netw

12. Connect to WC - Disconnect - Try connecting to WC once again: the connection fails. When I try once again, I'm finally connected, but balances are not loaded
connected!
no balances
13. Coinbase wallet in iOS: open the app in a mobile browser, Select CB option: the app navigates to the AppStore, and from there I can open installed CB wallet. IMO, it should open CB wallet without AppStore (if CB wallet is installed): 
image
image
14. When open the app in a wallet injected browser, the app is not autoconnected. In several wallets (1Inch, CB, TRUST)  'injected' is displayed instead of the wallet name. Tested in iOS
image
image
image
15. Connect to Safe walelt in iOS: wallet icon is too small: 
safe ios
15. Connect to MM, then connect to Safe (desktop) using WC. Then change an account inside the MM wallet: the app will change connection to Injected instead of Safe
safe - MM
16. I see these errors in console when select WC option for a wallet change. Is this OK?
wc
17. Widget+Standalone mode: I need to press twice on the button in order to connect to a wallet. E.g. I press for the 1st time: it may send a request to change a network in the wallet (if  a network differs). When I change the network nothing happens and I need to press on the Connect to wallet button once again. If a network matches - just to press on the 'connected to wallet' button several times. 
цшвпуе - тще сщтт
18.  Widget+Standalone mode: it says I'm connected to widget instead of the currently selected wallet (e.g. MM)
wallet name
19. Connection is not separated between Standalone and dapp modes: see, I should not be connected to dapp mode, but the preview shows that I'm connected. To reproduce: select standalone, connect to a wallet, switch to dapp. 
change mode - connected

20. (continuation of 19): when connect to dapp and standalone modes both, and switch modes, connection is changed to the same one for both modes. 
21. There is no 'Failed to copy' error when trying to connect using WC option in the standalome mode in the widget (it presents on Prod)
no copy

**Comment by shoom3301** [comment]
@elena-zh I also removed some excessive logic related Argent and Ambire wallets, specifically logic is responsible for detecting if it's a smart-contract wallet. Could you check it please as well?

**Comment by elena-zh** [comment]
Hey @shoom3301 , thank you!

Issues that I see today: 
1. Connected with Injected is displayed when I'm conencted to MM
image
2. Order of wallets is not fixed (p.1 from the previous [comment](https://github.com/cowprotocol/cowswap/pull/4420#pullrequestreview-2058732832))
image
3. Coinbase option (when extension is disabled) calls regular WC modal instead their native modal 
image
This one should be displayed 
image
4. When I close this WC modal (from the step 3), and select CB option once again, the modal hangs in the Connecting state 
image
5. I'm connected to MM. I press on the change wallet button and select Coinbase option. --> the app behaves like I'm connected to Coinbase wallet, but it is disabled in my extensions list 
image
image
6. I'm connected to Sepolia (from the previous case). I navigate to the Account page https://swap-dev-git-feat-clean-up-wallets-cowswap.vercel.app/#/account , Open Account modal, and press on the 'Change wallet', select MM --> the app requires me to swtich to Ethereum
image
When I cancel network switching request, I'm not reconnected to the new wallet.
7. Add token to Rabby is not working on Sepolia 
image
Also, not too clear to my why a token can't be added to Rabby if it exists there=) 
image
8. I can see 'Add token to Trezor' that is not working 
image
9. Change wallet from Rabby to MM when networks mismatch: the app requires to change a network in MM, otherwise it will not be connected. Currently, on Prod it picks the network that is set in a newly connected wallet. 
image
10. (continuation of 9): I cancelled network change request in MM, and the modal highlighted to me all options with connected wallets. I'd hightlight only the currently active one 
image
When I closed this modal, I appeared to be connected to MM!
11. I've been connected to Rabby/MM/Trezor and Safe WC, after tests 9-10 (above) WC option stopped to work: https://www.loom.com/share/e4d4d8e0811f48b8a3d33b3faf44224f
12. I've disconnected WC option from Safe, and initiated new conention. But the modal still shows me Rabby 
image
image
Refreshing helps.
13. I was connected with Safe(WC), then I picked MM to change the wallet. When I approved network switch in MM, I got this: 
image
14. When I switch between MM and Safe (WC), and then refresh the page this error appears in the console 
image

Thanks!

**Comment by shoom3301** [comment]
@elena-zh 
1. Fixed
2. EIP6963 doesn't guarantee an order of providers. We could hardcode some specific order, but it might be not fair and and will show that we are more inclined to certain providers. @anxolin wdyt?
3. Couldn't reproduce
4. Couldn't reproduce
5. Couldn't reproduce
6. Couldn't reproduce
7. It's ok since it Sepolia (testnet)
8. Fixed
9. Fixed
10. Couldn't reproduce (maybe because the previous point was fixed)
11. Couldn't reproduce (I guess it may happen even on prod)
12. Couldn't reproduce
13. Fixed
14. The error comes from WC side and it's specific only for Vercel. If it doesn't affect anything, please ignore it ([ref](https://github.com/orgs/WalletConnect/discussions/3442))

**Review by elena-zh — APPROVED** [review]
Approving!

For now, I've created #4451 issue related to the current PR to address it later.

**Pull request merged**
