### PR TITLE
fix(tokens): fix token lists styles

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

## 1. Modal height when token is not found

The modal should not colapse

Before:

image

After:

image

## 2. Token list context menu first item underline

The first item shouldn't be underlined by default

Before:

image

After:

image

## 3. Added margin in the tokens import results

image

## 4. Removed scrollbar from the user-added tokens list

image

### CODE REVIEW

**Review by anxolin — COMMENTED** [review]
Amazing, and thanks for the quick response.

I still see the issue with the GAS-FREE label not align. Is this done in another PR?

Also, i see this weird effect. Notice that for 1second, we filter all tokens by the text `SHIT`, it still filters out immediately the tokens, but not from the external sources. See how it still shows unrelated ones: SAND, ...

Then it creates a weird effect and replace them..

https://github.com/cowprotocol/cowswap/assets/2352112/e24d4016-abf6-40fc-b8ed-3a2753a59da4

**Review by alfetopito — COMMENTED** [review]
I still see a scroll bar in the manage tokens tab even in a looong height
image

**Comment by shoom3301** [comment]
>I still see a scroll bar in the manage tokens tab even in a looong height

@alfetopito thanks! Fixed

**Comment by shoom3301** [comment]
>I still see the issue with the GAS-FREE label not align. Is this done in another PR?

@anxolin I haven't touched it. I'm afraid it's not so simple to fix it now. @fairlighteth maybe you know how to fix it easy?

>Then it creates a weird effect and replace them..

Thanks Anxo! Fixed that

**Comment by alfetopito** [comment]
One last thing, there's no loader indicator for the external sources.
If nothing is found locally, I see `nothing found` until the external results are loaded.


https://github.com/cowprotocol/cowswap/assets/43217/d5397deb-2f21-4fd1-87cb-3b2bd986831b

**Comment by shoom3301** [comment]
>One last thing, there's no loader indicator for the external sources.

This is how it worked before (on prod), so I think we can improve it in the next release

**Comment by anxolin** [comment]
Now is better, but it shows there's no tokens... and then they appear 

https://github.com/cowprotocol/cowswap/assets/2352112/1b892501-607c-4e7d-9bc3-e21645077bdc

**Review by alfetopito — APPROVED** [review]

**Comment by shoom3301** [comment]
> Now is better, but it shows there's no tokens... and then they appear

Thanks @anxolin ! Improved this aspect

**Review by anxolin — APPROVED** [review]
Looks great now!

Some future reiteration could apply the loading only for the "additional tokens" part, since the local tokens filter is faster. But right now looks great, as long as we don't get big delays on the API that would be great. 

Wondering if we handle timeouts and errors in this API

**Comment by shoom3301** [comment]
>Wondering if we handle timeouts and errors in this API

Unfortunately we don't. I didn't have enough time to add them

**Comment by anxolin** [comment]
> Unfortunately we don't. I didn't have enough time to add them

okay, lets take note. Because potentially this, if it fails can lock the user in an infinite loading...
so we should do defensive programing with this. If the API is down or slow, we still should be able to use the local lists we have

**Pull request merged**
