### PR TITLE
feat(progress-bar-v2): missing link

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Add missing links to progress bar v2 and text related changes

# To Test

1. Check `unfilled` screen
* Cancel button should be highlighted
image
2. Check `expired` screen
image
* Place a new order should be highlighted and clicking on it re-open the swap with the same parameters (network, sell/buy tokens and amount and order type)
* Contact us should be set to `help@cow.fi`.
3. Check the link on `solving`
* Learn more should lead to https://cow.fi/learn/understanding-batch-auctions
image
4. Check the link on `solved`/`nextBatch`
* Learn more should lead to https://cow.fi/learn/understanding-batch-auctions
image

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @alfetopito , great job, thank you!

Some issues
1. 'Place a new order' link prefills the URL, but does not close the bar modal on click
not removed
2. When I close the modal with prefilled values in the URL, I see a huge amount in the sell field (my previous order was to sell 450 GNO)
huge amount
3. The link's color does not look good in the dark mode
link color
4. I'd add 'cancel' button to the 'waiting to long' state. I brought up this question [here](https://cowservices.slack.com/archives/C07BQJHK2E8/p1723478231259769). 
image

**Comment by alfetopito** [comment]
All should be fixed now @elena-zh

**Comment by alfetopito** [comment]
Consolidating to parent, will address comments if any in new PRs

**Comment by elena-zh** [comment]
Changes LGTM in the #4033 PR

**Pull request merged**
