### PR TITLE
Claim vested COW for locked GNO

### PR DESCRIPTION
**Pull request by anxolin**
# Summary
This PR adds a section to the profile page for letting users claim vested COW tokens they received for locking GNO.

# To Test

Open the page Profile

* [ ] If the connected account is eligible for vested COW from locked GNO (all addresses listed here: https://dune.xyz/bh2smith/Locked-GNO-Snapshot) it should show a section COW vesting from locked GNO
* [ ] The section should show the currently vested amount of tokens
* [ ] Users that are not eligible should not see the section

Claim the vested COW
* [ ] Click the Claim COW button, sign the transaction
* [ ] A transaction shall be added to the pending list and the user shall be notified once it completes
* [ ] The claim button should be disabled and show Successfully claimed
* [ ] The vested amount field should update to show the balance that became vested since clicking the claim button

# Background
To prevent a negative impact on page load performance, the merkle proof data for claiming the vested tokens is chunked and will be fetched lazily only when navigating to the profile page. The data can be found in this external repo: https://github.com/gnosis/locked-gno-cow-merkle-distro

> Originally created by @jfschwarz in https://github.com/gnosis/cowswap/pull/2599

### CODE REVIEW

**Comment by anxolin** [comment]
@jfschwarz note we need to recreate this PR because we are migrating all repositories. I'll add to the slack chat some details

**Comment by anxolin** [comment]
Hi, @jfschwarz , as mentioned in the chat:

- ABIs are merged, so I guess you will be able to rebase this PR and reduce drastically the number of changes
- @elena-zh will need some way to test the claims. Can we deploy a test contract so we get some way to test it?
- Let us know if the new repo or the re-creation of this PR cause you any troubles

**Comment by elena-zh** [comment]
Hey @jfschwarz , I have verified the latest changes related to the https://github.com/gnosis/cowswap/pull/2599#issuecomment-1085996831 issue, and they LGTM!

The only thing is left, is to complete test scenario and run a successful claim transaction. For this, it would great is you can deploy a test contract in Rinkeby with test accounts with locked GNO. 
If you need, I can list you several my accounts to include them into the test deployment. 
Thank you!

**Comment by elena-zh** [comment]
Hey @jfschwarz , @anxolin 
If we are adding a MOO sound when swap vCow->cow transaction is mined (implemented in #365), should we add this sound for the claiming vested COW for locked GNO successful transaction?

**Review by W3stside — APPROVED** [review]

**Comment by bh2smith** [comment]
Just wanted to point out that the dashboard won't display the amount of vested COW due to this. That computation was performed using an aggregation of the total amounts of "locked" GNO on each network and the 50M was distributed as each accounts proportion of the total. I could probably put together a query that shows this if anyone would like.

**Comment by nenadV91** [comment]
Closed in favor of https://github.com/cowprotocol/cowswap/pull/405

**Pull request closed without merging**
