### PR TITLE
fix: network setup and recipient resetting

### LINKED ISSUE #3757: Load recipient address from url when not connected
**Description**

When loading the url with the parameter `?recipient=0x...`, the recipient address is not set when there's no connected wallet.
Additionally, the network from the wallet takes precedence if you are already connected to a wallet different from that of the URL.

**How to Reproduce**

1. Without being connect/private browser window, open https://swap.cow.fi/#/100/swap/_/EURe?recipient=0x01
2. The recipient address will not be populated/set in the form

**Expected behavior**

The form with a custom recipient should be set, and the network should be changed.
The behaviour should be the same being connected or not.

**Additional context**

Reported in [this internal thread](https://cowservices.slack.com/archives/C036MD8ADMG/p1706783043710229)

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #3757

There are two fixes:
1. On the first app load, if wallet connected and wallet network doesn't match url network we should request network switching in the wallet
2. Before the fix we reset the recipient value always. But we should not do that when it set in the URL

  # To Test

1. All cases with network switching
 - wallet connected
 - wallet not connected
 - change network from UI
 - change network from URL
 - change network from Wallet
 - navigation between pages
2. Recipient value should be set if it presents in URL
3. Recipient value should be reset after page reload if it is not presented in URL

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
Works perfectly! ❤️

**Comment by elena-zh** [comment]
Question: shouldn't we switch the toggle ON as well in case of setting a recipient via URL? 
image

**Review by elena-zh — CHANGES_REQUESTED** [review]
vitalik.eth is not recognized as a valid recipient when fill in the field using the param in the link (but is valid when type in this manually) 
image

**Comment by shoom3301** [comment]
@elena-zh thank you!

1. No, I don't think so. Otherwise user will always the recipient input displayed even he never enabled it
2. Fixed
3. It would be problematic for technical perspective, I don't think it worth it
4. vitalik.eth - fixed :)

**Review by elena-zh — APPROVED** [review]
Looks good now!
Still there are some issues with URL params, I reported #3768 issue for this.

**Review by anxolin — COMMENTED** [review]
Amazing! Thanks for fixing this annoying bug!

**Pull request merged**
