### PR TITLE
Remove gas cost label from ETH orders

### LINKED ISSUE #1874: [1.29] Remove 'Gas cost = free' from ETH orders
Reported in https://cowservices.slack.com/archives/C0361CDG8GP/p1673624473344439

ETH orders tooltips show 'Gas cost = free' for ETH orders. Need to remove it

### PR DESCRIPTION
**Pull request by nenadV91**
# Summary

Fixes #1874

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey @nenadV91 , great job!
However, it would be great to remove Gas costs field from the tooltip in the order confirm modal
image

**Comment by nenadV91** [comment]
@elena-zh Great catch, should be fixed now 👍

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Comment by nenadV91** [comment]
Merging this for the release and we can do post code review

**Pull request merged**
