### PR TITLE
feat(smart-slippage): improve ux

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

## Update 2024-09-03

- Add `suggested` when smart slippage differs from user selection

Screenshot 2024-09-03 at 17 58 46

- On click, slippage value is updated to `auto`, using the smart slippage
- Add `dynamic` to slippage when it's in use (both on form and confirm modal)

Screenshot 2024-09-03 at 17 59 07
Screenshot 2024-09-03 at 17 59 38

- When user input value is same as smart value, do not show warnings

Screenshot 2024-09-03 at 17 59 20

⚠️ Texts, behaviour are still up to discussion.
⚠️ EthFlow remains as is as per Felix L opinion, to prevent too many non-refundable orders.

# Testing

1. Make sure the feature flag is on
2. Set slippage to `auto` if not already
3. Select a pair, fill in trade details
4. Expand the fee dropdown
* Slippage should be `dynamic`
5. Click on it to open the settings modal
* Should show the `dynamic` text and tooltip
6. Update it to match the exact value suggested
* `dynamic` should disappear from the form and the settings
* There should be no warnings
7. Change to a value other than the suggested percentage
* The form should show `suggested` link next to the current slippage
8. Click on it
* Should set slippage to `auto` and form should show `dynamic` next to slippage
9. On confirmation modal:
* `dynamic` should be shown when slippage set to `auto`
* not dynamic when manually set to anything else

## Original
Follow up on https://github.com/cowprotocol/cowswap/pull/4819

Quick draft to see if we can always show the default slippage and allow to reset the modified slippage with the default

image

WIP: Unsure if I will get this done before my leave

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , great job!
But here are some questions from my side: 
1. ETH flow: when I'm editing a slippage value, it is reflected on the form (see, 0 slippage is displayed). It is a UI-only issue as 0 is reset as soon as I stop editing the field (slippage will be returned back to 0.5 or 2). 
eth-flow
2. ETH-flow: when a slippage value differs from a default one, suggested option appears. Is this an expected? I thought it should not be applied to the ETH-flow. 
eth differ
3. When I manually set a value to a suggested slippage (test 6 from your list above), and then switch to the unwrapping flow, I can see 'Hight slippage amount' warning in the settings. Should we still display it? 
warning
4. When I intentionally set a slippage > than suggested, should we still show 'Suggested' option on the form? 
more
5. Looks like there are some excessive spaces between the slippage value and the suggested option 
ште
6. IMO, it would be great to explain a user WHY we suggest it. Maybe to add  a tooltip on 'Suggested' text  hover?
image
7. Again, maybe change the tooltip's text when a dynamic option is selected? 
image

Thanks!

**Comment by alfetopito** [comment]
> Hey @alfetopito , great job! But here are some questions from my side:
> 
>     1. ETH flow: when I'm editing a slippage value, it is reflected on the form (see, 0 slippage is displayed). It is a UI-only issue as 0 is reset as soon as I stop editing the field (slippage will be returned back to 0.5 or 2).
>
>        eth-flow

I don't see it as a problem, given that it'll be auto-fixed once the window is closed.
 
>     2. ETH-flow: when a slippage value differs from a default one, suggested option appears. Is this an expected? I thought it should not be applied to the ETH-flow.
>        eth differ

Indeed a bug! Fixed.

>     3. When I manually set a value to a suggested slippage (test 6 from your list above), and then switch to the unwrapping flow, I can see 'Hight slippage amount' warning in the settings. Should we still display it?
>        warning

I don't think it matters here since it doesn't apply to wrapping.

>     4. When I intentionally set a slippage > than suggested, should we still show 'Suggested' option on the form?
>        more

I think that's fine, the user might have picked a slippage that's too high to begin with.

>     5. Looks like there are some excessive spaces between the slippage value and the suggested option
>        ште

Fixed (see screen shot in the next point).

>     6. IMO, it would be great to explain a user WHY we suggest it. Maybe to add  a tooltip on 'Suggested' text  hover?
>        image

Added it 
image

>     7. Again, maybe change the tooltip's text when a dynamic option is selected?
>        image

We could but, for this we might need @MindyCoW UX powers.

**Comment by elena-zh** [comment]
Hey @alfetopito , thank you for the fixes!

Besides the tooltip (p.7), that is not up to you, everything looks great now!

Maybe only one point to say related to this: 

> > When I intentionally set a slippage > than suggested, should we still show 'Suggested' option on the form?
> I think that's fine, the user might have picked a slippage that's too high to begin with.

According to the algorithm, the highest slippage that can be applied is 2%. However, even this value may not be enough to fill a shitcoin trade. Anyways, lets see how it goes :)

**Comment by alfetopito** [comment]
I'll consolidate as is and update tooltips once I receive them from Mindy

**Pull request merged**
