### PR TITLE
Multiple cancellations: Checkbox styles

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- This PR iterates on the great PR @shoom3301 did to implement the Figma design.
- Mainly styles the checkboxes and some other layout mods

https://user-images.githubusercontent.com/31534717/231697168-2d6e2381-a700-45b0-906e-22013048bc7f.mov

https://user-images.githubusercontent.com/31534717/231697199-ca6b4b0e-c3b1-4f3b-8ff9-c9a64e2c8960.mov

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]
It looks perfect!

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!
Just 2 nitpicks: 
1. In Chrome + Win11 checkboxes look like a bit shifted 
shifted
2. It would be great to increase a tap area for the boxes in a mobile view :)

Thanks!

**Review by nenadV91 — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh Added bigger buttons for mobile/small viewports:

https://user-images.githubusercontent.com/31534717/231764801-e62df825-9236-4184-8149-0c8f9fe83d23.mov

**Review by elena-zh — APPROVED** [review]
Great job!!

**Comment by fairlighteth** [comment]
@elena-zh Thank you for the thorough checks and reviews! Merging now.

**Pull request merged**
