### PR TITLE
feat(twap): pass order class and slippage to app-data

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Added a slippage value and `orderClass=twap` to `appData`

  # To Test

1. Create a TWAP order
2. Wait until the first part is created
- [ ] Part order's app-data should contain orderClass=twap
- [ ] Part order's app-data slippage should respect the entered value

### CODE REVIEW

**Comment by elena-zh** [comment]
I can't see part's app data on explorer 
image

Also, I can't see it when I open it as a link https://cloudflare-ipfs.com/ipfs/QmcxSNSBbX8vmKR3vmeHvKZJuwkRkP33wgsYXB1VGu6ddv

But I have been able to see it in the console: 
image

**Comment by shoom3301** [comment]
@elena-zh fixed

**Review by elena-zh — APPROVED** [review]
Works great now. 
I have created a task to add this order type into Explorer's AppData page 
https://github.com/cowprotocol/explorer/issues/544

**Review by alfetopito — COMMENTED** [review]
👍

**Pull request merged**
