### PR TITLE
Release/1.24.0-RC.0

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Release candidate for `Release/1.24.0`

Main changes:
- Enabling new Swap for all environments
- New routing/urls (<network>/swap/<sell token>/<buy token>)
- Misc improvements and bug fixes
- Vercel setup (should not impact the code)

# Changelog

`git log --oneline --no-decorate HEAD...main`

ea734d030 Updated env vars with domain regex to account for: (#1285)
f719a4b62 Merge remote-tracking branch 'origin/main' into develop
f6ef7cf01 Manual prod deployment (#1269)
7dc138010 Remove old swap and related code (#1271)
d1d8b90eb Enable new swap as default and use new routing format (#1270)
0c0b63e2e Update node version (#1268)
2204aca82 Vercel setup (#1245)
a54f1d263 [Limit orders] pending and submitted modals, allowance check and approve (#1238)
c3381ba62 [Limit orders] confirm screen (#1234)
1af842f21 [Limit orders] render balances and fiat amounts (#1232)
aeb085e73 Fix: don't reset network to mainnet after page reload (#1248)
7742636fa Update Goerli cow and vcow address and merkle repo (#1265)
16be74923 [Limit orders] Initial price fetch (#1236)
b3abb3265 set pinned node 16.17.1 (#1257)
0440cb3ab Cosmos ci build (#1244)
f2f6de216 Cosmos export (#1230)
4cf3aa5e5 [New Process] - Move EthFlow & TradeSummary code to cow-react/modules/swap (#1206)
3a487c38f Fix for imported token bug (#1221)
c5b9bd2ad Fix Swap e2e test
4260149ea Fix tests (#1218)
34f2a6566 Merge branch 'main' of https://github.com/cowprotocol/cowswap into develop
22e117687 [Limit orders] store, widget, settings, rate control (#1137)
7dd981516 Merge remote-tracking branch 'origin/main' into develop
c6497fdf6 Fix tests and ignore ABIs linting (#1161)
8e22d58ec 1069/native token icons (#1152)
a6de58c9e Add webpack alias (#1145)
3518c034a Merge remote-tracking branch 'origin/main' into develop
c4f407a0e [Refactor 5] Refactor App, Routes and entry point (#1131)
8864fca76 [Refactor 4] Move ABIs (#1130)
867dbf723 Move API (#1129)
c31cbed26 [refactor 2] Create dumb Widget, Page, HelpCircle component (#1127)
5c7b10d21 [refactor 1] Move pages to cow-react (#1126)
b94c7e46e Refactor GA, fix custom dimensions and page titles (#1006)
13449e672 Keep last orderId on state when popup is closed (#974)
7e6989487 improve blocknative sdk error reporting (#1122)
365f7c8ae 1020/replace blockscout with gnosisscan (#1021)

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
I have found a list of issues related to the current release. It would be great to fix Critical and medium priority issues before the release: 

Critical: 
 - https://github.com/cowprotocol/cowswap/issues/1322
 - https://github.com/cowprotocol/cowswap/issues/1333

Medium: 
 - https://github.com/cowprotocol/cowswap/issues/1321
 - https://github.com/cowprotocol/cowswap/issues/1323
 - https://github.com/cowprotocol/cowswap/issues/1325
 - https://github.com/cowprotocol/cowswap/issues/1329

Low (would be good to take a look at them): 
  - https://github.com/cowprotocol/cowswap/issues/1327
  - https://github.com/cowprotocol/cowswap/issues/1320
  - https://github.com/cowprotocol/cowswap/issues/1215
  - https://github.com/cowprotocol/cowswap/issues/1237
  - https://github.com/cowprotocol/cowswap/issues/1330
  - https://github.com/cowprotocol/cowswap/issues/1331
  - https://github.com/cowprotocol/cowswap/issues/1318

Thanks

**Comment by anxolin** [comment]
@shoom3301 @nenadV91 pls, can we review Elenas issues and assess the severity to prepare the version?

**Comment by elena-zh** [comment]
I have retested the PR with the recent changes. Here are newly found issues and remaining ones (sorted by priority desc): 
 - https://github.com/cowprotocol/cowswap/issues/1382
 - https://github.com/cowprotocol/cowswap/issues/1381
 - https://github.com/cowprotocol/cowswap/issues/1366
 - https://github.com/cowprotocol/cowswap/issues/1323 - partially fixed in #1368 
 - https://github.com/cowprotocol/cowswap/issues/1369 - the 2nd part of the #1323 issue
 - https://github.com/cowprotocol/cowswap/issues/1380 - nice to fix
 - https://github.com/cowprotocol/cowswap/issues/1327#issuecomment-1309972379 - edge cases
 - https://github.com/cowprotocol/cowswap/issues/1329 - not a priority enhancement
Thanks

**Review by elena-zh — APPROVED** [review]
Given the fact that:
 - all critical and medium priority issues are fixed
 - I will do another round of testing on Staging

I'm approving the current PR. 

Low-priority issues that are not fixed: 
 - #1324  (exists on Prod, but exists on the PR as well)
 - #1366 (might be related to Vercel set up issue)
 - #1327 (edge cases)
 - #1329  (enhancement)
 - #1391 - issues with URL when connected to wallets that do not support network change

**Review by anxolin — APPROVED** [review]

**Pull request merged**
