### PR TITLE
fix(explorer): update explorer layout

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses the issues from https://github.com/cowprotocol/cowswap/issues/4690

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Approving with 2 nitpicks: 
1. there is different alignment for networks and contracts link on the page on a mobile resolution
image
2. there is unnecessary scroll appears when 'no orders' message is displayed 
image

**Comment by fairlighteth** [comment]
Both issues should be addressed now. From my point of view the items are aligned, although optically that may feel not to be the case:
Screenshot 2024-07-08 at 17 27 05

**Comment by elena-zh** [comment]
Hey @fairlighteth , the issue with the scroll is fixed, thank you!
Issue with alignment still does not look good to me, but we can address it a bit later
image

Also, I've opened a separate task #4694 for the moving footer issue. 
Thanks!

**Review by alfetopito — APPROVED** [review]

**Review by shoom3301 — APPROVED** [review]
Please, don't forget about https://www.conventionalcommits.org/en/v1.0.0/

**Comment by fairlighteth** [comment]
@elena-zh Addressed the text to be centered now.

**Comment by elena-zh** [comment]
@fairlighteth , looks great now. thank you!

**Pull request merged**
