### PR TITLE
Add warning when unsupported token is selected

### LINKED ISSUE #1682: [1.26]Add 'Read more' when unsupported token is selected
1. Open Limit orders page
2. Select an unsupported token into the field (AST in GC)

**AR**: there is no 'Read more' section

**ER**: it would be great to add it

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #1682 #1557

image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
1. nitpick: we show the warning to a not connected user this way on the Swap page: 
image

And this is how it is displayed on the Limit order page (no 'unsupported token' error): 
image

This is due to this issue: #1557 
So until it is implemented on the Limit orders page, maybe we should hide the banner on the Limit orders page, WDYT? 

2.  'Unsupported token' message is not displayed when there is no price/amount in the Limit orders page:
image
image

I think, these errors should be replaced with 'Unsupported token' message with no regard to a price/amount in the field. 

Thanks!

**Review by anxolin — APPROVED** [review]

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed.
1. Did as in Swap and fixed #1557 as well
2. Now we display errors first of all

**Comment by elena-zh** [comment]
Hey @shoom3301 , issues I faced: 
1. I see 'enter a price' error instead of the Unsupported token issue
unsupported
2. Approve button is glued to the Review button in the PR
button glued
3. Sell amount is too small error appears when i'm not connected. When I connect to a wallet, it remains to be displayed, even if I clear out the field: 
after conneciton
sell amount is too small
4. It would be nice to remove all error messages when tokens' amounts are 0, user is not connected, tokens are supported:
Swap form: 
image
Limit orders form:
image

Thanks!

**Comment by alfetopito** [comment]
Put on-hold due to pending issues reported and lack of capacity to address them.

**Review by alfetopito — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @shoom3301 , I have just retested the changes. 
Issues 1, 2,4 are still reproducible. As for the 3rd issue, I don't see 'Sell amount is too small error' when I connected as the token pair is reset, but I see a weird amount for the WETH token now:
amount

Could you please take a look into these issues once again?
Thanks!

**Comment by shoom3301** [comment]
@elena-zh Thanks! Fixed 1,2,4.

>As for the 3rd issue, I don't see 'Sell amount is too small error' when I connected as the token pair is reset, but I see a weird amount for the WETH token now:

I don't fully understand the problem. Anyway, it's out of the scope, if you wish you can create a separate task.

**Comment by elena-zh** [comment]
Hey @shoom3301 , great job!
The 3rd issue I reported seems to be fixed as well now due to I'm not able to reproduce it. 
I can see now only 2 issues that would be great to address: 
1. There is no 'Unsupported token' message on the Limit orders form when there are no amounts in the fields. See the comparison with the swap form: 
no amounts limit
no amounts
2. In the default state (when the 2nd token is not yet selected) it would be great to show 'Connect wallet' button instead of the 'Select token' message. See the comparison with the Swap form: 
def state swap
default state

Thanks!

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Pull request merged**
