### PR TITLE
feat(token-lists): limit token lists by 5000 tokens

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes: #3809
Context: https://cowservices.slack.com/archives/C0361CDG8GP/p1708342711821399

image

Experimentally, we figured out that after 9000 tokens the app crashes due to `localStorage` limitations.
To avoid that, I've added a limitation for token lists.
When somebody tries to add a new token list we check if the count of tokens in all token lists + list to add greater than 5000, then we display the error and don't add the list.

  # To Test

In Widget:
1. Add token lists in the configurator until you get the error

In App:
1. Add custom token lists in the token selector until you get the error

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
How do you arrived to the number 9,000 tokens?

Also, the problematic list is https://tokens.coingecko.com/uniswap/all.json
which is around 1.1 MB

Is getting under 5M our goal? 

I think there must be another issue on top we are not seeing yet. Look at this:

image


However, in this case the local storage is not the issue:

Look at the sizes, are super small:
```ts
for ( var i = 0, len = localStorage.length; i < len; ++i ) {
  const key = localStorage.key(i)
  const item = localStorage.getItem(key)
  console.log(key, Math.ceil(item.length / 1024), 'KB');
}
```

**Comment by anxolin** [comment]
@shoom3301 I think we have some duplication. I think is part of the problem (although I suspect there's more things)

If I add the token list, look at my numbers:
image

I get the 1.5 Mb list added twice

**Comment by shoom3301** [comment]
@anxolin you are right!
I've naively just copied the whole object.
Thank you so much!
The fix: https://github.com/cowprotocol/cowswap/pull/3881/commits/e108413f9e789420cf60e0281deccecc8ae527fd#diff-742ffdaa83610c8482a3c41f42f5818424b25d87b2a64d31c218f790b2bfe32dR46

**Comment by shoom3301** [comment]
>How do you arrived to the number 9,000 tokens?

https://cowservices.slack.com/archives/C0361CDG8GP/p1708343680920599?thread_ts=1708342711.821399&cid=C0361CDG8GP

**Comment by shoom3301** [comment]
@anxolin I've also added a migration to clean up the spoiled state of userAddedListsSourcesAtom:

https://github.com/cowprotocol/cowswap/pull/3881/commits/aad0b8a9b391168f5e511700f0346cb6c1896812

**Review by elena-zh — APPROVED** [review]

**Comment by anxolin** [comment]
One comment though. Coingecko has over 5K tokens. 

We suggest this list in the configurator. I would think we either increase the limit or remove that list, cause its weird we just show this error if someone checks the box: 
image

**Comment by shoom3301** [comment]
@anxolin good point, deleted this list

**Pull request merged**
