### PR TITLE
[Limit orders] pending and submitted modals

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

image

image

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Code is mostly ok but the app... is weird

I'm connected to Goerli

https://user-images.githubusercontent.com/43217/197779779-cadd59ab-7ca7-43a4-bb0a-8b95f6d2e975.mov

**Comment by shoom3301** [comment]
@alfetopito @nenadV91 already fixed it in develop

**Comment by elena-zh** [comment]
Hey @shoom3301 , some issues I have faced: 
1. No waiting modal in the Expert mode (should be)
2. As far as I understand, there[ should not be a progress bar](https://docs.google.com/document/d/1P9I4IkfsNXjyhzahhLGequaNKoGik0jP9lTO4TIBNfw/edit#heading=h.1bjj2esk7gw1) on the Order Submitted modal

**Review by alfetopito — COMMENTED** [review]
Working much better now :)

But as Elena said, there shouldn't be a progress bar for limit orders

**Comment by shoom3301** [comment]
@elena-zh fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , nice changes!
Some new issues: 
1. Waiting modal is not closed (Expert mode) when cancel/sign a transaction
not closed
2. There is a rounding issue on the waiting modal when lots of decimals are in the Sell/Buy amounts are filled in. It would be great to round amounts up to 4 decimals like we do for regular swap modals: 
rounding
to 4 decimals
3. I see a weird network indicator on the Submit modal 
netw indicator

Thanks!

**Review by alfetopito — COMMENTED** [review]
Code is ok

Behaviour, see Elena's comments, plus:

Placing the order, it failed with 400 error response
Screen Shot 2022-10-27 at 16 34 38

Now, I can't tell whether this is because the backend isn't ready or we are sending some wrong data.

Request data:

```
{
  "sellToken": "0x3430d04E42a722c5Ae52C5Bffbf1F230C2677600",
  "buyToken": "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6",
  "sellAmount": "672029386049368675562",
  "buyAmount": "672030000000000000",
  "validTo": 1666885143,
  "appData": "0x8ee89e369b514279116ab214907598c8878c4a53405097ef6c4ca4fed4cb7daf",
  "feeAmount": "118967369435510210560",
  "kind": "sell",
  "receiver": "0x5B0ABE214aB7875562ADeE331dEfF0Fe1912FE42",
  "partiallyFillable": false,
  "signingScheme": "eip712",
  "signature": "0x227b039197407d62e9e612d6aae96f74493620b589cafc02eed017d9ee59dcfe764bd382acec603cff807141ab3c7bf330ae40165977a2549181fa82594c009d1c",
  "from": "0x5B0ABE214aB7875562ADeE331dEfF0Fe1912FE42"
}
```

My current COW balance (the sell token) is of `672029386049368675562` which matches exactly the sell amount in the request.

Probably the backend? 🤷

**Comment by shoom3301** [comment]
@elena-zh 
1 - fixed
2 - fixed
3 - it will be redesigned in the future

**Comment by elena-zh** [comment]
Hey @shoom3301 , cases 1-2 LGTM!
Network indicator is also removed from the Confirm modal. 
The last nitpick is that we show full amounts on hover on a 'Placing..' modal for a regular swaps, so it would be great to add it to the Placing limit order modal as well
image

Thanks!

**Comment by shoom3301** [comment]
@elena-zh thanks! Fixed

**Pull request merged**
