### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by shoom3301**
:robot: I have created a release *beep* *boop*
---

<details><summary>cowswap: 1.77.0</summary>

### Features

* **hooks:** simulate hook transaction via Tenderly ([#4702](https://github.com/cowprotocol/cowswap/issues/4702)) ([19ee90a](https://github.com/cowprotocol/cowswap/commit/19ee90ab37638df29269bd47572898dcc94be8f4))
* **swap:** use smart slippage ([#4649](https://github.com/cowprotocol/cowswap/issues/4649)) ([ebb22ce](https://github.com/cowprotocol/cowswap/commit/ebb22cec497dfc696d32a2fd75ecc17cfd58eb41))
* update favicon icons and manifest ([#4689](https://github.com/cowprotocol/cowswap/issues/4689)) ([549bcc0](https://github.com/cowprotocol/cowswap/commit/549bcc0dea929efdb6adbffa956dac013a73c679))

### Bug Fixes

* **hooks:** link hooks page to swap trade state ([#4698](https://github.com/cowprotocol/cowswap/issues/4698)) ([bab250c](https://github.com/cowprotocol/cowswap/commit/bab250cb9888b3ec3dab422fc91fbaf23541b778))
* **limit:** clear limit output amount when price is empty ([#4678](https://github.com/cowprotocol/cowswap/issues/4678)) ([0620a9a](https://github.com/cowprotocol/cowswap/commit/0620a9a70a31687f70ec4abc6da280d54a823cb8))
* **limit:** missing price error takes precedence over missing approval ([#4693](https://github.com/cowprotocol/cowswap/issues/4693)) ([306059e](https://github.com/cowprotocol/cowswap/commit/306059ee46c57cb14bb69eb48f06aa6c85a9e4f6))
* **safe-bundle:** don't show active SWAP button unless trade is valid ([#4672](https://github.com/cowprotocol/cowswap/issues/4672)) ([1ea49ea](https://github.com/cowprotocol/cowswap/commit/1ea49ea7552ce8a314b35c9092bc234ba38fa66f))
* **trade:** display trade details when there is no usd value of costs ([#4704](https://github.com/cowprotocol/cowswap/issues/4704)) ([62e6b78](https://github.com/cowprotocol/cowswap/commit/62e6b78ea934836f709ef4a4c6ab5f817baf592a))
* vercel redirects ([#4686](https://github.com/cowprotocol/cowswap/issues/4686)) ([107ed3a](https://github.com/cowprotocol/cowswap/commit/107ed3ad74318c14ef608cd090d1086d6389426b))
</details>

<details><summary>cow-fi: 1.7.0</summary>

### Features

* sitemap.xml generating cow.fi ([#4687](https://github.com/cowprotocol/cowswap/issues/4687)) ([571bb7d](https://github.com/cowprotocol/cowswap/commit/571bb7d2fabedceb5484bf59e3c26b39de3e5717))
</details>

<details><summary>widget-configurator: 1.4.0</summary>

### Features

* update favicon icons and manifest ([#4689](https://github.com/cowprotocol/cowswap/issues/4689)) ([549bcc0](https://github.com/cowprotocol/cowswap/commit/549bcc0dea929efdb6adbffa956dac013a73c679))
</details>

<details><summary>cowswap-abis: 1.0.0</summary>

### Features

* hook store & hook Dapps 🪝 ([#4652](https://github.com/cowprotocol/cowswap/issues/4652)) ([b38321e](https://github.com/cowprotocol/cowswap/commit/b38321e0665e1ad5f0633868f8934128601ad313))
</details>

<details><summary>analytics: 1.4.0</summary>

### Features

* hook store & hook Dapps 🪝 ([#4652](https://github.com/cowprotocol/cowswap/issues/4652)) ([b38321e](https://github.com/cowprotocol/cowswap/commit/b38321e0665e1ad5f0633868f8934128601ad313))
</details>

<details><summary>assets: 1.6.0</summary>

### Features

* **hooks:** simulate hook transaction via Tenderly ([#4702](https://github.com/cowprotocol/cowswap/issues/4702)) ([19ee90a](https://github.com/cowprotocol/cowswap/commit/19ee90ab37638df29269bd47572898dcc94be8f4))
* update widget cow logo ([#4659](https://github.com/cowprotocol/cowswap/issues/4659)) ([d7d40f7](https://github.com/cowprotocol/cowswap/commit/d7d40f718012b1d4dc039c57dcbfe2070795b3e0))
</details>

<details><summary>balances-and-allowances: 1.0.0</summary>

### Bug Fixes

* **limit:** clear limit output amount when price is empty ([#4678](https://github.com/cowprotocol/cowswap/issues/4678)) ([0620a9a](https://github.com/cowprotocol/cowswap/commit/0620a9a70a31687f70ec4abc6da280d54a823cb8))
</details>

<details><summary>common-const: 1.7.0</summary>

### Features

* **swap:** use smart slippage ([#4649](https://github.com/cowprotocol/cowswap/issues/4649)) ([ebb22ce](https://github.com/cowprotocol/cowswap/commit/ebb22cec497dfc696d32a2fd75ecc17cfd58eb41))
</details>

<details><summary>common-utils: 1.5.0</summary>

### Features

* **hooks:** simulate hook transaction via Tenderly ([#4702](https://github.com/cowprotocol/cowswap/issues/4702)) ([19ee90a](https://github.com/cowprotocol/cowswap/commit/19ee90ab37638df29269bd47572898dcc94be8f4))
* **swap:** use smart slippage ([#4649](https://github.com/cowprotocol/cowswap/issues/4649)) ([ebb22ce](https://github.com/cowprotocol/cowswap/commit/ebb22cec497dfc696d32a2fd75ecc17cfd58eb41))
</details>

<details><summary>events: 1.4.0</summary>

### Features

* hook store & hook Dapps 🪝 ([#4652](https://github.com/cowprotocol/cowswap/issues/4652)) ([b38321e](https://github.com/cowprotocol/cowswap/commit/b38321e0665e1ad5f0633868f8934128601ad313))
</details>

<details><summary>types: 1.1.0</summary>

### Features

* hook store & hook Dapps 🪝 ([#4652](https://github.com/cowprotocol/cowswap/issues/4652)) ([b38321e](https://github.com/cowprotocol/cowswap/commit/b38321e0665e1ad5f0633868f8934128601ad313))
</details>

<details><summary>ui: 1.6.0</summary>

### Features

* explorer app cleanup ([#4625](https://github.com/cowprotocol/cowswap/issues/4625)) ([4148b0a](https://github.com/cowprotocol/cowswap/commit/4148b0a2f8e33d0b5d2c09a0f5eeacdb8d4eb66a))

### Bug Fixes

* **explorer:** fix almost filled orders on Explorer ([#4650](https://github.com/cowprotocol/cowswap/issues/4650)) ([fb4f593](https://github.com/cowprotocol/cowswap/commit/fb4f593d8a30f6fe3834d298178994aa9af3abf5))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/cowswap-v1.77.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/cow-fi-v1.7.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/widget-configurator-v1.4.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/cowswap-abis-v1.0.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/analytics-v1.4.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/assets-v1.6.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/common-const-v1.7.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/common-utils-v1.5.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/events-v1.4.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/types-v1.1.0 :sunflower:

**Comment by shoom3301** [comment]
:robot: Release is at https://github.com/cowprotocol/cowswap/releases/tag/ui-v1.6.0 :sunflower:

**Pull request merged**
