### PR TITLE
feat: style suspense loader

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Styles the suspense loader
- Related issue https://github.com/cowprotocol/cowswap/issues/324

https://github.com/cowprotocol/cowswap/assets/31534717/87adbbb2-d9af-4453-bde3-8a02552df3e7

https://github.com/cowprotocol/cowswap/assets/31534717/aadadf30-35d2-42ba-9737-0dc6efccfe75

https://github.com/cowprotocol/cowswap/assets/31534717/f32a943a-5c6f-4205-890a-212a15055ce4

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — COMMENTED** [review]
Hey @fairlighteth , great, thank you!
However, I think, it would be nice to remove the loader rotation due to it looks a bit weird when the cow disappears in this state 
image
From my perspective, pulsing cow should be enough :)
And it would be great to add this loader to all pages in the app (there is #324 task for this) ;)

**Review by shoom3301 — APPROVED** [review]

**Comment by fairlighteth** [comment]
@alfetopito Will review

**Comment by fairlighteth** [comment]
@alfetopito updated:

https://github.com/cowprotocol/cowswap/assets/31534717/9680a7c8-d63b-49d5-99e9-5c4ae50f46e8

**Review by elena-zh — APPROVED** [review]
LGTM!

**Comment by alfetopito** [comment]
Any risk if we point this to release @anxolin ?

**Comment by anxolin** [comment]
> Any risk if we point this to release @anxolin ?

No  risk, but I would release it as part of the normal release process with 1.43 (cc/ @shoom3301 )

**Review by anxolin — APPROVED** [review]

**Pull request merged**
