### PR TITLE
 🆕🎨 Misc styling II

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

After merging the previous bigger design update PR, I try to do quick and small PR's to keep it going as quick and efficient as possible.

- Appzi button > make more visible/less opacity
- Limit order UI layout
- Arrow separator pass a prop to toggle a horizontal line display
- Limit order UI banner styling (InfoPopup)

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!
Some my notes: 
1. Limit order page+info  page is not center-aligned on the page. 
image
image
image
image

2. Text on the infobanner is hard to read due to transparent background
image
image


Thank you!

**Comment by fairlighteth** [comment]
Fixed 2. As for 1, I made sure to add a mobile/tablet break point. Though in the current layout I have reserved space for the components that will be shown on the right. Are we planning to show this centered without components?

**Comment by fairlighteth** [comment]
@elena-zh I have centered it now in this PR.

**Review by shoom3301 — APPROVED** [review]

**Review by alfetopito — COMMENTED** [review]
Approved

**Pull request merged**
