### PR TITLE
feat: update T&C content and add ToC to policies pages

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes: #3801 

T&C content: https://docs.google.com/document/d/1ldOYHzsZBEBOdAlMV1x1dR1jwQPBdjyj87rbQZGksdo/edit#heading=h.odz557vwyozx

## What changed
1. Updated T&C content (see the link above)
2. Added table of contents to T&C, Cookie policy, Privacy policy
3. Updated `react-markdown` package
4. Refactored T&C, Cookie policy, Privacy policy pages (got rid of HTML tags due to `react-markdown` upgrade)
5. Removed "Navigating this Policy" from Privacy Policy since we have a common one

## How table of contents work
I actually inherited the component from FAQ pages and added a couple of changes:
1. Made it a bit wider for policies pages
2. Made it scrollable, because T&C content is big
3. ToC takes only `h2` tags, I did it intentionally. If I take all heading, the ToC will be enormously big.

image

image

  # To Test

1. Cookie policy page should be the same, only headings might be a bit changed
2. Privacy policy page should be the same, only headings might be a bit changed
3. T&C is updated (see the link above)

### CODE REVIEW

**Comment by shoom3301** [comment]
>Not too important, but this has a double hash in the URL, and of course don't work if we want to share. I don't think is that important in this case

@anxolin yeah, I know, this is how it used to work in FAQ section.
Anyway, I will try to fix it.

**Comment by shoom3301** [comment]
@anxolin fixed:
https://github.com/cowprotocol/cowswap/pull/3865/commits/b368034df499376d1a5ff8522a36694dac7e8d95

**Review by alfetopito — COMMENTED** [review]
There's an extra bar on the left side 
image

I see it both on Chrome and FF.
Is it intentional?

**Comment by elena-zh** [comment]
In win 11 it does not look good
image

**Comment by elena-zh** [comment]
There is a duplicating section in the Terms 
image

**Comment by shoom3301** [comment]
@elena-zh thanks!
1. Removed one
2. Made all links color blue
3. I couldn't reproduce, please ping me, let's take a look together
4. Fixed
5. Fixed
6. I'm not sure, we should ask the author of the text
7. Fixed
8. It's ok :)

**Comment by elena-zh** [comment]
Hey @shoom3301 , great!
There are some changes in the original document related to bullet points + this should not be started from a separate line (also fixed in the doc)
image
Could you please fix all these changes? 

Thanks!

**Comment by shoom3301** [comment]
@elena-zh Sure! Fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , pls, don't kill me :))
But please, add periods in the end of every listing (corresponds to the doc)
period 1
period
period2
periods

**Comment by shoom3301** [comment]
@elena-zh sure! I haven't even though about killing you :)

**Review by anxolin — APPROVED** [review]
Awesome, thanks for the fix!!! looks great

**Review by alfetopito — APPROVED** [review]

**Review by elena-zh — APPROVED** [review]
Great job!
Approving with one nitpick: this link is the only one in the text with font-weight 400 :) all the rest have 500
image

**Pull request merged**
