### PR TITLE
OrderSigningUtils for order and order cancellation signing

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

1. Added [OrderSigningUtils](https://github.com/cowprotocol/cow-sdk/pull/112) for order creation and cancellation signings
2. Removed code duplications

  # To Test

1. Create a swap
2. Create a limit order
3. Cancel an order
4. Sell ETH to anything (ETH-flow)
5. ETH-flow cancellation

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Looks simple enough 👍

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @shoom3301 , nice!
However, I can't cancel limit and market orders: 
cancel
 And it would be great to enhance an message when try to cancel already filled order:
error

Thanks!

**Comment by shoom3301** [comment]
@elena-zh fixed

**Comment by elena-zh** [comment]
Hey @shoom3301 , the 2nd my comment it not fixed. 
image

But I can create a separate issue for this. Please let me know. 

Thanks

**Comment by shoom3301** [comment]
@elena-zh we receive the text from backend. Anyway, how did you get the error? It shouldn't be reproducible

**Comment by elena-zh** [comment]
> @elena-zh we receive the text from backend. Anyway, how did you get the error? It shouldn't be reproducible

It was always reproducible as an edge case. 
'Filled' notifications come with a delay, so sometimes when an order is already filled, and a user tries to cancel it, this notification appear. 
**To reproduce:** 

1. Place an order
2. Call 'cancel order modal, send a TX request to the wallet, but do not sign it until you hear the Moo sound
3. Immediately sign the TX in the wallet.

**Comment by shoom3301** [comment]
@elena-zh please, create a separate issue for it

**Pull request merged**
