### PR TITLE
feat: make widget to use all space

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

To show the widget, it would be nice to allow to show two version:
* Small responsive: We show it with a width of`450px`
* Big!: Will use as much space as available

For example, for limit orders, instead of:
image

Now it tries to use all the space:

https://github.com/cowprotocol/cowswap/assets/2352112/db090d80-3259-491f-81cc-77a248207169

## Not included
It would be great to give an option on how to select Small/Big options. @fairlighteth how is best to show this control?

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

**Comment by elena-zh** [comment]
Hey @anxolin , is this intended to see this widget width when open it separately in a browser? 
load
Screenshot_3

Actually, this happens when I load the app inside the safe as well 
image

**Review by alfetopito — APPROVED** [review]

**Comment by anxolin** [comment]
> Hey @anxolin , is this intended to see this widget width when open it separately in a browser?

not intended...


I don't get how you broke it 😭

image

**Review by elena-zh — APPROVED** [review]
Hey @anxolin , I'm not able to catch this 'tiny width' issue I faced :(
And now the changes LGTM besides 1 nitpick: when the app is loading, a 'loader' area is also occupying the whole page's width 
image
LMK please if I need to open a separate issue for this.

**Comment by anxolin** [comment]
> Hey @anxolin , I'm not able to catch this 'tiny width' issue I faced :(
And now the changes LGTM besides 1 nitpick: when the app is loading, a 'loader' area is also occupying the whole page's width

Cool! thanks for re-checking. Then I think I will merge this into the re-lease. 

For the loading issue, I'm not sure is something to fix, I would think we want to also take all the space for this case. No? 
If you really think is bad, feel free to create the issue, otherwise we can leave it like this

**Pull request merged**
