### PR TITLE
[Limit orders] orders list layout (pure components)

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

1. Orders type switcher
2. Orders table
3. Orders table pagination

image

image

### CODE REVIEW

**Comment by shoom3301** [comment]
1. fixed
2. fixed
3. -
4. fixed
5. Will be developed here -> https://github.com/cowprotocol/cowswap/issues/1350

@elena-zh

**Comment by elena-zh** [comment]
Hey @shoom3301 , the table looks much better now!
 However, a still have some nitpicks: 
1. Cosmos: icons are compressed on a screen width change
icons
2. I still vote for having different messages for cases 1-3, but I believe it will be changed in following PRs 
3. Amounts do not show titles on hover (case 4)
4. As far as I can understand, cases 5-6 will be fixed in #1350 . Correct?
5. Issue with statuses: The order should be in 'Open' status when it is pending. Besides, 'Cancelling' status is missing when an order is canceling (now 'Pending' is displayed for both 'Open' and 'Cancelling')
cancelling
6. 'presignaturePending' status should be 'Signing' 

Thanks!

**Comment by shoom3301** [comment]
1 - done
2 -added message for disconnected wallet state. For unsupported network - I can't reproduce
3 - done
4 - correct
5 - done
6 - done

**Comment by elena-zh** [comment]
Hey @shoom3301 , case 2: open this link, connect to MM, change a network to an unsupported one in the MM: 
https://swap-g0hvgiwwq-cowswap.vercel.app/#/1/swap/WETH
image
OR this link with the same steps: 
https://swap-dev-git-limit-orders-orders-list-cowswap.vercel.app/#/1/limit-orders/WETH
image

**Comment by elena-zh** [comment]
The last nitpick is to change 'Pending' status to 'Open' in order to correspond the status in the Account modal. 
image

I will no longer report UI issues here as they will be fixed in UI PRs.

**Comment by elena-zh** [comment]
I have also noticed that Orders history shows 99 orders (and 10 pages)
image
while [Explorer ](https://protocol-explorer.dev.gnosisdev.com/goerli/address/0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d)shows 110:
image

**Comment by elena-zh** [comment]
> We show only up to 100 orders per tab (we do it on purpose)

**Pull request merged**
