### PR TITLE
feat: replace expert mode enabling prompt by UI control

### LINKED ISSUE #2342: Expert mode button is broken inside the Safe app
1. Open CoW Swap inside the safe app
2. Open Settings 
3. Try switching ON the Expert mode

**AR: impossible:** 

**ER**: it should be possible ro switch ON/OFF expert mode

### PR DESCRIPTION
**Pull request by shoom3301**
# Summary

Fixes #2342

`window.prompt()` doesn't work inside an Iframe and with some other cases.

image

image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @shoom3301 , the button becomes always enabled when I switch ON the expert mode once.
image
To reproduce: 
1. Switch ON the expert mode
2. Switch it OFF
3. Switch it ON once again: the Turn ON button will be enabled.

**Review by elena-zh — APPROVED** [review]
Great job!

**Review by tukantje — APPROVED** [review]

**Review by alfetopito — COMMENTED** [review]
2 small notes about this on android in app browser (tried on imtoken and metamask mobile)

1. It's case sensitive, and some places auto-caps the first letter
2. It's quite broken when the keyboard is open

signal-2023-04-20-152340
signal-2023-04-20-152113

**Comment by elena-zh** [comment]
Hey @alfetopito , could you please provide a bit more details about your device model and Android version?
Here are 2 screenshots from integrated browsers in iOS+MM, and Android+imToken, and everything looks good to me:
image
image

**Comment by tukantje** [comment]
@alfetopito https://github.com/cowprotocol/cowswap/pull/2344#issuecomment-1516435780

**Pull request merged**
