### PR TITLE
fix: favourite tokens are not aligned

### LINKED ISSUE #4457: Favourite tokens are misaligned when token w/o image is displayed there
Favourite tokens are misaligned when token w/o image is displayed there.
See the image: 
image

**To reproduce:** 
1. Go to https://swap.cow.fi/#/account/tokens
2. Select some favoutite tokens that don't have image
3. Go to the Swap page and open the token list

**AR**: tokens are misaligned

**ER**: tokens are aligned

### PR DESCRIPTION
**Pull request by lukicenturi**
# Summary

Fixes #4457

High-level description of what your changes are accomplishing
Just change some styling
Screenshot at Jun 25 20-34-30
Screenshot at Jun 25 20-34-12

### CODE REVIEW

**Review by shoom3301 — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
Thanks again!

**Review by elena-zh — APPROVED** [review]
Hey @lukicenturi , thank you for fixing this!

**Comment by alfetopito** [comment]
@lukicenturi unfortunately, we recently merged changes touching the same files.
Can you please resolve the conflicts? It's mostly renamings.

**Comment by lukicenturi** [comment]
> @lukicenturi unfortunately, we recently merged changes touching the same files. Can you please resolve the conflicts? It's mostly renamings.

should be fine now I guess

**Pull request merged**
